//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups information on how the resource has already been used
 * 
 * <p>Java class for actualUseInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="actualUseInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="actualUse">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="humanUse"/>
 *               &lt;enumeration value="nlpApplications"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}useNLPSpecific" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="usageReport" type="{http://www.ilsp.gr/META-XMLSchema}documentationInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="derivedResource" type="{http://www.ilsp.gr/META-XMLSchema}targetResourceInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="usageProject" type="{http://www.ilsp.gr/META-XMLSchema}projectInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="actualUseDetails" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "actualUseInfoType", propOrder = {
    "actualUse",
    "useNLPSpecific",
    "usageReport",
    "derivedResource",
    "usageProject",
    "actualUseDetails"
})
public class ActualUseInfoType {

    @XmlElement(required = true)
    protected String actualUse;
    protected List<String> useNLPSpecific;
    protected List<DocumentationInfoType> usageReport;
    protected List<TargetResourceInfoType> derivedResource;
    protected List<ProjectInfoType> usageProject;
    protected String actualUseDetails;

    /**
     * Gets the value of the actualUse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualUse() {
        return actualUse;
    }

    /**
     * Sets the value of the actualUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualUse(String value) {
        this.actualUse = value;
    }

    /**
     * Specifies the NLP application for which the resource iscreated or the application in which it has actually been used.Gets the value of the useNLPSpecific property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the useNLPSpecific property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUseNLPSpecific().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUseNLPSpecific() {
        if (useNLPSpecific == null) {
            useNLPSpecific = new ArrayList<String>();
        }
        return this.useNLPSpecific;
    }

    /**
     * Gets the value of the usageReport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usageReport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsageReport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentationInfoType }
     * 
     * 
     */
    public List<DocumentationInfoType> getUsageReport() {
        if (usageReport == null) {
            usageReport = new ArrayList<DocumentationInfoType>();
        }
        return this.usageReport;
    }

    /**
     * Gets the value of the derivedResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the derivedResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDerivedResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TargetResourceInfoType }
     * 
     * 
     */
    public List<TargetResourceInfoType> getDerivedResource() {
        if (derivedResource == null) {
            derivedResource = new ArrayList<TargetResourceInfoType>();
        }
        return this.derivedResource;
    }

    /**
     * Gets the value of the usageProject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usageProject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsageProject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProjectInfoType }
     * 
     * 
     */
    public List<ProjectInfoType> getUsageProject() {
        if (usageProject == null) {
            usageProject = new ArrayList<ProjectInfoType>();
        }
        return this.usageProject;
    }

    /**
     * Gets the value of the actualUseDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActualUseDetails() {
        return actualUseDetails;
    }

    /**
     * Sets the value of the actualUseDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActualUseDetails(String value) {
        this.actualUseDetails = value;
    }

}
