//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups information on the annotated part(s) of a resource
 * 
 * <p>Java class for annotationInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="annotationInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}annotationType"/>
 *         &lt;element name="annotationStandoff" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}segmentationLevel" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}annotationFormat" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}tagset" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}conformanceToStandardsBestPractices" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="theoreticModel" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="500"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="annotationManual" type="{http://www.ilsp.gr/META-XMLSchema}documentationInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="annotationMode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *               &lt;enumeration value="automatic"/>
 *               &lt;enumeration value="manual"/>
 *               &lt;enumeration value="mixed"/>
 *               &lt;enumeration value="interactive"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="annotationModeDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="annotationTool" type="{http://www.ilsp.gr/META-XMLSchema}targetResourceInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="sizePerAnnotation" type="{http://www.ilsp.gr/META-XMLSchema}sizeInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "annotationInfoType", propOrder = {
    "annotationType",
    "annotationStandoff",
    "segmentationLevel",
    "annotationFormat",
    "tagset",
    "conformanceToStandardsBestPractices",
    "theoreticModel",
    "annotationManual",
    "annotationMode",
    "annotationModeDetails",
    "annotationTool",
    "sizePerAnnotation"
})
public class AnnotationInfoType {

    @XmlElement(required = true)
    protected String annotationType;
    protected Boolean annotationStandoff;
    protected List<String> segmentationLevel;
    protected String annotationFormat;
    protected String tagset;
    protected List<String> conformanceToStandardsBestPractices;
    protected String theoreticModel;
    protected List<DocumentationInfoType> annotationManual;
    protected String annotationMode;
    protected String annotationModeDetails;
    protected List<TargetResourceInfoType> annotationTool;
    protected SizeInfoType sizePerAnnotation;

    /**
     * Specifies the annotation level of the resource or the annotation type a tool/ service requires or produces as an output
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnotationType() {
        return annotationType;
    }

    /**
     * Sets the value of the annotationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnotationType(String value) {
        this.annotationType = value;
    }

    /**
     * Gets the value of the annotationStandoff property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAnnotationStandoff() {
        return annotationStandoff;
    }

    /**
     * Sets the value of the annotationStandoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAnnotationStandoff(Boolean value) {
        this.annotationStandoff = value;
    }

    /**
     * Specifies the segmentation unit in terms of which the resource has been segmented or the level of segmentation a tool/service requires/outputs Gets the value of the segmentationLevel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the segmentationLevel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegmentationLevel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSegmentationLevel() {
        if (segmentationLevel == null) {
            segmentationLevel = new ArrayList<String>();
        }
        return this.segmentationLevel;
    }

    /**
     * Specifies the format that is used in the annotation process since often the mime type will not be sufficient for machine processing
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnotationFormat() {
        return annotationFormat;
    }

    /**
     * Sets the value of the annotationFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnotationFormat(String value) {
        this.annotationFormat = value;
    }

    /**
     * A name or a url reference to the tagset used in the annotation of the resource or used by the tool/service
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTagset() {
        return tagset;
    }

    /**
     * Sets the value of the tagset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTagset(String value) {
        this.tagset = value;
    }

    /**
     * Specifies the standards or the best practices to which the tagset used for the annotation conforms Gets the value of the conformanceToStandardsBestPractices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conformanceToStandardsBestPractices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConformanceToStandardsBestPractices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getConformanceToStandardsBestPractices() {
        if (conformanceToStandardsBestPractices == null) {
            conformanceToStandardsBestPractices = new ArrayList<String>();
        }
        return this.conformanceToStandardsBestPractices;
    }

    /**
     * Gets the value of the theoreticModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTheoreticModel() {
        return theoreticModel;
    }

    /**
     * Sets the value of the theoreticModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTheoreticModel(String value) {
        this.theoreticModel = value;
    }

    /**
     * Gets the value of the annotationManual property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotationManual property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotationManual().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentationInfoType }
     * 
     * 
     */
    public List<DocumentationInfoType> getAnnotationManual() {
        if (annotationManual == null) {
            annotationManual = new ArrayList<DocumentationInfoType>();
        }
        return this.annotationManual;
    }

    /**
     * Gets the value of the annotationMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnotationMode() {
        return annotationMode;
    }

    /**
     * Sets the value of the annotationMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnotationMode(String value) {
        this.annotationMode = value;
    }

    /**
     * Gets the value of the annotationModeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnnotationModeDetails() {
        return annotationModeDetails;
    }

    /**
     * Sets the value of the annotationModeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnnotationModeDetails(String value) {
        this.annotationModeDetails = value;
    }

    /**
     * Gets the value of the annotationTool property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotationTool property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotationTool().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TargetResourceInfoType }
     * 
     * 
     */
    public List<TargetResourceInfoType> getAnnotationTool() {
        if (annotationTool == null) {
            annotationTool = new ArrayList<TargetResourceInfoType>();
        }
        return this.annotationTool;
    }

    /**
     * Gets the value of the sizePerAnnotation property.
     * 
     * @return
     *     possible object is
     *     {@link SizeInfoType }
     *     
     */
    public SizeInfoType getSizePerAnnotation() {
        return sizePerAnnotation;
    }

    /**
     * Sets the value of the sizePerAnnotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SizeInfoType }
     *     
     */
    public void setSizePerAnnotation(SizeInfoType value) {
        this.sizePerAnnotation = value;
    }

}
