//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups together information on the capture of the audio or video part of a corpus
 * 
 * <p>Java class for captureInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="captureInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="capturingDeviceType" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="studioEquipment"/>
 *               &lt;enumeration value="microphone"/>
 *               &lt;enumeration value="closeTalkMicrophone"/>
 *               &lt;enumeration value="farfieldMicrophone"/>
 *               &lt;enumeration value="lavalierMicrophone"/>
 *               &lt;enumeration value="microphoneArray"/>
 *               &lt;enumeration value="embeddedMicrophone"/>
 *               &lt;enumeration value="largeMembraneMicrophone"/>
 *               &lt;enumeration value="laryngograph"/>
 *               &lt;enumeration value="telephoneFixed"/>
 *               &lt;enumeration value="telephoneMobile"/>
 *               &lt;enumeration value="telephoneIP"/>
 *               &lt;enumeration value="camera"/>
 *               &lt;enumeration value="webcam"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="capturingDeviceTypeDetails" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="400"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="capturingDetails" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="400"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="capturingEnvironment" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="complex"/>
 *               &lt;enumeration value="plain"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="sensorTechnology" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="sceneIllumination" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="daylight"/>
 *               &lt;enumeration value="fix"/>
 *               &lt;enumeration value="multipleSources"/>
 *               &lt;enumeration value="singleSource"/>
 *               &lt;enumeration value="variable"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}personSourceSetInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "captureInfoType", propOrder = {
    "capturingDeviceType",
    "capturingDeviceTypeDetails",
    "capturingDetails",
    "capturingEnvironment",
    "sensorTechnology",
    "sceneIllumination",
    "personSourceSetInfo"
})
public class CaptureInfoType {

    protected List<String> capturingDeviceType;
    protected String capturingDeviceTypeDetails;
    protected String capturingDetails;
    protected String capturingEnvironment;
    protected List<String> sensorTechnology;
    protected String sceneIllumination;
    protected PersonSourceSetInfoType personSourceSetInfo;

    /**
     * Gets the value of the capturingDeviceType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the capturingDeviceType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCapturingDeviceType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCapturingDeviceType() {
        if (capturingDeviceType == null) {
            capturingDeviceType = new ArrayList<String>();
        }
        return this.capturingDeviceType;
    }

    /**
     * Gets the value of the capturingDeviceTypeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapturingDeviceTypeDetails() {
        return capturingDeviceTypeDetails;
    }

    /**
     * Sets the value of the capturingDeviceTypeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapturingDeviceTypeDetails(String value) {
        this.capturingDeviceTypeDetails = value;
    }

    /**
     * Gets the value of the capturingDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapturingDetails() {
        return capturingDetails;
    }

    /**
     * Sets the value of the capturingDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapturingDetails(String value) {
        this.capturingDetails = value;
    }

    /**
     * Gets the value of the capturingEnvironment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapturingEnvironment() {
        return capturingEnvironment;
    }

    /**
     * Sets the value of the capturingEnvironment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapturingEnvironment(String value) {
        this.capturingEnvironment = value;
    }

    /**
     * Gets the value of the sensorTechnology property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sensorTechnology property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSensorTechnology().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSensorTechnology() {
        if (sensorTechnology == null) {
            sensorTechnology = new ArrayList<String>();
        }
        return this.sensorTechnology;
    }

    /**
     * Gets the value of the sceneIllumination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSceneIllumination() {
        return sceneIllumination;
    }

    /**
     * Sets the value of the sceneIllumination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSceneIllumination(String value) {
        this.sceneIllumination = value;
    }

    /**
     * Groups information on the persons (speakers, video participants, etc.) in the audio andvideoparts of the resource
     * 
     * @return
     *     possible object is
     *     {@link PersonSourceSetInfoType }
     *     
     */
    public PersonSourceSetInfoType getPersonSourceSetInfo() {
        return personSourceSetInfo;
    }

    /**
     * Sets the value of the personSourceSetInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonSourceSetInfoType }
     *     
     */
    public void setPersonSourceSetInfo(PersonSourceSetInfoType value) {
        this.personSourceSetInfo = value;
    }

}
