//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups together information on the compression status and method of a resource
 * 
 * <p>Java class for compressionInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="compressionInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="compression" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="compressionName" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *               &lt;enumeration value="mpg"/>
 *               &lt;enumeration value="avi"/>
 *               &lt;enumeration value="mov"/>
 *               &lt;enumeration value="flac"/>
 *               &lt;enumeration value="shorten"/>
 *               &lt;enumeration value="mp3"/>
 *               &lt;enumeration value="oggVorbis"/>
 *               &lt;enumeration value="atrac"/>
 *               &lt;enumeration value="aac"/>
 *               &lt;enumeration value="mpeg"/>
 *               &lt;enumeration value="realAudio"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="compressionLoss" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "compressionInfoType", propOrder = {
    "compression",
    "compressionName",
    "compressionLoss"
})
public class CompressionInfoType {

    protected boolean compression;
    protected List<String> compressionName;
    protected Boolean compressionLoss;

    /**
     * Gets the value of the compression property.
     * 
     */
    public boolean isCompression() {
        return compression;
    }

    /**
     * Sets the value of the compression property.
     * 
     */
    public void setCompression(boolean value) {
        this.compression = value;
    }

    /**
     * Gets the value of the compressionName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compressionName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompressionName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCompressionName() {
        if (compressionName == null) {
            compressionName = new ArrayList<String>();
        }
        return this.compressionName;
    }

    /**
     * Gets the value of the compressionLoss property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCompressionLoss() {
        return compressionLoss;
    }

    /**
     * Sets the value of the compressionLoss property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCompressionLoss(Boolean value) {
        this.compressionLoss = value;
    }

}
