//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups together information required for n-gram resources; information can be provided both as regards features drawn from the source corpus (e.g. language coverage, size, format, domains etc.) and features pertaining to the n-gram output itself (e.g. range of n-grams, type of item included, etc.)
 * 
 * <p>Java class for corpusTextNgramInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="corpusTextNgramInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mediaType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}ngramInfo"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}lingualityInfo"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}languageInfo" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}modalityInfo" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}sizeInfo" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}textFormatInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}characterEncodingInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}annotationInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}domainInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}textClassificationInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}timeCoverageInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}geographicCoverageInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}creationInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "corpusTextNgramInfoType", propOrder = {
    "mediaType",
    "ngramInfo",
    "lingualityInfo",
    "languageInfo",
    "modalityInfo",
    "sizeInfo",
    "textFormatInfo",
    "characterEncodingInfo",
    "annotationInfo",
    "domainInfo",
    "textClassificationInfo",
    "timeCoverageInfo",
    "geographicCoverageInfo",
    "creationInfo"
})
public class CorpusTextNgramInfoType {

    @XmlElement(required = true)
    protected String mediaType;
    @XmlElement(required = true)
    protected NgramInfoType ngramInfo;
    @XmlElement(required = true)
    protected LingualityInfo lingualityInfo;
    @XmlElement(required = true)
    protected List<LanguageInfoType> languageInfo;
    protected ModalityInfoType modalityInfo;
    @XmlElement(required = true)
    protected List<SizeInfoType> sizeInfo;
    protected List<TextFormatInfoType> textFormatInfo;
    protected List<CharacterEncodingInfoType> characterEncodingInfo;
    protected List<AnnotationInfoType> annotationInfo;
    protected List<DomainInfoType> domainInfo;
    protected List<TextClassificationInfoType> textClassificationInfo;
    protected List<TimeCoverageInfoType> timeCoverageInfo;
    protected List<GeographicCoverageInfoType> geographicCoverageInfo;
    protected CreationInfoType creationInfo;

    /**
     * Gets the value of the mediaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaType() {
        return mediaType;
    }

    /**
     * Sets the value of the mediaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaType(String value) {
        this.mediaType = value;
    }

    /**
     * Gets the value of the ngramInfo property.
     * 
     * @return
     *     possible object is
     *     {@link NgramInfoType }
     *     
     */
    public NgramInfoType getNgramInfo() {
        return ngramInfo;
    }

    /**
     * Sets the value of the ngramInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link NgramInfoType }
     *     
     */
    public void setNgramInfo(NgramInfoType value) {
        this.ngramInfo = value;
    }

    /**
     * Groups information on the number of languages of the resource part and of the way they are combined to each other
     * 
     * @return
     *     possible object is
     *     {@link LingualityInfo }
     *     
     */
    public LingualityInfo getLingualityInfo() {
        return lingualityInfo;
    }

    /**
     * Sets the value of the lingualityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LingualityInfo }
     *     
     */
    public void setLingualityInfo(LingualityInfo value) {
        this.lingualityInfo = value;
    }

    /**
     * Groups information on the languages represented in the resource Gets the value of the languageInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languageInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguageInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LanguageInfoType }
     * 
     * 
     */
    public List<LanguageInfoType> getLanguageInfo() {
        if (languageInfo == null) {
            languageInfo = new ArrayList<LanguageInfoType>();
        }
        return this.languageInfo;
    }

    /**
     * Groups information on the modalities represented in the resource
     * 
     * @return
     *     possible object is
     *     {@link ModalityInfoType }
     *     
     */
    public ModalityInfoType getModalityInfo() {
        return modalityInfo;
    }

    /**
     * Sets the value of the modalityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModalityInfoType }
     *     
     */
    public void setModalityInfo(ModalityInfoType value) {
        this.modalityInfo = value;
    }

    /**
     * Groups information on the size of the resource or of resource parts Gets the value of the sizeInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sizeInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSizeInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SizeInfoType }
     * 
     * 
     */
    public List<SizeInfoType> getSizeInfo() {
        if (sizeInfo == null) {
            sizeInfo = new ArrayList<SizeInfoType>();
        }
        return this.sizeInfo;
    }

    /**
     * Groups information on the text format(s) of a resource Gets the value of the textFormatInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textFormatInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextFormatInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextFormatInfoType }
     * 
     * 
     */
    public List<TextFormatInfoType> getTextFormatInfo() {
        if (textFormatInfo == null) {
            textFormatInfo = new ArrayList<TextFormatInfoType>();
        }
        return this.textFormatInfo;
    }

    /**
     * Groups together information on character encoding of the resource Gets the value of the characterEncodingInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the characterEncodingInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCharacterEncodingInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CharacterEncodingInfoType }
     * 
     * 
     */
    public List<CharacterEncodingInfoType> getCharacterEncodingInfo() {
        if (characterEncodingInfo == null) {
            characterEncodingInfo = new ArrayList<CharacterEncodingInfoType>();
        }
        return this.characterEncodingInfo;
    }

    /**
     * Groups information on the annotated part(s) of a resource Gets the value of the annotationInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the annotationInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotationInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnnotationInfoType }
     * 
     * 
     */
    public List<AnnotationInfoType> getAnnotationInfo() {
        if (annotationInfo == null) {
            annotationInfo = new ArrayList<AnnotationInfoType>();
        }
        return this.annotationInfo;
    }

    /**
     * Groups together information on domains represented in the resource; can be repeated for parts of the resource with distinct domain Gets the value of the domainInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the domainInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDomainInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DomainInfoType }
     * 
     * 
     */
    public List<DomainInfoType> getDomainInfo() {
        if (domainInfo == null) {
            domainInfo = new ArrayList<DomainInfoType>();
        }
        return this.domainInfo;
    }

    /**
     * Groups together information on text type/genre of the resource Gets the value of the textClassificationInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textClassificationInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextClassificationInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextClassificationInfoType }
     * 
     * 
     */
    public List<TextClassificationInfoType> getTextClassificationInfo() {
        if (textClassificationInfo == null) {
            textClassificationInfo = new ArrayList<TextClassificationInfoType>();
        }
        return this.textClassificationInfo;
    }

    /**
     * Groups together information on time classification of the resource Gets the value of the timeCoverageInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timeCoverageInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimeCoverageInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimeCoverageInfoType }
     * 
     * 
     */
    public List<TimeCoverageInfoType> getTimeCoverageInfo() {
        if (timeCoverageInfo == null) {
            timeCoverageInfo = new ArrayList<TimeCoverageInfoType>();
        }
        return this.timeCoverageInfo;
    }

    /**
     * Groups information on geographic classification of the resource Gets the value of the geographicCoverageInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geographicCoverageInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeographicCoverageInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeographicCoverageInfoType }
     * 
     * 
     */
    public List<GeographicCoverageInfoType> getGeographicCoverageInfo() {
        if (geographicCoverageInfo == null) {
            geographicCoverageInfo = new ArrayList<GeographicCoverageInfoType>();
        }
        return this.geographicCoverageInfo;
    }

    /**
     * Groups together information on the resource creation (e.g. for corpora, selection of texts/audio files/ video files etc. and structural encoding thereof; for lexica, construction of lemma list etc.)
     * 
     * @return
     *     possible object is
     *     {@link CreationInfoType }
     *     
     */
    public CreationInfoType getCreationInfo() {
        return creationInfo;
    }

    /**
     * Sets the value of the creationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreationInfoType }
     *     
     */
    public void setCreationInfo(CreationInfoType value) {
        this.creationInfo = value;
    }

}
