//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups together information on the resource creation (e.g. for corpora, selection of texts/audio files/ video files etc. and structural encoding thereof; for lexica, construction of lemma list etc.)
 * 
 * <p>Java class for creationInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="creationInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="originalSource" type="{http://www.ilsp.gr/META-XMLSchema}targetResourceInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="creationMode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="automatic"/>
 *               &lt;enumeration value="manual"/>
 *               &lt;enumeration value="mixed"/>
 *               &lt;enumeration value="interactive"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="creationModeDetails" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="creationTool" type="{http://www.ilsp.gr/META-XMLSchema}targetResourceInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "creationInfoType", propOrder = {
    "originalSource",
    "creationMode",
    "creationModeDetails",
    "creationTool"
})
public class CreationInfoType {

    protected List<TargetResourceInfoType> originalSource;
    protected String creationMode;
    protected String creationModeDetails;
    protected List<TargetResourceInfoType> creationTool;

    /**
     * Gets the value of the originalSource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the originalSource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOriginalSource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TargetResourceInfoType }
     * 
     * 
     */
    public List<TargetResourceInfoType> getOriginalSource() {
        if (originalSource == null) {
            originalSource = new ArrayList<TargetResourceInfoType>();
        }
        return this.originalSource;
    }

    /**
     * Gets the value of the creationMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationMode() {
        return creationMode;
    }

    /**
     * Sets the value of the creationMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationMode(String value) {
        this.creationMode = value;
    }

    /**
     * Gets the value of the creationModeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationModeDetails() {
        return creationModeDetails;
    }

    /**
     * Sets the value of the creationModeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationModeDetails(String value) {
        this.creationModeDetails = value;
    }

    /**
     * Gets the value of the creationTool property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creationTool property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreationTool().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TargetResourceInfoType }
     * 
     * 
     */
    public List<TargetResourceInfoType> getCreationTool() {
        if (creationTool == null) {
            creationTool = new ArrayList<TargetResourceInfoType>();
        }
        return this.creationTool;
    }

}
