//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups information on the distribution of the resource
 * 
 * <p>Java class for distributionInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="distributionInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="availability">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *               &lt;enumeration value="available"/>
 *               &lt;enumeration value="underReview"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}licenceInfo" maxOccurs="unbounded"/>
 *         &lt;element name="allowsUsesBesidesDGT" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="iprHolder" type="{http://www.ilsp.gr/META-XMLSchema}actorInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "distributionInfoType", propOrder = {
    "availability",
    "licenceInfo",
//    "allowsUsesBesidesDGT",
    "iprHolder"
})
@XmlSeeAlso({
    DistributionInfo.class
})
public class DistributionInfoType {

    @XmlElement(required = true)
    protected String availability;
    @XmlElement(required = true)
    protected List<LicenceInfo> licenceInfo;
//    protected boolean allowsUsesBesidesDGT;
    protected List<ActorInfoType> iprHolder;

    /**
     * Gets the value of the availability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAvailability() {
        return availability;
    }

    /**
     * Sets the value of the availability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAvailability(String value) {
        this.availability = value;
    }

    /**
     * Groups information on different forms of distribution of the resource and the corresponding licences under which they are distributed; can be repeated to allow for different modes of access and conditions of use (e.g. free for academic use, on-a-fee basis for commercial use, download of a sample for free use etc.) Gets the value of the licenceInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the licenceInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLicenceInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LicenceInfo }
     * 
     * 
     */
    public List<LicenceInfo> getLicenceInfo() {
        if (licenceInfo == null) {
            licenceInfo = new ArrayList<LicenceInfo>();
        }
        return this.licenceInfo;
    }

//    /**
//     * Gets the value of the allowsUsesBesidesDGT property.
//     * 
//     */
//    public boolean isAllowsUsesBesidesDGT() {
//        return allowsUsesBesidesDGT;
//    }
//
//    /**
//     * Sets the value of the allowsUsesBesidesDGT property.
//     * 
//     */
//    public void setAllowsUsesBesidesDGT(boolean value) {
//        this.allowsUsesBesidesDGT = value;
//    }

    /**
     * Gets the value of the iprHolder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the iprHolder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIprHolder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActorInfoType }
     * 
     * 
     */
    public List<ActorInfoType> getIprHolder() {
        if (iprHolder == null) {
            iprHolder = new ArrayList<ActorInfoType>();
        }
        return this.iprHolder;
    }

}
