//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups together information on domains represented in the resource; can be repeated for parts of the resource with distinct domain
 * 
 * <p>Java class for domainInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="domainInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}domain" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}domainId" maxOccurs="unbounded"/>
 *         &lt;element name="sizePerDomain" type="{http://www.ilsp.gr/META-XMLSchema}sizeInfoType" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}conformanceToClassificationScheme" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "domainInfoType", propOrder = {
    "domain",
    "domainId",
    "sizePerDomain",
    "conformanceToClassificationScheme"
})
public class DomainInfoType {

    @XmlElement(required = true)
    protected List<String> domain;
    @XmlElement(required = true)
    protected List<String> domainId;
    protected SizeInfoType sizePerDomain;
    protected String conformanceToClassificationScheme;

    /**
     * Gets the value of the domain property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the domain property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDomain().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDomain() {
        if (domain == null) {
            domain = new ArrayList<String>();
        }
        return this.domain;
    }

    /**
     * Gets the value of the domainId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the domainId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDomainId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDomainId() {
        if (domainId == null) {
            domainId = new ArrayList<String>();
        }
        return this.domainId;
    }

    /**
     * Gets the value of the sizePerDomain property.
     * 
     * @return
     *     possible object is
     *     {@link SizeInfoType }
     *     
     */
    public SizeInfoType getSizePerDomain() {
        return sizePerDomain;
    }

    /**
     * Sets the value of the sizePerDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link SizeInfoType }
     *     
     */
    public void setSizePerDomain(SizeInfoType value) {
        this.sizePerDomain = value;
    }

    /**
     * Gets the value of the conformanceToClassificationScheme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConformanceToClassificationScheme() {
        return conformanceToClassificationScheme;
    }

    /**
     * Sets the value of the conformanceToClassificationScheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConformanceToClassificationScheme(String value) {
        this.conformanceToClassificationScheme = value;
    }

}
