//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups together information on the operation requirements of the Language Descriptions
 * 
 * <p>Java class for languageDescriptionOperationInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="languageDescriptionOperationInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}runningEnvironmentInfo" minOccurs="0"/>
 *         &lt;element name="relatedLexiconInfo" type="{http://www.ilsp.gr/META-XMLSchema}relatedLexiconInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "languageDescriptionOperationInfoType", propOrder = {
    "runningEnvironmentInfo",
    "relatedLexiconInfo"
})
public class LanguageDescriptionOperationInfoType {

    protected RunningEnvironmentInfoType runningEnvironmentInfo;
    protected RelatedLexiconInfoType relatedLexiconInfo;

    /**
     * Groups together information on the running environment of a tool or a language description
     * 
     * @return
     *     possible object is
     *     {@link RunningEnvironmentInfoType }
     *     
     */
    public RunningEnvironmentInfoType getRunningEnvironmentInfo() {
        return runningEnvironmentInfo;
    }

    /**
     * Sets the value of the runningEnvironmentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RunningEnvironmentInfoType }
     *     
     */
    public void setRunningEnvironmentInfo(RunningEnvironmentInfoType value) {
        this.runningEnvironmentInfo = value;
    }

    /**
     * Gets the value of the relatedLexiconInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RelatedLexiconInfoType }
     *     
     */
    public RelatedLexiconInfoType getRelatedLexiconInfo() {
        return relatedLexiconInfo;
    }

    /**
     * Sets the value of the relatedLexiconInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatedLexiconInfoType }
     *     
     */
    public void setRelatedLexiconInfo(RelatedLexiconInfoType value) {
        this.relatedLexiconInfo = value;
    }

}
