//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups together information on language descriptions (grammars)
 * 
 * <p>Java class for languageDescriptionInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="languageDescriptionInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resourceType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="languageDescriptionType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="grammar"/>
 *               &lt;enumeration value="languageModel"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}languageDescriptionEncodingInfo" minOccurs="0"/>
 *         &lt;element name="languageDescriptionMediaType">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}languageDescriptionTextInfo" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "languageDescriptionInfoType", propOrder = {
    "resourceType",
    "languageDescriptionType",
    "languageDescriptionEncodingInfo",
    "languageDescriptionMediaType"
})
public class LanguageDescriptionInfoType {

    @XmlElement(required = true)
    protected String resourceType;
    @XmlElement(required = true)
    protected String languageDescriptionType;
    protected LanguageDescriptionEncodingInfoType languageDescriptionEncodingInfo;
    @XmlElement(required = true)
    protected LanguageDescriptionInfoType.LanguageDescriptionMediaType languageDescriptionMediaType;

    /**
     * Gets the value of the resourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * Sets the value of the resourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceType(String value) {
        this.resourceType = value;
    }

    /**
     * Gets the value of the languageDescriptionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageDescriptionType() {
        return languageDescriptionType;
    }

    /**
     * Sets the value of the languageDescriptionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageDescriptionType(String value) {
        this.languageDescriptionType = value;
    }

    /**
     * Groups together information on the contents of the LanguageDescriptions
     * 
     * @return
     *     possible object is
     *     {@link LanguageDescriptionEncodingInfoType }
     *     
     */
    public LanguageDescriptionEncodingInfoType getLanguageDescriptionEncodingInfo() {
        return languageDescriptionEncodingInfo;
    }

    /**
     * Sets the value of the languageDescriptionEncodingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageDescriptionEncodingInfoType }
     *     
     */
    public void setLanguageDescriptionEncodingInfo(LanguageDescriptionEncodingInfoType value) {
        this.languageDescriptionEncodingInfo = value;
    }

    /**
     * Gets the value of the languageDescriptionMediaType property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageDescriptionInfoType.LanguageDescriptionMediaType }
     *     
     */
    public LanguageDescriptionInfoType.LanguageDescriptionMediaType getLanguageDescriptionMediaType() {
        return languageDescriptionMediaType;
    }

    /**
     * Sets the value of the languageDescriptionMediaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageDescriptionInfoType.LanguageDescriptionMediaType }
     *     
     */
    public void setLanguageDescriptionMediaType(LanguageDescriptionInfoType.LanguageDescriptionMediaType value) {
        this.languageDescriptionMediaType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}languageDescriptionTextInfo" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "languageDescriptionTextInfo"
    })
    public static class LanguageDescriptionMediaType {

        protected LanguageDescriptionTextInfo languageDescriptionTextInfo;

        /**
         * Groups together all information relevant to the text module of a language description (e.g. format, languages, size etc.); it is obligatory for all language descriptions
         * 
         * @return
         *     possible object is
         *     {@link LanguageDescriptionTextInfo }
         *     
         */
        public LanguageDescriptionTextInfo getLanguageDescriptionTextInfo() {
            return languageDescriptionTextInfo;
        }

        /**
         * Sets the value of the languageDescriptionTextInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link LanguageDescriptionTextInfo }
         *     
         */
        public void setLanguageDescriptionTextInfo(LanguageDescriptionTextInfo value) {
            this.languageDescriptionTextInfo = value;
        }

    }

}
