//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for languageScriptNameType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="languageScriptNameType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="100"/>
 *     &lt;enumeration value="Afaka"/>
 *     &lt;enumeration value="Caucasian Albanian"/>
 *     &lt;enumeration value="Ahom; Tai Ahom"/>
 *     &lt;enumeration value="Arabic"/>
 *     &lt;enumeration value="Imperial Aramaic"/>
 *     &lt;enumeration value="Armenian"/>
 *     &lt;enumeration value="Avestan"/>
 *     &lt;enumeration value="Balinese"/>
 *     &lt;enumeration value="Bamum"/>
 *     &lt;enumeration value="Bassa Vah"/>
 *     &lt;enumeration value="Batak"/>
 *     &lt;enumeration value="Bengali"/>
 *     &lt;enumeration value="Blissymbols"/>
 *     &lt;enumeration value="Bopomofo"/>
 *     &lt;enumeration value="Brahmi"/>
 *     &lt;enumeration value="Braille"/>
 *     &lt;enumeration value="Buginese"/>
 *     &lt;enumeration value="Buhid"/>
 *     &lt;enumeration value="Chakma"/>
 *     &lt;enumeration value="Unified Canadian Aboriginal Syllabics"/>
 *     &lt;enumeration value="Carian"/>
 *     &lt;enumeration value="Cham"/>
 *     &lt;enumeration value="Cherokee"/>
 *     &lt;enumeration value="Cirth"/>
 *     &lt;enumeration value="Coptic"/>
 *     &lt;enumeration value="Cypriot"/>
 *     &lt;enumeration value="Cyrillic"/>
 *     &lt;enumeration value="Cyrillic (Old Church Slavonic variant)"/>
 *     &lt;enumeration value="Devanagari; Nagari"/>
 *     &lt;enumeration value="Deseret; Mormon"/>
 *     &lt;enumeration value="Duployan shorthand; Duployan stenography"/>
 *     &lt;enumeration value="Egyptian demotic"/>
 *     &lt;enumeration value="Egyptian hieratic"/>
 *     &lt;enumeration value="Egyptian hieroglyphs"/>
 *     &lt;enumeration value="Elbasan"/>
 *     &lt;enumeration value="Ethiopic; Geʻez; Ge'ez"/>
 *     &lt;enumeration value="Khutsuri (Asomtavruli and Nuskhuri)"/>
 *     &lt;enumeration value="Georgian (Mkhedruli)"/>
 *     &lt;enumeration value="Glagolitic"/>
 *     &lt;enumeration value="Gothic"/>
 *     &lt;enumeration value="Grantha"/>
 *     &lt;enumeration value="Greek"/>
 *     &lt;enumeration value="Gujarati"/>
 *     &lt;enumeration value="Gurmukhi"/>
 *     &lt;enumeration value="Hangul; Hangŭl; Hangeul"/>
 *     &lt;enumeration value="Han; Hanzi; Kanji; Hanja"/>
 *     &lt;enumeration value="Hanunoo; Hanunóo"/>
 *     &lt;enumeration value="Han (Simplified variant)"/>
 *     &lt;enumeration value="Han (Traditional variant)"/>
 *     &lt;enumeration value="Hatran"/>
 *     &lt;enumeration value="Hebrew"/>
 *     &lt;enumeration value="Hiragana"/>
 *     &lt;enumeration value="Anatolian Hieroglyphs; Luwian Hieroglyphs; Hittite Hieroglyphs"/>
 *     &lt;enumeration value="Pahawh Hmong"/>
 *     &lt;enumeration value="Japanese syllabaries (alias for Hiragana + Katakana)"/>
 *     &lt;enumeration value="Old Hungarian; Hungarian Runic"/>
 *     &lt;enumeration value="Indus; Harappan"/>
 *     &lt;enumeration value="Old Italic (Etruscan, Oscan, etc.)"/>
 *     &lt;enumeration value="Javanese"/>
 *     &lt;enumeration value="Japanese (alias for Han + Hiragana + Katakana)"/>
 *     &lt;enumeration value="Jurchen"/>
 *     &lt;enumeration value="Kayah Li"/>
 *     &lt;enumeration value="Katakana"/>
 *     &lt;enumeration value="Kharoshthi"/>
 *     &lt;enumeration value="Khmer"/>
 *     &lt;enumeration value="Khojki"/>
 *     &lt;enumeration value="Kannada"/>
 *     &lt;enumeration value="Korean (alias for Hangul + Han)"/>
 *     &lt;enumeration value="Kpelle"/>
 *     &lt;enumeration value="Kaithi"/>
 *     &lt;enumeration value="Tai Tham; Lanna"/>
 *     &lt;enumeration value="Lao"/>
 *     &lt;enumeration value="Latin (Fraktur variant)"/>
 *     &lt;enumeration value="Latin (Gaelic variant)"/>
 *     &lt;enumeration value="Latin"/>
 *     &lt;enumeration value="Lepcha; Róng"/>
 *     &lt;enumeration value="Limbu"/>
 *     &lt;enumeration value="Linear A"/>
 *     &lt;enumeration value="Linear B"/>
 *     &lt;enumeration value="Lisu; Fraser"/>
 *     &lt;enumeration value="Loma"/>
 *     &lt;enumeration value="Lycian"/>
 *     &lt;enumeration value="Lydian"/>
 *     &lt;enumeration value="Mahajani"/>
 *     &lt;enumeration value="Mandaic; Mandaean"/>
 *     &lt;enumeration value="Manichaean"/>
 *     &lt;enumeration value="Mayan hieroglyphs"/>
 *     &lt;enumeration value="Mende Kikakui"/>
 *     &lt;enumeration value="Meroitic Cursive"/>
 *     &lt;enumeration value="Meroitic Hieroglyphs"/>
 *     &lt;enumeration value="Malayalam"/>
 *     &lt;enumeration value="Modi; Moḍī"/>
 *     &lt;enumeration value="Mongolian"/>
 *     &lt;enumeration value="Moon; Moon code; Moon script; Moon type"/>
 *     &lt;enumeration value="Mro; Mru"/>
 *     &lt;enumeration value="Meitei Mayek; Meithei; Meetei"/>
 *     &lt;enumeration value="Multani"/>
 *     &lt;enumeration value="Myanmar; Burmese"/>
 *     &lt;enumeration value="Old North Arabian; Ancient North Arabian"/>
 *     &lt;enumeration value="Nabataean"/>
 *     &lt;enumeration value="Nakhi Geba; 'Na-'Khi ²Ggŏ-¹baw; Naxi Geba"/>
 *     &lt;enumeration value="N’Ko; N'Ko"/>
 *     &lt;enumeration value="Nüshu"/>
 *     &lt;enumeration value="Ogham"/>
 *     &lt;enumeration value="Ol Chiki; Ol Cemet'; Ol; Santali"/>
 *     &lt;enumeration value="Old Turkic; Orkhon Runic"/>
 *     &lt;enumeration value="Oriya"/>
 *     &lt;enumeration value="Osmanya"/>
 *     &lt;enumeration value="Palmyrene"/>
 *     &lt;enumeration value="Pau Cin Hau"/>
 *     &lt;enumeration value="Old Permic"/>
 *     &lt;enumeration value="Phags-pa"/>
 *     &lt;enumeration value="Inscriptional Pahlavi"/>
 *     &lt;enumeration value="Psalter Pahlavi"/>
 *     &lt;enumeration value="Book Pahlavi"/>
 *     &lt;enumeration value="Phoenician"/>
 *     &lt;enumeration value="Miao; Pollard"/>
 *     &lt;enumeration value="Inscriptional Parthian"/>
 *     &lt;enumeration value="Private use"/>
 *     &lt;enumeration value="Rejang; Redjang; Kaganga"/>
 *     &lt;enumeration value="Rongorongo"/>
 *     &lt;enumeration value="Runic"/>
 *     &lt;enumeration value="Samaritan"/>
 *     &lt;enumeration value="Sarati"/>
 *     &lt;enumeration value="Old South Arabian"/>
 *     &lt;enumeration value="Saurashtra"/>
 *     &lt;enumeration value="SignWriting"/>
 *     &lt;enumeration value="Shavian; Shaw"/>
 *     &lt;enumeration value="Sharada; Śāradā"/>
 *     &lt;enumeration value="Siddham; Siddhaṃ; Siddhamātṛkā"/>
 *     &lt;enumeration value="Khudawadi; Sindhi"/>
 *     &lt;enumeration value="Sinhala"/>
 *     &lt;enumeration value="Sora Sompeng"/>
 *     &lt;enumeration value="Sundanese"/>
 *     &lt;enumeration value="Syloti Nagri"/>
 *     &lt;enumeration value="Syriac"/>
 *     &lt;enumeration value="Syriac (Estrangelo variant)"/>
 *     &lt;enumeration value="Syriac (Western variant)"/>
 *     &lt;enumeration value="Syriac (Eastern variant)"/>
 *     &lt;enumeration value="Tagbanwa"/>
 *     &lt;enumeration value="Takri; Ṭākrī; Ṭāṅkrī"/>
 *     &lt;enumeration value="Tai Le"/>
 *     &lt;enumeration value="New Tai Lue"/>
 *     &lt;enumeration value="Tamil"/>
 *     &lt;enumeration value="Tangut"/>
 *     &lt;enumeration value="Tai Viet"/>
 *     &lt;enumeration value="Telugu"/>
 *     &lt;enumeration value="Tengwar"/>
 *     &lt;enumeration value="Tifinagh; Berber"/>
 *     &lt;enumeration value="Tagalog; Baybayin; Alibata"/>
 *     &lt;enumeration value="Thaana"/>
 *     &lt;enumeration value="Thai"/>
 *     &lt;enumeration value="Tibetan"/>
 *     &lt;enumeration value="Tirhuta"/>
 *     &lt;enumeration value="Ugaritic"/>
 *     &lt;enumeration value="Vai"/>
 *     &lt;enumeration value="Visible Speech"/>
 *     &lt;enumeration value="Warang Citi; Varang Kshiti"/>
 *     &lt;enumeration value="Woleai"/>
 *     &lt;enumeration value="Old Persian"/>
 *     &lt;enumeration value="Sumero-Akkadian cuneiform"/>
 *     &lt;enumeration value="Yi"/>
 *     &lt;enumeration value="Code for inherited script"/>
 *     &lt;enumeration value="Mathematical notation"/>
 *     &lt;enumeration value="Symbols"/>
 *     &lt;enumeration value="Code for unwritten documents"/>
 *     &lt;enumeration value="Code for undetermined script"/>
 *     &lt;enumeration value="Code for uncoded script"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "languageScriptNameType")
@XmlEnum
public enum LanguageScriptNameType {

    @XmlEnumValue("Afaka")
    AFAKA("Afaka"),
    @XmlEnumValue("Caucasian Albanian")
    CAUCASIAN_ALBANIAN("Caucasian Albanian"),
    @XmlEnumValue("Ahom; Tai Ahom")
    AHOM_TAI_AHOM("Ahom; Tai Ahom"),
    @XmlEnumValue("Arabic")
    ARABIC("Arabic"),
    @XmlEnumValue("Imperial Aramaic")
    IMPERIAL_ARAMAIC("Imperial Aramaic"),
    @XmlEnumValue("Armenian")
    ARMENIAN("Armenian"),
    @XmlEnumValue("Avestan")
    AVESTAN("Avestan"),
    @XmlEnumValue("Balinese")
    BALINESE("Balinese"),
    @XmlEnumValue("Bamum")
    BAMUM("Bamum"),
    @XmlEnumValue("Bassa Vah")
    BASSA_VAH("Bassa Vah"),
    @XmlEnumValue("Batak")
    BATAK("Batak"),
    @XmlEnumValue("Bengali")
    BENGALI("Bengali"),
    @XmlEnumValue("Blissymbols")
    BLISSYMBOLS("Blissymbols"),
    @XmlEnumValue("Bopomofo")
    BOPOMOFO("Bopomofo"),
    @XmlEnumValue("Brahmi")
    BRAHMI("Brahmi"),
    @XmlEnumValue("Braille")
    BRAILLE("Braille"),
    @XmlEnumValue("Buginese")
    BUGINESE("Buginese"),
    @XmlEnumValue("Buhid")
    BUHID("Buhid"),
    @XmlEnumValue("Chakma")
    CHAKMA("Chakma"),
    @XmlEnumValue("Unified Canadian Aboriginal Syllabics")
    UNIFIED_CANADIAN_ABORIGINAL_SYLLABICS("Unified Canadian Aboriginal Syllabics"),
    @XmlEnumValue("Carian")
    CARIAN("Carian"),
    @XmlEnumValue("Cham")
    CHAM("Cham"),
    @XmlEnumValue("Cherokee")
    CHEROKEE("Cherokee"),
    @XmlEnumValue("Cirth")
    CIRTH("Cirth"),
    @XmlEnumValue("Coptic")
    COPTIC("Coptic"),
    @XmlEnumValue("Cypriot")
    CYPRIOT("Cypriot"),
    @XmlEnumValue("Cyrillic")
    CYRILLIC("Cyrillic"),
    @XmlEnumValue("Cyrillic (Old Church Slavonic variant)")
    CYRILLIC_OLD_CHURCH_SLAVONIC_VARIANT("Cyrillic (Old Church Slavonic variant)"),
    @XmlEnumValue("Devanagari; Nagari")
    DEVANAGARI_NAGARI("Devanagari; Nagari"),
    @XmlEnumValue("Deseret; Mormon")
    DESERET_MORMON("Deseret; Mormon"),
    @XmlEnumValue("Duployan shorthand; Duployan stenography")
    DUPLOYAN_SHORTHAND_DUPLOYAN_STENOGRAPHY("Duployan shorthand; Duployan stenography"),
    @XmlEnumValue("Egyptian demotic")
    EGYPTIAN_DEMOTIC("Egyptian demotic"),
    @XmlEnumValue("Egyptian hieratic")
    EGYPTIAN_HIERATIC("Egyptian hieratic"),
    @XmlEnumValue("Egyptian hieroglyphs")
    EGYPTIAN_HIEROGLYPHS("Egyptian hieroglyphs"),
    @XmlEnumValue("Elbasan")
    ELBASAN("Elbasan"),
    @XmlEnumValue("Ethiopic; Ge\u02bbez; Ge'ez")
    ETHIOPIC_GE_ʻ_EZ_GE_EZ("Ethiopic; Ge\u02bbez; Ge'ez"),
    @XmlEnumValue("Khutsuri (Asomtavruli and Nuskhuri)")
    KHUTSURI_ASOMTAVRULI_AND_NUSKHURI("Khutsuri (Asomtavruli and Nuskhuri)"),
    @XmlEnumValue("Georgian (Mkhedruli)")
    GEORGIAN_MKHEDRULI("Georgian (Mkhedruli)"),
    @XmlEnumValue("Glagolitic")
    GLAGOLITIC("Glagolitic"),
    @XmlEnumValue("Gothic")
    GOTHIC("Gothic"),
    @XmlEnumValue("Grantha")
    GRANTHA("Grantha"),
    @XmlEnumValue("Greek")
    GREEK("Greek"),
    @XmlEnumValue("Gujarati")
    GUJARATI("Gujarati"),
    @XmlEnumValue("Gurmukhi")
    GURMUKHI("Gurmukhi"),
    @XmlEnumValue("Hangul; Hang\u016dl; Hangeul")
    HANGUL_HANGŬL_HANGEUL("Hangul; Hang\u016dl; Hangeul"),
    @XmlEnumValue("Han; Hanzi; Kanji; Hanja")
    HAN_HANZI_KANJI_HANJA("Han; Hanzi; Kanji; Hanja"),
    @XmlEnumValue("Hanunoo; Hanun\u00f3o")
    HANUNOO_HANUNÓO("Hanunoo; Hanun\u00f3o"),
    @XmlEnumValue("Han (Simplified variant)")
    HAN_SIMPLIFIED_VARIANT("Han (Simplified variant)"),
    @XmlEnumValue("Han (Traditional variant)")
    HAN_TRADITIONAL_VARIANT("Han (Traditional variant)"),
    @XmlEnumValue("Hatran")
    HATRAN("Hatran"),
    @XmlEnumValue("Hebrew")
    HEBREW("Hebrew"),
    @XmlEnumValue("Hiragana")
    HIRAGANA("Hiragana"),
    @XmlEnumValue("Anatolian Hieroglyphs; Luwian Hieroglyphs; Hittite Hieroglyphs")
    ANATOLIAN_HIEROGLYPHS_LUWIAN_HIEROGLYPHS_HITTITE_HIEROGLYPHS("Anatolian Hieroglyphs; Luwian Hieroglyphs; Hittite Hieroglyphs"),
    @XmlEnumValue("Pahawh Hmong")
    PAHAWH_HMONG("Pahawh Hmong"),
    @XmlEnumValue("Japanese syllabaries (alias for Hiragana + Katakana)")
    JAPANESE_SYLLABARIES_ALIAS_FOR_HIRAGANA_KATAKANA("Japanese syllabaries (alias for Hiragana + Katakana)"),
    @XmlEnumValue("Old Hungarian; Hungarian Runic")
    OLD_HUNGARIAN_HUNGARIAN_RUNIC("Old Hungarian; Hungarian Runic"),
    @XmlEnumValue("Indus; Harappan")
    INDUS_HARAPPAN("Indus; Harappan"),
    @XmlEnumValue("Old Italic (Etruscan, Oscan, etc.)")
    OLD_ITALIC_ETRUSCAN_OSCAN_ETC("Old Italic (Etruscan, Oscan, etc.)"),
    @XmlEnumValue("Javanese")
    JAVANESE("Javanese"),
    @XmlEnumValue("Japanese (alias for Han + Hiragana + Katakana)")
    JAPANESE_ALIAS_FOR_HAN_HIRAGANA_KATAKANA("Japanese (alias for Han + Hiragana + Katakana)"),
    @XmlEnumValue("Jurchen")
    JURCHEN("Jurchen"),
    @XmlEnumValue("Kayah Li")
    KAYAH_LI("Kayah Li"),
    @XmlEnumValue("Katakana")
    KATAKANA("Katakana"),
    @XmlEnumValue("Kharoshthi")
    KHAROSHTHI("Kharoshthi"),
    @XmlEnumValue("Khmer")
    KHMER("Khmer"),
    @XmlEnumValue("Khojki")
    KHOJKI("Khojki"),
    @XmlEnumValue("Kannada")
    KANNADA("Kannada"),
    @XmlEnumValue("Korean (alias for Hangul + Han)")
    KOREAN_ALIAS_FOR_HANGUL_HAN("Korean (alias for Hangul + Han)"),
    @XmlEnumValue("Kpelle")
    KPELLE("Kpelle"),
    @XmlEnumValue("Kaithi")
    KAITHI("Kaithi"),
    @XmlEnumValue("Tai Tham; Lanna")
    TAI_THAM_LANNA("Tai Tham; Lanna"),
    @XmlEnumValue("Lao")
    LAO("Lao"),
    @XmlEnumValue("Latin (Fraktur variant)")
    LATIN_FRAKTUR_VARIANT("Latin (Fraktur variant)"),
    @XmlEnumValue("Latin (Gaelic variant)")
    LATIN_GAELIC_VARIANT("Latin (Gaelic variant)"),
    @XmlEnumValue("Latin")
    LATIN("Latin"),
    @XmlEnumValue("Lepcha; R\u00f3ng")
    LEPCHA_RÓNG("Lepcha; R\u00f3ng"),
    @XmlEnumValue("Limbu")
    LIMBU("Limbu"),
    @XmlEnumValue("Linear A")
    LINEAR_A("Linear A"),
    @XmlEnumValue("Linear B")
    LINEAR_B("Linear B"),
    @XmlEnumValue("Lisu; Fraser")
    LISU_FRASER("Lisu; Fraser"),
    @XmlEnumValue("Loma")
    LOMA("Loma"),
    @XmlEnumValue("Lycian")
    LYCIAN("Lycian"),
    @XmlEnumValue("Lydian")
    LYDIAN("Lydian"),
    @XmlEnumValue("Mahajani")
    MAHAJANI("Mahajani"),
    @XmlEnumValue("Mandaic; Mandaean")
    MANDAIC_MANDAEAN("Mandaic; Mandaean"),
    @XmlEnumValue("Manichaean")
    MANICHAEAN("Manichaean"),
    @XmlEnumValue("Mayan hieroglyphs")
    MAYAN_HIEROGLYPHS("Mayan hieroglyphs"),
    @XmlEnumValue("Mende Kikakui")
    MENDE_KIKAKUI("Mende Kikakui"),
    @XmlEnumValue("Meroitic Cursive")
    MEROITIC_CURSIVE("Meroitic Cursive"),
    @XmlEnumValue("Meroitic Hieroglyphs")
    MEROITIC_HIEROGLYPHS("Meroitic Hieroglyphs"),
    @XmlEnumValue("Malayalam")
    MALAYALAM("Malayalam"),
    @XmlEnumValue("Modi; Mo\u1e0d\u012b")
    MODI_MOḌĪ("Modi; Mo\u1e0d\u012b"),
    @XmlEnumValue("Mongolian")
    MONGOLIAN("Mongolian"),
    @XmlEnumValue("Moon; Moon code; Moon script; Moon type")
    MOON_MOON_CODE_MOON_SCRIPT_MOON_TYPE("Moon; Moon code; Moon script; Moon type"),
    @XmlEnumValue("Mro; Mru")
    MRO_MRU("Mro; Mru"),
    @XmlEnumValue("Meitei Mayek; Meithei; Meetei")
    MEITEI_MAYEK_MEITHEI_MEETEI("Meitei Mayek; Meithei; Meetei"),
    @XmlEnumValue("Multani")
    MULTANI("Multani"),
    @XmlEnumValue("Myanmar; Burmese")
    MYANMAR_BURMESE("Myanmar; Burmese"),
    @XmlEnumValue("Old North Arabian; Ancient North Arabian")
    OLD_NORTH_ARABIAN_ANCIENT_NORTH_ARABIAN("Old North Arabian; Ancient North Arabian"),
    @XmlEnumValue("Nabataean")
    NABATAEAN("Nabataean"),
    @XmlEnumValue("Nakhi Geba; 'Na-'Khi \u00b2Gg\u014f-\u00b9baw; Naxi Geba")
    NAKHI_GEBA_NA_KHI_GGŎ_BAW_NAXI_GEBA("Nakhi Geba; 'Na-'Khi \u00b2Gg\u014f-\u00b9baw; Naxi Geba"),
    @XmlEnumValue("N\u2019Ko; N'Ko")
    N_KO_N_KO("N\u2019Ko; N'Ko"),
    @XmlEnumValue("N\u00fcshu")
    NÜSHU("N\u00fcshu"),
    @XmlEnumValue("Ogham")
    OGHAM("Ogham"),
    @XmlEnumValue("Ol Chiki; Ol Cemet'; Ol; Santali")
    OL_CHIKI_OL_CEMET_OL_SANTALI("Ol Chiki; Ol Cemet'; Ol; Santali"),
    @XmlEnumValue("Old Turkic; Orkhon Runic")
    OLD_TURKIC_ORKHON_RUNIC("Old Turkic; Orkhon Runic"),
    @XmlEnumValue("Oriya")
    ORIYA("Oriya"),
    @XmlEnumValue("Osmanya")
    OSMANYA("Osmanya"),
    @XmlEnumValue("Palmyrene")
    PALMYRENE("Palmyrene"),
    @XmlEnumValue("Pau Cin Hau")
    PAU_CIN_HAU("Pau Cin Hau"),
    @XmlEnumValue("Old Permic")
    OLD_PERMIC("Old Permic"),
    @XmlEnumValue("Phags-pa")
    PHAGS_PA("Phags-pa"),
    @XmlEnumValue("Inscriptional Pahlavi")
    INSCRIPTIONAL_PAHLAVI("Inscriptional Pahlavi"),
    @XmlEnumValue("Psalter Pahlavi")
    PSALTER_PAHLAVI("Psalter Pahlavi"),
    @XmlEnumValue("Book Pahlavi")
    BOOK_PAHLAVI("Book Pahlavi"),
    @XmlEnumValue("Phoenician")
    PHOENICIAN("Phoenician"),
    @XmlEnumValue("Miao; Pollard")
    MIAO_POLLARD("Miao; Pollard"),
    @XmlEnumValue("Inscriptional Parthian")
    INSCRIPTIONAL_PARTHIAN("Inscriptional Parthian"),
    @XmlEnumValue("Private use")
    PRIVATE_USE("Private use"),
    @XmlEnumValue("Rejang; Redjang; Kaganga")
    REJANG_REDJANG_KAGANGA("Rejang; Redjang; Kaganga"),
    @XmlEnumValue("Rongorongo")
    RONGORONGO("Rongorongo"),
    @XmlEnumValue("Runic")
    RUNIC("Runic"),
    @XmlEnumValue("Samaritan")
    SAMARITAN("Samaritan"),
    @XmlEnumValue("Sarati")
    SARATI("Sarati"),
    @XmlEnumValue("Old South Arabian")
    OLD_SOUTH_ARABIAN("Old South Arabian"),
    @XmlEnumValue("Saurashtra")
    SAURASHTRA("Saurashtra"),
    @XmlEnumValue("SignWriting")
    SIGN_WRITING("SignWriting"),
    @XmlEnumValue("Shavian; Shaw")
    SHAVIAN_SHAW("Shavian; Shaw"),
    @XmlEnumValue("Sharada; \u015a\u0101rad\u0101")
    SHARADA_ŚĀRADĀ("Sharada; \u015a\u0101rad\u0101"),
    @XmlEnumValue("Siddham; Siddha\u1e43; Siddham\u0101t\u1e5bk\u0101")
    SIDDHAM_SIDDHAṂ_SIDDHAMĀTṚKĀ("Siddham; Siddha\u1e43; Siddham\u0101t\u1e5bk\u0101"),
    @XmlEnumValue("Khudawadi; Sindhi")
    KHUDAWADI_SINDHI("Khudawadi; Sindhi"),
    @XmlEnumValue("Sinhala")
    SINHALA("Sinhala"),
    @XmlEnumValue("Sora Sompeng")
    SORA_SOMPENG("Sora Sompeng"),
    @XmlEnumValue("Sundanese")
    SUNDANESE("Sundanese"),
    @XmlEnumValue("Syloti Nagri")
    SYLOTI_NAGRI("Syloti Nagri"),
    @XmlEnumValue("Syriac")
    SYRIAC("Syriac"),
    @XmlEnumValue("Syriac (Estrangelo variant)")
    SYRIAC_ESTRANGELO_VARIANT("Syriac (Estrangelo variant)"),
    @XmlEnumValue("Syriac (Western variant)")
    SYRIAC_WESTERN_VARIANT("Syriac (Western variant)"),
    @XmlEnumValue("Syriac (Eastern variant)")
    SYRIAC_EASTERN_VARIANT("Syriac (Eastern variant)"),
    @XmlEnumValue("Tagbanwa")
    TAGBANWA("Tagbanwa"),
    @XmlEnumValue("Takri; \u1e6c\u0101kr\u012b; \u1e6c\u0101\u1e45kr\u012b")
    TAKRI_ṬĀKRĪ_ṬĀṄKRĪ("Takri; \u1e6c\u0101kr\u012b; \u1e6c\u0101\u1e45kr\u012b"),
    @XmlEnumValue("Tai Le")
    TAI_LE("Tai Le"),
    @XmlEnumValue("New Tai Lue")
    NEW_TAI_LUE("New Tai Lue"),
    @XmlEnumValue("Tamil")
    TAMIL("Tamil"),
    @XmlEnumValue("Tangut")
    TANGUT("Tangut"),
    @XmlEnumValue("Tai Viet")
    TAI_VIET("Tai Viet"),
    @XmlEnumValue("Telugu")
    TELUGU("Telugu"),
    @XmlEnumValue("Tengwar")
    TENGWAR("Tengwar"),
    @XmlEnumValue("Tifinagh; Berber")
    TIFINAGH_BERBER("Tifinagh; Berber"),
    @XmlEnumValue("Tagalog; Baybayin; Alibata")
    TAGALOG_BAYBAYIN_ALIBATA("Tagalog; Baybayin; Alibata"),
    @XmlEnumValue("Thaana")
    THAANA("Thaana"),
    @XmlEnumValue("Thai")
    THAI("Thai"),
    @XmlEnumValue("Tibetan")
    TIBETAN("Tibetan"),
    @XmlEnumValue("Tirhuta")
    TIRHUTA("Tirhuta"),
    @XmlEnumValue("Ugaritic")
    UGARITIC("Ugaritic"),
    @XmlEnumValue("Vai")
    VAI("Vai"),
    @XmlEnumValue("Visible Speech")
    VISIBLE_SPEECH("Visible Speech"),
    @XmlEnumValue("Warang Citi; Varang Kshiti")
    WARANG_CITI_VARANG_KSHITI("Warang Citi; Varang Kshiti"),
    @XmlEnumValue("Woleai")
    WOLEAI("Woleai"),
    @XmlEnumValue("Old Persian")
    OLD_PERSIAN("Old Persian"),
    @XmlEnumValue("Sumero-Akkadian cuneiform")
    SUMERO_AKKADIAN_CUNEIFORM("Sumero-Akkadian cuneiform"),
    @XmlEnumValue("Yi")
    YI("Yi"),
    @XmlEnumValue("Code for inherited script")
    CODE_FOR_INHERITED_SCRIPT("Code for inherited script"),
    @XmlEnumValue("Mathematical notation")
    MATHEMATICAL_NOTATION("Mathematical notation"),
    @XmlEnumValue("Symbols")
    SYMBOLS("Symbols"),
    @XmlEnumValue("Code for unwritten documents")
    CODE_FOR_UNWRITTEN_DOCUMENTS("Code for unwritten documents"),
    @XmlEnumValue("Code for undetermined script")
    CODE_FOR_UNDETERMINED_SCRIPT("Code for undetermined script"),
    @XmlEnumValue("Code for uncoded script")
    CODE_FOR_UNCODED_SCRIPT("Code for uncoded script");
    private final String value;

    LanguageScriptNameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LanguageScriptNameType fromValue(String v) {
        for (LanguageScriptNameType c: LanguageScriptNameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
