//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups together information on the contents of the LanguageDescriptions
 * 
 * <p>Java class for languageDescriptionEncodingInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="languageDescriptionEncodingInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="encodingLevel" maxOccurs="unbounded">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="phonetics"/>
 *               &lt;enumeration value="phonology"/>
 *               &lt;enumeration value="semantics"/>
 *               &lt;enumeration value="morphology"/>
 *               &lt;enumeration value="syntax"/>
 *               &lt;enumeration value="pragmatics"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}conformanceToStandardsBestPractices" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="theoreticModel" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="500"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="formalism" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="task" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="anaphoraResolution"/>
 *               &lt;enumeration value="chunking"/>
 *               &lt;enumeration value="parsing"/>
 *               &lt;enumeration value="npRecognition"/>
 *               &lt;enumeration value="titlesParsing"/>
 *               &lt;enumeration value="definitionsParsing"/>
 *               &lt;enumeration value="analysis"/>
 *               &lt;enumeration value="generation"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "languageDescriptionEncodingInfoType", propOrder = {
    "encodingLevel",
    "conformanceToStandardsBestPractices",
    "theoreticModel",
    "formalism",
    "task"
})
public class LanguageDescriptionEncodingInfoType {

    @XmlElement(required = true)
    protected List<String> encodingLevel;
    protected List<String> conformanceToStandardsBestPractices;
    protected List<String> theoreticModel;
    protected String formalism;
    protected List<String> task;

    /**
     * Gets the value of the encodingLevel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the encodingLevel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEncodingLevel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getEncodingLevel() {
        if (encodingLevel == null) {
            encodingLevel = new ArrayList<String>();
        }
        return this.encodingLevel;
    }

    /**
     * Specifies the standards or the best practices to which the tagset used for the annotation conforms Gets the value of the conformanceToStandardsBestPractices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the conformanceToStandardsBestPractices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConformanceToStandardsBestPractices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getConformanceToStandardsBestPractices() {
        if (conformanceToStandardsBestPractices == null) {
            conformanceToStandardsBestPractices = new ArrayList<String>();
        }
        return this.conformanceToStandardsBestPractices;
    }

    /**
     * Gets the value of the theoreticModel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the theoreticModel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTheoreticModel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTheoreticModel() {
        if (theoreticModel == null) {
            theoreticModel = new ArrayList<String>();
        }
        return this.theoreticModel;
    }

    /**
     * Gets the value of the formalism property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormalism() {
        return formalism;
    }

    /**
     * Sets the value of the formalism property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormalism(String value) {
        this.formalism = value;
    }

    /**
     * Gets the value of the task property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the task property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTask().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTask() {
        if (task == null) {
            task = new ArrayList<String>();
        }
        return this.task;
    }

}
