//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.16 at 02:19:04 PM EET 
//


package gr.ilsp.metashare;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups information on the languages represented in the resource 
 * 
 * <p>Java class for languageInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="languageInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}languageName"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}languageScript" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}region" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}variants" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}languageId"/>
 *         &lt;element name="sizePerLanguage" type="{http://www.ilsp.gr/META-XMLSchema}sizeInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}languageVarietyInfo" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "languageInfoType", propOrder = {
    "languageName",
    "languageScript",
    "region",
    "variants",
    "languageId",
    "sizePerLanguage",
    "languageVarietyInfo"
})
public class LanguageInfoType {

    @XmlElement(required = true)
    protected String languageName;
    protected String languageScript;
    protected String region;
    protected List<String> variants;
    @XmlElement(required = true)
    protected String languageId;
    protected List<SizeInfoType> sizePerLanguage;
    protected List<LanguageVarietyInfoType> languageVarietyInfo;

    /**
     * A human understandable name of the language that is used in the resource; the name is selected according to the IETF BCP47 specifications
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageName() {
        return languageName;
    }

    /**
     * Sets the value of the languageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageName(String value) {
        this.languageName = value;
    }

    /**
     * A human understandable name of the script used for the resource, according to the IETF BCP47 specifications; the element is optional and should only be used for extraordinary cases (e.g. transcribed text in IPA etc.)
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageScript() {
        return languageScript;
    }

    /**
     * Sets the value of the languageScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageScript(String value) {
        this.languageScript = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the variants property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the variants property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVariants().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getVariants() {
        if (variants == null) {
            variants = new ArrayList<String>();
        }
        return this.variants;
    }

    /**
     * The identifier of the language that is included in the resource or supported by the tool/service, according to the IETF BCP47 specifications
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguageId() {
        return languageId;
    }

    /**
     * Sets the value of the languageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguageId(String value) {
        this.languageId = value;
    }

    /**
     * Gets the value of the sizePerLanguage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sizePerLanguage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSizePerLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SizeInfoType }
     * 
     * 
     */
    public List<SizeInfoType> getSizePerLanguage() {
        if (sizePerLanguage == null) {
            sizePerLanguage = new ArrayList<SizeInfoType>();
        }
        return this.sizePerLanguage;
    }

    /**
     * Groups information on language varieties occurred in the resource (e.g. dialects) Gets the value of the languageVarietyInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languageVarietyInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguageVarietyInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LanguageVarietyInfoType }
     * 
     * 
     */
    public List<LanguageVarietyInfoType> getLanguageVarietyInfo() {
        if (languageVarietyInfo == null) {
            languageVarietyInfo = new ArrayList<LanguageVarietyInfoType>();
        }
        return this.languageVarietyInfo;
    }

}
