//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups together information specific to lexical/conceptual resources
 * 
 * <p>Java class for lexicalConceptualResourceInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lexicalConceptualResourceInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resourceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lexicalConceptualResourceType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="wordList"/>
 *               &lt;enumeration value="computationalLexicon"/>
 *               &lt;enumeration value="ontology"/>
 *               &lt;enumeration value="wordnet"/>
 *               &lt;enumeration value="thesaurus"/>
 *               &lt;enumeration value="framenet"/>
 *               &lt;enumeration value="terminologicalResource"/>
 *               &lt;enumeration value="machineReadableDictionary"/>
 *               &lt;enumeration value="lexicon"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}lexicalConceptualResourceEncodingInfo" minOccurs="0"/>
 *         &lt;element name="lexicalConceptualResourceMediaType">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}lexicalConceptualResourceTextInfo" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lexicalConceptualResourceInfoType", propOrder = {
    "resourceType",
    "lexicalConceptualResourceType",
    "lexicalConceptualResourceEncodingInfo",
    "lexicalConceptualResourceMediaType"
})
public class LexicalConceptualResourceInfoType {

    @XmlElement(required = true)
    protected String resourceType;
    @XmlElement(required = true)
    protected String lexicalConceptualResourceType;
    protected LexicalConceptualResourceEncodingInfoType lexicalConceptualResourceEncodingInfo;
    @XmlElement(required = true)
    protected LexicalConceptualResourceInfoType.LexicalConceptualResourceMediaType lexicalConceptualResourceMediaType;

    /**
     * Gets the value of the resourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * Sets the value of the resourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourceType(String value) {
        this.resourceType = value;
    }

    /**
     * Gets the value of the lexicalConceptualResourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLexicalConceptualResourceType() {
        return lexicalConceptualResourceType;
    }

    /**
     * Sets the value of the lexicalConceptualResourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLexicalConceptualResourceType(String value) {
        this.lexicalConceptualResourceType = value;
    }

    /**
     * Groups all information regarding the contents of lexical/conceptual resources
     * 
     * @return
     *     possible object is
     *     {@link LexicalConceptualResourceEncodingInfoType }
     *     
     */
    public LexicalConceptualResourceEncodingInfoType getLexicalConceptualResourceEncodingInfo() {
        return lexicalConceptualResourceEncodingInfo;
    }

    /**
     * Sets the value of the lexicalConceptualResourceEncodingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LexicalConceptualResourceEncodingInfoType }
     *     
     */
    public void setLexicalConceptualResourceEncodingInfo(LexicalConceptualResourceEncodingInfoType value) {
        this.lexicalConceptualResourceEncodingInfo = value;
    }

    /**
     * Gets the value of the lexicalConceptualResourceMediaType property.
     * 
     * @return
     *     possible object is
     *     {@link LexicalConceptualResourceInfoType.LexicalConceptualResourceMediaType }
     *     
     */
    public LexicalConceptualResourceInfoType.LexicalConceptualResourceMediaType getLexicalConceptualResourceMediaType() {
        return lexicalConceptualResourceMediaType;
    }

    /**
     * Sets the value of the lexicalConceptualResourceMediaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link LexicalConceptualResourceInfoType.LexicalConceptualResourceMediaType }
     *     
     */
    public void setLexicalConceptualResourceMediaType(LexicalConceptualResourceInfoType.LexicalConceptualResourceMediaType value) {
        this.lexicalConceptualResourceMediaType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}lexicalConceptualResourceTextInfo" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lexicalConceptualResourceTextInfo"
    })
    public static class LexicalConceptualResourceMediaType {

        protected LexicalConceptualResourceTextInfo lexicalConceptualResourceTextInfo;

        /**
         * Groups information on the textual part of the lexical/conceptual resource
         * 
         * @return
         *     possible object is
         *     {@link LexicalConceptualResourceTextInfo }
         *     
         */
        public LexicalConceptualResourceTextInfo getLexicalConceptualResourceTextInfo() {
            return lexicalConceptualResourceTextInfo;
        }

        /**
         * Sets the value of the lexicalConceptualResourceTextInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link LexicalConceptualResourceTextInfo }
         *     
         */
        public void setLexicalConceptualResourceTextInfo(LexicalConceptualResourceTextInfo value) {
            this.lexicalConceptualResourceTextInfo = value;
        }

    }

}
