//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups information on licences for the resource; can be repeated to allow for different modes of access and restrictions of use (e.g. free for academic use, on-a-fee basis for commercial use, download of a sample for free use etc.)
 * 
 * <p>Java class for licenceInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="licenceInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="licence">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *               &lt;enumeration value="CC-BY"/>
 *               &lt;enumeration value="CC-BY-NC"/>
 *               &lt;enumeration value="CC-BY-NC-ND"/>
 *               &lt;enumeration value="CC-BY-NC-SA"/>
 *               &lt;enumeration value="CC-BY-ND"/>
 *               &lt;enumeration value="CC-BY-SA"/>
 *               &lt;enumeration value="CC-ZERO"/>
 *               &lt;enumeration value="PDDL"/>
 *               &lt;enumeration value="ODC-BY"/>
 *               &lt;enumeration value="ODbL"/>
 *               &lt;enumeration value="openForReuseWithRestrictions"/>
 *               &lt;enumeration value="FreeOpenDataLicence_Belgium"/>
 *               &lt;enumeration value="OpenDataLicenceAtAFairCost_Belgium"/>
 *               &lt;enumeration value="FreeOpenDataLicenceForNon-CommercialRe-use_Belgium"/>
 *               &lt;enumeration value="OpenDataLicenceAtAFairCostForCommercialRe-use_Belgium"/>
 *               &lt;enumeration value="NLSOpenDataLicence_Finland"/>
 *               &lt;enumeration value="LicenceOuverte-OpenLicence_France"/>
 *               &lt;enumeration value="DL-DE-BY_Germany"/>
 *               &lt;enumeration value="DL-DE-ZERO_Germany"/>
 *               &lt;enumeration value="PSI-licence_Ireland"/>
 *               &lt;enumeration value="IODL_Italy"/>
 *               &lt;enumeration value="NLOD_Norway"/>
 *               &lt;enumeration value="OGL_UK"/>
 *               &lt;enumeration value="NCGL_UK"/>
 *               &lt;enumeration value="non-standard/Other_Licence/Terms"/>
 *               &lt;enumeration value="underNegotiation"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="otherLicenceName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="otherLicence_TermsText" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;restriction base="&lt;http://www.ilsp.gr/META-XMLSchema>myString">
 *               &lt;/restriction>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="otherLicence_TermsURL" type="{http://www.ilsp.gr/META-XMLSchema}httpURI" minOccurs="0"/>
 *         &lt;element name="personalDataIncluded" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="personalDataAdditionalInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sensitiveDataIncluded" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="sensitiveDataAdditionalInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="restrictionsOfUse" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *               &lt;enumeration value="nonCommercialUse"/>
 *               &lt;enumeration value="commercialUse"/>
 *               &lt;enumeration value="attribution"/>
 *               &lt;enumeration value="shareAlike"/>
 *               &lt;enumeration value="noDerivatives"/>
 *               &lt;enumeration value="research"/>
 *               &lt;enumeration value="education"/>
 *               &lt;enumeration value="compensate"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="fee" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="attributionText" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;restriction base="&lt;http://www.ilsp.gr/META-XMLSchema>myString">
 *               &lt;/restriction>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "licenceInfoType", propOrder = {
    "licence",
    "otherLicenceName",
    "otherLicenceTermsText",
    "otherLicenceTermsURL",
//    "personalDataIncluded",
//    "personalDataAdditionalInfo",
//    "sensitiveDataIncluded",
//    "sensitiveDataAdditionalInfo",
    "restrictionsOfUse",
    "fee",
    "attributionText"
})
@XmlSeeAlso({
    LicenceInfo.class
})
public class LicenceInfoType {

    @XmlElement(required = true)
    protected String licence;
    protected String otherLicenceName;
    @XmlElement(name = "otherLicence_TermsText")
    protected List<LicenceInfoType.OtherLicenceTermsText> otherLicenceTermsText;
    @XmlElement(name = "otherLicence_TermsURL")
    @XmlSchemaType(name = "anyURI")
    protected String otherLicenceTermsURL;
//    protected boolean personalDataIncluded;
//    protected String personalDataAdditionalInfo;
//    protected boolean sensitiveDataIncluded;
//    protected String sensitiveDataAdditionalInfo;
    protected List<String> restrictionsOfUse;
    protected String fee;
    protected List<LicenceInfoType.AttributionText> attributionText;

    /**
     * Gets the value of the licence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicence() {
        return licence;
    }

    /**
     * Sets the value of the licence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicence(String value) {
        this.licence = value;
    }

    /**
     * Gets the value of the otherLicenceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherLicenceName() {
        return otherLicenceName;
    }

    /**
     * Sets the value of the otherLicenceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherLicenceName(String value) {
        this.otherLicenceName = value;
    }

    /**
     * Gets the value of the otherLicenceTermsText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherLicenceTermsText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherLicenceTermsText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LicenceInfoType.OtherLicenceTermsText }
     * 
     * 
     */
    public List<LicenceInfoType.OtherLicenceTermsText> getOtherLicenceTermsText() {
        if (otherLicenceTermsText == null) {
            otherLicenceTermsText = new ArrayList<LicenceInfoType.OtherLicenceTermsText>();
        }
        return this.otherLicenceTermsText;
    }

    /**
     * Gets the value of the otherLicenceTermsURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherLicenceTermsURL() {
        return otherLicenceTermsURL;
    }

    /**
     * Sets the value of the otherLicenceTermsURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherLicenceTermsURL(String value) {
        this.otherLicenceTermsURL = value;
    }

//    /**
//     * Gets the value of the personalDataIncluded property.
//     * 
//     */
//    public boolean isPersonalDataIncluded() {
//        return personalDataIncluded;
//    }
//
//    /**
//     * Sets the value of the personalDataIncluded property.
//     * 
//     */
//    public void setPersonalDataIncluded(boolean value) {
//        this.personalDataIncluded = value;
//    }
//
//    /**
//     * Gets the value of the personalDataAdditionalInfo property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link String }
//     *     
//     */
//    public String getPersonalDataAdditionalInfo() {
//        return personalDataAdditionalInfo;
//    }
//
//    /**
//     * Sets the value of the personalDataAdditionalInfo property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *     
//     */
//    public void setPersonalDataAdditionalInfo(String value) {
//        this.personalDataAdditionalInfo = value;
//    }
//
//    /**
//     * Gets the value of the sensitiveDataIncluded property.
//     * 
//     */
//    public boolean isSensitiveDataIncluded() {
//        return sensitiveDataIncluded;
//    }
//
//    /**
//     * Sets the value of the sensitiveDataIncluded property.
//     * 
//     */
//    public void setSensitiveDataIncluded(boolean value) {
//        this.sensitiveDataIncluded = value;
//    }

//    /**
//     * Gets the value of the sensitiveDataAdditionalInfo property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link String }
//     *     
//     */
//    public String getSensitiveDataAdditionalInfo() {
//        return sensitiveDataAdditionalInfo;
//    }
//
//    /**
//     * Sets the value of the sensitiveDataAdditionalInfo property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *     
//     */
//    public void setSensitiveDataAdditionalInfo(String value) {
//        this.sensitiveDataAdditionalInfo = value;
//    }

    /**
     * Gets the value of the restrictionsOfUse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the restrictionsOfUse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRestrictionsOfUse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRestrictionsOfUse() {
        if (restrictionsOfUse == null) {
            restrictionsOfUse = new ArrayList<String>();
        }
        return this.restrictionsOfUse;
    }

    /**
     * Gets the value of the fee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFee() {
        return fee;
    }

    /**
     * Sets the value of the fee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFee(String value) {
        this.fee = value;
    }

    /**
     * Gets the value of the attributionText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributionText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributionText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LicenceInfoType.AttributionText }
     * 
     * 
     */
    public List<LicenceInfoType.AttributionText> getAttributionText() {
        if (attributionText == null) {
            attributionText = new ArrayList<LicenceInfoType.AttributionText>();
        }
        return this.attributionText;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;restriction base="&lt;http://www.ilsp.gr/META-XMLSchema>myString">
     *     &lt;/restriction>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AttributionText
        extends MyString
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;restriction base="&lt;http://www.ilsp.gr/META-XMLSchema>myString">
     *     &lt;/restriction>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class OtherLicenceTermsText
        extends MyString
    {


    }

}
