//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups information on the way different media of the resource interact with or link to each other. To be used for multimodal resources or for resources representing sensorimotor data
 * 
 * <p>Java class for linkToOtherMediaInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="linkToOtherMediaInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="otherMedia">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="text"/>
 *               &lt;enumeration value="textNumerical"/>
 *               &lt;enumeration value="video"/>
 *               &lt;enumeration value="audio"/>
 *               &lt;enumeration value="image"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="mediaTypeDetails" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="500"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="synchronizedWithText" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="synchronizedWithAudio" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="synchronizedWithVideo" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="synchronizedWithImage" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="synchronizedWithTextNumerical" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "linkToOtherMediaInfoType", propOrder = {
    "otherMedia",
    "mediaTypeDetails",
    "synchronizedWithText",
    "synchronizedWithAudio",
    "synchronizedWithVideo",
    "synchronizedWithImage",
    "synchronizedWithTextNumerical"
})
public class LinkToOtherMediaInfoType {

    @XmlElement(required = true)
    protected String otherMedia;
    protected String mediaTypeDetails;
    protected Boolean synchronizedWithText;
    protected Boolean synchronizedWithAudio;
    protected Boolean synchronizedWithVideo;
    protected Boolean synchronizedWithImage;
    protected Boolean synchronizedWithTextNumerical;

    /**
     * Gets the value of the otherMedia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherMedia() {
        return otherMedia;
    }

    /**
     * Sets the value of the otherMedia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherMedia(String value) {
        this.otherMedia = value;
    }

    /**
     * Gets the value of the mediaTypeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaTypeDetails() {
        return mediaTypeDetails;
    }

    /**
     * Sets the value of the mediaTypeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaTypeDetails(String value) {
        this.mediaTypeDetails = value;
    }

    /**
     * Gets the value of the synchronizedWithText property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSynchronizedWithText() {
        return synchronizedWithText;
    }

    /**
     * Sets the value of the synchronizedWithText property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSynchronizedWithText(Boolean value) {
        this.synchronizedWithText = value;
    }

    /**
     * Gets the value of the synchronizedWithAudio property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSynchronizedWithAudio() {
        return synchronizedWithAudio;
    }

    /**
     * Sets the value of the synchronizedWithAudio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSynchronizedWithAudio(Boolean value) {
        this.synchronizedWithAudio = value;
    }

    /**
     * Gets the value of the synchronizedWithVideo property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSynchronizedWithVideo() {
        return synchronizedWithVideo;
    }

    /**
     * Sets the value of the synchronizedWithVideo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSynchronizedWithVideo(Boolean value) {
        this.synchronizedWithVideo = value;
    }

    /**
     * Gets the value of the synchronizedWithImage property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSynchronizedWithImage() {
        return synchronizedWithImage;
    }

    /**
     * Sets the value of the synchronizedWithImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSynchronizedWithImage(Boolean value) {
        this.synchronizedWithImage = value;
    }

    /**
     * Gets the value of the synchronizedWithTextNumerical property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSynchronizedWithTextNumerical() {
        return synchronizedWithTextNumerical;
    }

    /**
     * Sets the value of the synchronizedWithTextNumerical property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSynchronizedWithTextNumerical(Boolean value) {
        this.synchronizedWithTextNumerical = value;
    }

}
