//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.20 at 01:34:11 PM EET 
//


package gr.ilsp.metashare;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Groups information on the metadata record itself
 * 
 * <p>Java class for metadataInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="metadataInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="metadataCreationDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="metadataCreator" type="{http://www.ilsp.gr/META-XMLSchema}personInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="metadataLanguageName" type="{http://www.ilsp.gr/META-XMLSchema}languageNameType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="metadataLanguageId" type="{http://www.ilsp.gr/META-XMLSchema}languageTagType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="metadataLastDateUpdated" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "metadataInfoType", propOrder = {
    "metadataCreationDate",
    "metadataCreator",
    "metadataLanguageName",
    "metadataLanguageId",
    "metadataLastDateUpdated"
})
public class MetadataInfoType {

    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar metadataCreationDate;
    protected List<PersonInfoType> metadataCreator;
    protected List<String> metadataLanguageName;
    protected List<String> metadataLanguageId;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar metadataLastDateUpdated;

    /**
     * Gets the value of the metadataCreationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMetadataCreationDate() {
        return metadataCreationDate;
    }

    /**
     * Sets the value of the metadataCreationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMetadataCreationDate(XMLGregorianCalendar value) {
        this.metadataCreationDate = value;
    }

    /**
     * Gets the value of the metadataCreator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadataCreator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadataCreator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonInfoType }
     * 
     * 
     */
    public List<PersonInfoType> getMetadataCreator() {
        if (metadataCreator == null) {
            metadataCreator = new ArrayList<PersonInfoType>();
        }
        return this.metadataCreator;
    }

    /**
     * Gets the value of the metadataLanguageName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadataLanguageName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadataLanguageName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMetadataLanguageName() {
        if (metadataLanguageName == null) {
            metadataLanguageName = new ArrayList<String>();
        }
        return this.metadataLanguageName;
    }

    /**
     * Gets the value of the metadataLanguageId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadataLanguageId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadataLanguageId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMetadataLanguageId() {
        if (metadataLanguageId == null) {
            metadataLanguageId = new ArrayList<String>();
        }
        return this.metadataLanguageId;
    }

    /**
     * Gets the value of the metadataLastDateUpdated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMetadataLastDateUpdated() {
        return metadataLastDateUpdated;
    }

    /**
     * Sets the value of the metadataLastDateUpdated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMetadataLastDateUpdated(XMLGregorianCalendar value) {
        this.metadataLastDateUpdated = value;
    }

}
