//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for myString complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="myString">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="lang" type="{http://www.w3.org/2001/XMLSchema}language" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "myString", propOrder = {
    "value"
})
@XmlSeeAlso({
    gr.ilsp.metashare.IdentificationInfoType.ResourceName.class,
    gr.ilsp.metashare.IdentificationInfoType.Description.class,
    gr.ilsp.metashare.IdentificationInfoType.ResourceShortName.class,
    gr.ilsp.metashare.LicenceInfoType.OtherLicenceTermsText.class,
    gr.ilsp.metashare.LicenceInfoType.AttributionText.class,
    gr.ilsp.metashare.ProjectInfoType.ProjectName.class,
    gr.ilsp.metashare.ProjectInfoType.ProjectShortName.class,
    gr.ilsp.metashare.DocumentInfoType.Title.class,
    gr.ilsp.metashare.PersonInfoType.Surname.class,
    gr.ilsp.metashare.PersonInfoType.GivenName.class,
    gr.ilsp.metashare.OrganizationInfoType.OrganizationName.class,
    gr.ilsp.metashare.OrganizationInfoType.OrganizationShortName.class,
    gr.ilsp.metashare.ParticipantInfoType.Alias.class,
    gr.ilsp.metashare.ParticipantInfoType.DialectAccent.class
})
public class MyString {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "lang")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String lang;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
