//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gr.ilsp.metashare package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AnnotationFormat_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "annotationFormat");
    private final static QName _CharacterEncodingInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "characterEncodingInfo");
    private final static QName _LanguageVarietyName_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "languageVarietyName");
    private final static QName _Tagset_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "tagset");
    private final static QName _UsageInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "usageInfo");
    private final static QName _CompressionInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "compressionInfo");
    private final static QName _DocumentList_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "documentList");
    private final static QName _OrganizationInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "organizationInfo");
    private final static QName _LanguageId_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "languageId");
    private final static QName _LanguageInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "languageInfo");
    private final static QName _LanguageDescriptionOperationInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "languageDescriptionOperationInfo");
    private final static QName _TextFormatInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "textFormatInfo");
    private final static QName _PersonList_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "personList");
    private final static QName _ConformanceToClassificationScheme_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "conformanceToClassificationScheme");
    private final static QName _AnnotationInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "annotationInfo");
    private final static QName _LanguageDescriptionPerformanceInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "languageDescriptionPerformanceInfo");
    private final static QName _UseNLPSpecific_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "useNLPSpecific");
    private final static QName _SegmentationLevel_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "segmentationLevel");
    private final static QName _RunningEnvironmentInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "runningEnvironmentInfo");
    private final static QName _LexicalConceptualResourceInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "lexicalConceptualResourceInfo");
    private final static QName _ConformanceToStandardsBestPractices_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "conformanceToStandardsBestPractices");
    private final static QName _TextClassificationInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "textClassificationInfo");
    private final static QName _CorpusTextNgramInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "corpusTextNgramInfo");
    private final static QName _ResourceDocumentationInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "resourceDocumentationInfo");
    private final static QName _PersonInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "personInfo");
    private final static QName _LanguageName_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "languageName");
    private final static QName _ResourceInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "resourceInfo");
    private final static QName _MetadataInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "metadataInfo");
    private final static QName _ForeseenUseInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "foreseenUseInfo");
    private final static QName _DocumentInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "documentInfo");
    private final static QName _DomainInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "domainInfo");
    private final static QName _ResourceCreationInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "resourceCreationInfo");
    private final static QName _SizeInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "sizeInfo");
    private final static QName _ModalityInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "modalityInfo");
    private final static QName _ResolutionInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "resolutionInfo");
    private final static QName _CharacterEncoding_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "characterEncoding");
    private final static QName _Region_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "region");
    private final static QName _ActualUseInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "actualUseInfo");
    private final static QName _DocumentationInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "documentationInfo");
    private final static QName _LinkToOtherMediaInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "linkToOtherMediaInfo");
    private final static QName _LanguageDescriptionEncodingInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "languageDescriptionEncodingInfo");
    private final static QName _Domain_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "domain");
    private final static QName _AnnotationType_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "annotationType");
    private final static QName _VersionInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "versionInfo");
    private final static QName _MediaType_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "mediaType");
    private final static QName _TextType_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "textType");
    private final static QName _SettingInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "settingInfo");
    private final static QName _DomainId_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "domainId");
    private final static QName _CreationInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "creationInfo");
    private final static QName _ModalityType_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "modalityType");
    private final static QName _DocumentUnstructured_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "documentUnstructured");
    private final static QName _NgramInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "ngramInfo");
    private final static QName _CaptureInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "captureInfo");
    private final static QName _RecordingInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "recordingInfo");
    private final static QName _CorpusInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "corpusInfo");
    private final static QName _TextGenre_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "textGenre");
    private final static QName _LexicalConceptualResourceEncodingInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "lexicalConceptualResourceEncodingInfo");
    private final static QName _LanguageDescriptionInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "languageDescriptionInfo");
    private final static QName _RelationInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "relationInfo");
    private final static QName _LanguageVarietyInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "languageVarietyInfo");
    private final static QName _CommunicationInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "communicationInfo");
    private final static QName _TimeCoverageInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "timeCoverageInfo");
    private final static QName _ProjectInfoList_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "projectInfoList");
    private final static QName _ProjectInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "projectInfo");
    private final static QName _GeographicCoverageInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "geographicCoverageInfo");
    private final static QName _OrganizationList_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "organizationList");
    private final static QName _ValidationInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "validationInfo");
    private final static QName _MimeType_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "mimeType");
    private final static QName _Variants_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "variants");
    private final static QName _IdentificationInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "identificationInfo");
    private final static QName _PersonSourceSetInfo_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "personSourceSetInfo");
    private final static QName _LanguageScript_QNAME = new QName("http://www.ilsp.gr/META-XMLSchema", "languageScript");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gr.ilsp.metashare
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LicenceInfoType }
     * 
     */
    public LicenceInfoType createLicenceInfoType() {
        return new LicenceInfoType();
    }

    /**
     * Create an instance of {@link ParticipantInfoType }
     * 
     */
    public ParticipantInfoType createParticipantInfoType() {
        return new ParticipantInfoType();
    }

    /**
     * Create an instance of {@link OrganizationInfoType }
     * 
     */
    public OrganizationInfoType createOrganizationInfoType() {
        return new OrganizationInfoType();
    }

    /**
     * Create an instance of {@link LexicalConceptualResourceInfoType }
     * 
     */
    public LexicalConceptualResourceInfoType createLexicalConceptualResourceInfoType() {
        return new LexicalConceptualResourceInfoType();
    }

    /**
     * Create an instance of {@link ResourceInfoType }
     * 
     */
    public ResourceInfoType createResourceInfoType() {
        return new ResourceInfoType();
    }

    /**
     * Create an instance of {@link PersonInfoType }
     * 
     */
    public PersonInfoType createPersonInfoType() {
        return new PersonInfoType();
    }

    /**
     * Create an instance of {@link DocumentInfoType }
     * 
     */
    public DocumentInfoType createDocumentInfoType() {
        return new DocumentInfoType();
    }

    /**
     * Create an instance of {@link CorpusInfoType }
     * 
     */
    public CorpusInfoType createCorpusInfoType() {
        return new CorpusInfoType();
    }

    /**
     * Create an instance of {@link LanguageDescriptionInfoType }
     * 
     */
    public LanguageDescriptionInfoType createLanguageDescriptionInfoType() {
        return new LanguageDescriptionInfoType();
    }

    /**
     * Create an instance of {@link ProjectInfoType }
     * 
     */
    public ProjectInfoType createProjectInfoType() {
        return new ProjectInfoType();
    }

    /**
     * Create an instance of {@link IdentificationInfoType }
     * 
     */
    public IdentificationInfoType createIdentificationInfoType() {
        return new IdentificationInfoType();
    }

    /**
     * Create an instance of {@link PersonSourceSetInfoType }
     * 
     */
    public PersonSourceSetInfoType createPersonSourceSetInfoType() {
        return new PersonSourceSetInfoType();
    }

    /**
     * Create an instance of {@link OrganizationListType }
     * 
     */
    public OrganizationListType createOrganizationListType() {
        return new OrganizationListType();
    }

    /**
     * Create an instance of {@link ValidationInfoType }
     * 
     */
    public ValidationInfoType createValidationInfoType() {
        return new ValidationInfoType();
    }

    /**
     * Create an instance of {@link GeographicCoverageInfoType }
     * 
     */
    public GeographicCoverageInfoType createGeographicCoverageInfoType() {
        return new GeographicCoverageInfoType();
    }

    /**
     * Create an instance of {@link DistributionInfo }
     * 
     */
    public DistributionInfo createDistributionInfo() {
        return new DistributionInfo();
    }

    /**
     * Create an instance of {@link DistributionInfoType }
     * 
     */
    public DistributionInfoType createDistributionInfoType() {
        return new DistributionInfoType();
    }

    /**
     * Create an instance of {@link LicenceInfo }
     * 
     */
    public LicenceInfo createLicenceInfo() {
        return new LicenceInfo();
    }

    /**
     * Create an instance of {@link LicenceInfoType.OtherLicenceTermsText }
     * 
     */
    public LicenceInfoType.OtherLicenceTermsText createLicenceInfoTypeOtherLicenceTermsText() {
        return new LicenceInfoType.OtherLicenceTermsText();
    }

    /**
     * Create an instance of {@link LicenceInfoType.AttributionText }
     * 
     */
    public LicenceInfoType.AttributionText createLicenceInfoTypeAttributionText() {
        return new LicenceInfoType.AttributionText();
    }

    /**
     * Create an instance of {@link ActorInfoType }
     * 
     */
    public ActorInfoType createActorInfoType() {
        return new ActorInfoType();
    }

    /**
     * Create an instance of {@link CommunicationInfoType }
     * 
     */
    public CommunicationInfoType createCommunicationInfoType() {
        return new CommunicationInfoType();
    }

    /**
     * Create an instance of {@link TimeCoverageInfoType }
     * 
     */
    public TimeCoverageInfoType createTimeCoverageInfoType() {
        return new TimeCoverageInfoType();
    }

    /**
     * Create an instance of {@link ProjectListType }
     * 
     */
    public ProjectListType createProjectListType() {
        return new ProjectListType();
    }

    /**
     * Create an instance of {@link LexicalConceptualResourceEncodingInfoType }
     * 
     */
    public LexicalConceptualResourceEncodingInfoType createLexicalConceptualResourceEncodingInfoType() {
        return new LexicalConceptualResourceEncodingInfoType();
    }

    /**
     * Create an instance of {@link LanguageVarietyInfoType }
     * 
     */
    public LanguageVarietyInfoType createLanguageVarietyInfoType() {
        return new LanguageVarietyInfoType();
    }

    /**
     * Create an instance of {@link RelationInfoType }
     * 
     */
    public RelationInfoType createRelationInfoType() {
        return new RelationInfoType();
    }

    /**
     * Create an instance of {@link LanguageDescriptionTextInfo }
     * 
     */
    public LanguageDescriptionTextInfo createLanguageDescriptionTextInfo() {
        return new LanguageDescriptionTextInfo();
    }

    /**
     * Create an instance of {@link LanguageDescriptionTextInfoType }
     * 
     */
    public LanguageDescriptionTextInfoType createLanguageDescriptionTextInfoType() {
        return new LanguageDescriptionTextInfoType();
    }

    /**
     * Create an instance of {@link LingualityInfo }
     * 
     */
    public LingualityInfo createLingualityInfo() {
        return new LingualityInfo();
    }

    /**
     * Create an instance of {@link LingualityInfoType }
     * 
     */
    public LingualityInfoType createLingualityInfoType() {
        return new LingualityInfoType();
    }

    /**
     * Create an instance of {@link LanguageInfoType }
     * 
     */
    public LanguageInfoType createLanguageInfoType() {
        return new LanguageInfoType();
    }

    /**
     * Create an instance of {@link SizeInfoType }
     * 
     */
    public SizeInfoType createSizeInfoType() {
        return new SizeInfoType();
    }

    /**
     * Create an instance of {@link TextFormatInfoType }
     * 
     */
    public TextFormatInfoType createTextFormatInfoType() {
        return new TextFormatInfoType();
    }

    /**
     * Create an instance of {@link CharacterEncodingInfoType }
     * 
     */
    public CharacterEncodingInfoType createCharacterEncodingInfoType() {
        return new CharacterEncodingInfoType();
    }

    /**
     * Create an instance of {@link DomainInfoType }
     * 
     */
    public DomainInfoType createDomainInfoType() {
        return new DomainInfoType();
    }

    /**
     * Create an instance of {@link NgramInfoType }
     * 
     */
    public NgramInfoType createNgramInfoType() {
        return new NgramInfoType();
    }

    /**
     * Create an instance of {@link CaptureInfoType }
     * 
     */
    public CaptureInfoType createCaptureInfoType() {
        return new CaptureInfoType();
    }

    /**
     * Create an instance of {@link RecordingInfoType }
     * 
     */
    public RecordingInfoType createRecordingInfoType() {
        return new RecordingInfoType();
    }

    /**
     * Create an instance of {@link VersionInfoType }
     * 
     */
    public VersionInfoType createVersionInfoType() {
        return new VersionInfoType();
    }

    /**
     * Create an instance of {@link SettingInfoType }
     * 
     */
    public SettingInfoType createSettingInfoType() {
        return new SettingInfoType();
    }

    /**
     * Create an instance of {@link CreationInfoType }
     * 
     */
    public CreationInfoType createCreationInfoType() {
        return new CreationInfoType();
    }

    /**
     * Create an instance of {@link LexicalConceptualResourceTextInfo }
     * 
     */
    public LexicalConceptualResourceTextInfo createLexicalConceptualResourceTextInfo() {
        return new LexicalConceptualResourceTextInfo();
    }

    /**
     * Create an instance of {@link LexicalConceptualResourceTextInfoType }
     * 
     */
    public LexicalConceptualResourceTextInfoType createLexicalConceptualResourceTextInfoType() {
        return new LexicalConceptualResourceTextInfoType();
    }

    /**
     * Create an instance of {@link DocumentationInfoType }
     * 
     */
    public DocumentationInfoType createDocumentationInfoType() {
        return new DocumentationInfoType();
    }

    /**
     * Create an instance of {@link LinkToOtherMediaInfoType }
     * 
     */
    public LinkToOtherMediaInfoType createLinkToOtherMediaInfoType() {
        return new LinkToOtherMediaInfoType();
    }

    /**
     * Create an instance of {@link LanguageDescriptionEncodingInfoType }
     * 
     */
    public LanguageDescriptionEncodingInfoType createLanguageDescriptionEncodingInfoType() {
        return new LanguageDescriptionEncodingInfoType();
    }

    /**
     * Create an instance of {@link ModalityInfoType }
     * 
     */
    public ModalityInfoType createModalityInfoType() {
        return new ModalityInfoType();
    }

    /**
     * Create an instance of {@link ResolutionInfoType }
     * 
     */
    public ResolutionInfoType createResolutionInfoType() {
        return new ResolutionInfoType();
    }

    /**
     * Create an instance of {@link ActualUseInfoType }
     * 
     */
    public ActualUseInfoType createActualUseInfoType() {
        return new ActualUseInfoType();
    }

    /**
     * Create an instance of {@link ForeseenUseInfoType }
     * 
     */
    public ForeseenUseInfoType createForeseenUseInfoType() {
        return new ForeseenUseInfoType();
    }

    /**
     * Create an instance of {@link ResourceCreationInfoType }
     * 
     */
    public ResourceCreationInfoType createResourceCreationInfoType() {
        return new ResourceCreationInfoType();
    }

    /**
     * Create an instance of {@link ResourceDocumentationInfoType }
     * 
     */
    public ResourceDocumentationInfoType createResourceDocumentationInfoType() {
        return new ResourceDocumentationInfoType();
    }

    /**
     * Create an instance of {@link TextClassificationInfoType }
     * 
     */
    public TextClassificationInfoType createTextClassificationInfoType() {
        return new TextClassificationInfoType();
    }

    /**
     * Create an instance of {@link CorpusTextNgramInfoType }
     * 
     */
    public CorpusTextNgramInfoType createCorpusTextNgramInfoType() {
        return new CorpusTextNgramInfoType();
    }

    /**
     * Create an instance of {@link MetadataInfoType }
     * 
     */
    public MetadataInfoType createMetadataInfoType() {
        return new MetadataInfoType();
    }

    /**
     * Create an instance of {@link RunningEnvironmentInfoType }
     * 
     */
    public RunningEnvironmentInfoType createRunningEnvironmentInfoType() {
        return new RunningEnvironmentInfoType();
    }

    /**
     * Create an instance of {@link LanguageDescriptionPerformanceInfoType }
     * 
     */
    public LanguageDescriptionPerformanceInfoType createLanguageDescriptionPerformanceInfoType() {
        return new LanguageDescriptionPerformanceInfoType();
    }

    /**
     * Create an instance of {@link LanguageDescriptionOperationInfoType }
     * 
     */
    public LanguageDescriptionOperationInfoType createLanguageDescriptionOperationInfoType() {
        return new LanguageDescriptionOperationInfoType();
    }

    /**
     * Create an instance of {@link PersonListType }
     * 
     */
    public PersonListType createPersonListType() {
        return new PersonListType();
    }

    /**
     * Create an instance of {@link AnnotationInfoType }
     * 
     */
    public AnnotationInfoType createAnnotationInfoType() {
        return new AnnotationInfoType();
    }

    /**
     * Create an instance of {@link UsageInfoType }
     * 
     */
    public UsageInfoType createUsageInfoType() {
        return new UsageInfoType();
    }

    /**
     * Create an instance of {@link CompressionInfoType }
     * 
     */
    public CompressionInfoType createCompressionInfoType() {
        return new CompressionInfoType();
    }

    /**
     * Create an instance of {@link CorpusTextInfo }
     * 
     */
    public CorpusTextInfo createCorpusTextInfo() {
        return new CorpusTextInfo();
    }

    /**
     * Create an instance of {@link CorpusTextInfoType }
     * 
     */
    public CorpusTextInfoType createCorpusTextInfoType() {
        return new CorpusTextInfoType();
    }

    /**
     * Create an instance of {@link DocumentListType }
     * 
     */
    public DocumentListType createDocumentListType() {
        return new DocumentListType();
    }

    /**
     * Create an instance of {@link MembershipInfoType }
     * 
     */
    public MembershipInfoType createMembershipInfoType() {
        return new MembershipInfoType();
    }

    /**
     * Create an instance of {@link MyString }
     * 
     */
    public MyString createMyString() {
        return new MyString();
    }

    /**
     * Create an instance of {@link TargetResourceInfoType }
     * 
     */
    public TargetResourceInfoType createTargetResourceInfoType() {
        return new TargetResourceInfoType();
    }

    /**
     * Create an instance of {@link RelatedLexiconInfoType }
     * 
     */
    public RelatedLexiconInfoType createRelatedLexiconInfoType() {
        return new RelatedLexiconInfoType();
    }

    /**
     * Create an instance of {@link ParticipantInfoType.Alias }
     * 
     */
    public ParticipantInfoType.Alias createParticipantInfoTypeAlias() {
        return new ParticipantInfoType.Alias();
    }

    /**
     * Create an instance of {@link ParticipantInfoType.DialectAccent }
     * 
     */
    public ParticipantInfoType.DialectAccent createParticipantInfoTypeDialectAccent() {
        return new ParticipantInfoType.DialectAccent();
    }

    /**
     * Create an instance of {@link OrganizationInfoType.OrganizationName }
     * 
     */
    public OrganizationInfoType.OrganizationName createOrganizationInfoTypeOrganizationName() {
        return new OrganizationInfoType.OrganizationName();
    }

    /**
     * Create an instance of {@link OrganizationInfoType.OrganizationShortName }
     * 
     */
    public OrganizationInfoType.OrganizationShortName createOrganizationInfoTypeOrganizationShortName() {
        return new OrganizationInfoType.OrganizationShortName();
    }

    /**
     * Create an instance of {@link LexicalConceptualResourceInfoType.LexicalConceptualResourceMediaType }
     * 
     */
    public LexicalConceptualResourceInfoType.LexicalConceptualResourceMediaType createLexicalConceptualResourceInfoTypeLexicalConceptualResourceMediaType() {
        return new LexicalConceptualResourceInfoType.LexicalConceptualResourceMediaType();
    }

    /**
     * Create an instance of {@link ResourceInfoType.ResourceComponentType }
     * 
     */
    public ResourceInfoType.ResourceComponentType createResourceInfoTypeResourceComponentType() {
        return new ResourceInfoType.ResourceComponentType();
    }

    /**
     * Create an instance of {@link PersonInfoType.Surname }
     * 
     */
    public PersonInfoType.Surname createPersonInfoTypeSurname() {
        return new PersonInfoType.Surname();
    }

    /**
     * Create an instance of {@link PersonInfoType.GivenName }
     * 
     */
    public PersonInfoType.GivenName createPersonInfoTypeGivenName() {
        return new PersonInfoType.GivenName();
    }

    /**
     * Create an instance of {@link DocumentInfoType.Title }
     * 
     */
    public DocumentInfoType.Title createDocumentInfoTypeTitle() {
        return new DocumentInfoType.Title();
    }

    /**
     * Create an instance of {@link CorpusInfoType.CorpusMediaType }
     * 
     */
    public CorpusInfoType.CorpusMediaType createCorpusInfoTypeCorpusMediaType() {
        return new CorpusInfoType.CorpusMediaType();
    }

    /**
     * Create an instance of {@link LanguageDescriptionInfoType.LanguageDescriptionMediaType }
     * 
     */
    public LanguageDescriptionInfoType.LanguageDescriptionMediaType createLanguageDescriptionInfoTypeLanguageDescriptionMediaType() {
        return new LanguageDescriptionInfoType.LanguageDescriptionMediaType();
    }

    /**
     * Create an instance of {@link ProjectInfoType.ProjectName }
     * 
     */
    public ProjectInfoType.ProjectName createProjectInfoTypeProjectName() {
        return new ProjectInfoType.ProjectName();
    }

    /**
     * Create an instance of {@link ProjectInfoType.ProjectShortName }
     * 
     */
    public ProjectInfoType.ProjectShortName createProjectInfoTypeProjectShortName() {
        return new ProjectInfoType.ProjectShortName();
    }

    /**
     * Create an instance of {@link IdentificationInfoType.ResourceName }
     * 
     */
    public IdentificationInfoType.ResourceName createIdentificationInfoTypeResourceName() {
        return new IdentificationInfoType.ResourceName();
    }

    /**
     * Create an instance of {@link IdentificationInfoType.Description }
     * 
     */
    public IdentificationInfoType.Description createIdentificationInfoTypeDescription() {
        return new IdentificationInfoType.Description();
    }

    /**
     * Create an instance of {@link IdentificationInfoType.ResourceShortName }
     * 
     */
    public IdentificationInfoType.ResourceShortName createIdentificationInfoTypeResourceShortName() {
        return new IdentificationInfoType.ResourceShortName();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "annotationFormat")
    public JAXBElement<String> createAnnotationFormat(String value) {
        return new JAXBElement<String>(_AnnotationFormat_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CharacterEncodingInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "characterEncodingInfo")
    public JAXBElement<CharacterEncodingInfoType> createCharacterEncodingInfo(CharacterEncodingInfoType value) {
        return new JAXBElement<CharacterEncodingInfoType>(_CharacterEncodingInfo_QNAME, CharacterEncodingInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "languageVarietyName")
    public JAXBElement<String> createLanguageVarietyName(String value) {
        return new JAXBElement<String>(_LanguageVarietyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "tagset")
    public JAXBElement<String> createTagset(String value) {
        return new JAXBElement<String>(_Tagset_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsageInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "usageInfo")
    public JAXBElement<UsageInfoType> createUsageInfo(UsageInfoType value) {
        return new JAXBElement<UsageInfoType>(_UsageInfo_QNAME, UsageInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompressionInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "compressionInfo")
    public JAXBElement<CompressionInfoType> createCompressionInfo(CompressionInfoType value) {
        return new JAXBElement<CompressionInfoType>(_CompressionInfo_QNAME, CompressionInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "documentList")
    public JAXBElement<DocumentListType> createDocumentList(DocumentListType value) {
        return new JAXBElement<DocumentListType>(_DocumentList_QNAME, DocumentListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "organizationInfo")
    public JAXBElement<OrganizationInfoType> createOrganizationInfo(OrganizationInfoType value) {
        return new JAXBElement<OrganizationInfoType>(_OrganizationInfo_QNAME, OrganizationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "languageId")
    public JAXBElement<String> createLanguageId(String value) {
        return new JAXBElement<String>(_LanguageId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "languageInfo")
    public JAXBElement<LanguageInfoType> createLanguageInfo(LanguageInfoType value) {
        return new JAXBElement<LanguageInfoType>(_LanguageInfo_QNAME, LanguageInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageDescriptionOperationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "languageDescriptionOperationInfo")
    public JAXBElement<LanguageDescriptionOperationInfoType> createLanguageDescriptionOperationInfo(LanguageDescriptionOperationInfoType value) {
        return new JAXBElement<LanguageDescriptionOperationInfoType>(_LanguageDescriptionOperationInfo_QNAME, LanguageDescriptionOperationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextFormatInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "textFormatInfo")
    public JAXBElement<TextFormatInfoType> createTextFormatInfo(TextFormatInfoType value) {
        return new JAXBElement<TextFormatInfoType>(_TextFormatInfo_QNAME, TextFormatInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "personList")
    public JAXBElement<PersonListType> createPersonList(PersonListType value) {
        return new JAXBElement<PersonListType>(_PersonList_QNAME, PersonListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "conformanceToClassificationScheme")
    public JAXBElement<String> createConformanceToClassificationScheme(String value) {
        return new JAXBElement<String>(_ConformanceToClassificationScheme_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "annotationInfo")
    public JAXBElement<AnnotationInfoType> createAnnotationInfo(AnnotationInfoType value) {
        return new JAXBElement<AnnotationInfoType>(_AnnotationInfo_QNAME, AnnotationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageDescriptionPerformanceInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "languageDescriptionPerformanceInfo")
    public JAXBElement<LanguageDescriptionPerformanceInfoType> createLanguageDescriptionPerformanceInfo(LanguageDescriptionPerformanceInfoType value) {
        return new JAXBElement<LanguageDescriptionPerformanceInfoType>(_LanguageDescriptionPerformanceInfo_QNAME, LanguageDescriptionPerformanceInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "useNLPSpecific")
    public JAXBElement<String> createUseNLPSpecific(String value) {
        return new JAXBElement<String>(_UseNLPSpecific_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "segmentationLevel")
    public JAXBElement<String> createSegmentationLevel(String value) {
        return new JAXBElement<String>(_SegmentationLevel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RunningEnvironmentInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "runningEnvironmentInfo")
    public JAXBElement<RunningEnvironmentInfoType> createRunningEnvironmentInfo(RunningEnvironmentInfoType value) {
        return new JAXBElement<RunningEnvironmentInfoType>(_RunningEnvironmentInfo_QNAME, RunningEnvironmentInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LexicalConceptualResourceInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "lexicalConceptualResourceInfo")
    public JAXBElement<LexicalConceptualResourceInfoType> createLexicalConceptualResourceInfo(LexicalConceptualResourceInfoType value) {
        return new JAXBElement<LexicalConceptualResourceInfoType>(_LexicalConceptualResourceInfo_QNAME, LexicalConceptualResourceInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "conformanceToStandardsBestPractices")
    public JAXBElement<String> createConformanceToStandardsBestPractices(String value) {
        return new JAXBElement<String>(_ConformanceToStandardsBestPractices_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextClassificationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "textClassificationInfo")
    public JAXBElement<TextClassificationInfoType> createTextClassificationInfo(TextClassificationInfoType value) {
        return new JAXBElement<TextClassificationInfoType>(_TextClassificationInfo_QNAME, TextClassificationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CorpusTextNgramInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "corpusTextNgramInfo")
    public JAXBElement<CorpusTextNgramInfoType> createCorpusTextNgramInfo(CorpusTextNgramInfoType value) {
        return new JAXBElement<CorpusTextNgramInfoType>(_CorpusTextNgramInfo_QNAME, CorpusTextNgramInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceDocumentationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "resourceDocumentationInfo")
    public JAXBElement<ResourceDocumentationInfoType> createResourceDocumentationInfo(ResourceDocumentationInfoType value) {
        return new JAXBElement<ResourceDocumentationInfoType>(_ResourceDocumentationInfo_QNAME, ResourceDocumentationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "personInfo")
    public JAXBElement<PersonInfoType> createPersonInfo(PersonInfoType value) {
        return new JAXBElement<PersonInfoType>(_PersonInfo_QNAME, PersonInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "languageName")
    public JAXBElement<String> createLanguageName(String value) {
        return new JAXBElement<String>(_LanguageName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "resourceInfo")
    public JAXBElement<ResourceInfoType> createResourceInfo(ResourceInfoType value) {
        return new JAXBElement<ResourceInfoType>(_ResourceInfo_QNAME, ResourceInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetadataInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "metadataInfo")
    public JAXBElement<MetadataInfoType> createMetadataInfo(MetadataInfoType value) {
        return new JAXBElement<MetadataInfoType>(_MetadataInfo_QNAME, MetadataInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ForeseenUseInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "foreseenUseInfo")
    public JAXBElement<ForeseenUseInfoType> createForeseenUseInfo(ForeseenUseInfoType value) {
        return new JAXBElement<ForeseenUseInfoType>(_ForeseenUseInfo_QNAME, ForeseenUseInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "documentInfo")
    public JAXBElement<DocumentInfoType> createDocumentInfo(DocumentInfoType value) {
        return new JAXBElement<DocumentInfoType>(_DocumentInfo_QNAME, DocumentInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DomainInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "domainInfo")
    public JAXBElement<DomainInfoType> createDomainInfo(DomainInfoType value) {
        return new JAXBElement<DomainInfoType>(_DomainInfo_QNAME, DomainInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceCreationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "resourceCreationInfo")
    public JAXBElement<ResourceCreationInfoType> createResourceCreationInfo(ResourceCreationInfoType value) {
        return new JAXBElement<ResourceCreationInfoType>(_ResourceCreationInfo_QNAME, ResourceCreationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SizeInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "sizeInfo")
    public JAXBElement<SizeInfoType> createSizeInfo(SizeInfoType value) {
        return new JAXBElement<SizeInfoType>(_SizeInfo_QNAME, SizeInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModalityInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "modalityInfo")
    public JAXBElement<ModalityInfoType> createModalityInfo(ModalityInfoType value) {
        return new JAXBElement<ModalityInfoType>(_ModalityInfo_QNAME, ModalityInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResolutionInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "resolutionInfo")
    public JAXBElement<ResolutionInfoType> createResolutionInfo(ResolutionInfoType value) {
        return new JAXBElement<ResolutionInfoType>(_ResolutionInfo_QNAME, ResolutionInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "characterEncoding")
    public JAXBElement<String> createCharacterEncoding(String value) {
        return new JAXBElement<String>(_CharacterEncoding_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegionNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "region")
    public JAXBElement<RegionNameType> createRegion(RegionNameType value) {
        return new JAXBElement<RegionNameType>(_Region_QNAME, RegionNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActualUseInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "actualUseInfo")
    public JAXBElement<ActualUseInfoType> createActualUseInfo(ActualUseInfoType value) {
        return new JAXBElement<ActualUseInfoType>(_ActualUseInfo_QNAME, ActualUseInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "documentationInfo")
    public JAXBElement<DocumentationInfoType> createDocumentationInfo(DocumentationInfoType value) {
        return new JAXBElement<DocumentationInfoType>(_DocumentationInfo_QNAME, DocumentationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkToOtherMediaInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "linkToOtherMediaInfo")
    public JAXBElement<LinkToOtherMediaInfoType> createLinkToOtherMediaInfo(LinkToOtherMediaInfoType value) {
        return new JAXBElement<LinkToOtherMediaInfoType>(_LinkToOtherMediaInfo_QNAME, LinkToOtherMediaInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageDescriptionEncodingInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "languageDescriptionEncodingInfo")
    public JAXBElement<LanguageDescriptionEncodingInfoType> createLanguageDescriptionEncodingInfo(LanguageDescriptionEncodingInfoType value) {
        return new JAXBElement<LanguageDescriptionEncodingInfoType>(_LanguageDescriptionEncodingInfo_QNAME, LanguageDescriptionEncodingInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "domain")
    public JAXBElement<String> createDomain(String value) {
        return new JAXBElement<String>(_Domain_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "annotationType")
    public JAXBElement<String> createAnnotationType(String value) {
        return new JAXBElement<String>(_AnnotationType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VersionInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "versionInfo")
    public JAXBElement<VersionInfoType> createVersionInfo(VersionInfoType value) {
        return new JAXBElement<VersionInfoType>(_VersionInfo_QNAME, VersionInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "mediaType")
    public JAXBElement<String> createMediaType(String value) {
        return new JAXBElement<String>(_MediaType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "textType")
    public JAXBElement<String> createTextType(String value) {
        return new JAXBElement<String>(_TextType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SettingInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "settingInfo")
    public JAXBElement<SettingInfoType> createSettingInfo(SettingInfoType value) {
        return new JAXBElement<SettingInfoType>(_SettingInfo_QNAME, SettingInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "domainId")
    public JAXBElement<String> createDomainId(String value) {
        return new JAXBElement<String>(_DomainId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "creationInfo")
    public JAXBElement<CreationInfoType> createCreationInfo(CreationInfoType value) {
        return new JAXBElement<CreationInfoType>(_CreationInfo_QNAME, CreationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "modalityType")
    public JAXBElement<String> createModalityType(String value) {
        return new JAXBElement<String>(_ModalityType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "documentUnstructured")
    public JAXBElement<String> createDocumentUnstructured(String value) {
        return new JAXBElement<String>(_DocumentUnstructured_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NgramInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "ngramInfo")
    public JAXBElement<NgramInfoType> createNgramInfo(NgramInfoType value) {
        return new JAXBElement<NgramInfoType>(_NgramInfo_QNAME, NgramInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CaptureInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "captureInfo")
    public JAXBElement<CaptureInfoType> createCaptureInfo(CaptureInfoType value) {
        return new JAXBElement<CaptureInfoType>(_CaptureInfo_QNAME, CaptureInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecordingInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "recordingInfo")
    public JAXBElement<RecordingInfoType> createRecordingInfo(RecordingInfoType value) {
        return new JAXBElement<RecordingInfoType>(_RecordingInfo_QNAME, RecordingInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CorpusInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "corpusInfo")
    public JAXBElement<CorpusInfoType> createCorpusInfo(CorpusInfoType value) {
        return new JAXBElement<CorpusInfoType>(_CorpusInfo_QNAME, CorpusInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "textGenre")
    public JAXBElement<String> createTextGenre(String value) {
        return new JAXBElement<String>(_TextGenre_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LexicalConceptualResourceEncodingInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "lexicalConceptualResourceEncodingInfo")
    public JAXBElement<LexicalConceptualResourceEncodingInfoType> createLexicalConceptualResourceEncodingInfo(LexicalConceptualResourceEncodingInfoType value) {
        return new JAXBElement<LexicalConceptualResourceEncodingInfoType>(_LexicalConceptualResourceEncodingInfo_QNAME, LexicalConceptualResourceEncodingInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageDescriptionInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "languageDescriptionInfo")
    public JAXBElement<LanguageDescriptionInfoType> createLanguageDescriptionInfo(LanguageDescriptionInfoType value) {
        return new JAXBElement<LanguageDescriptionInfoType>(_LanguageDescriptionInfo_QNAME, LanguageDescriptionInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "relationInfo")
    public JAXBElement<RelationInfoType> createRelationInfo(RelationInfoType value) {
        return new JAXBElement<RelationInfoType>(_RelationInfo_QNAME, RelationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageVarietyInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "languageVarietyInfo")
    public JAXBElement<LanguageVarietyInfoType> createLanguageVarietyInfo(LanguageVarietyInfoType value) {
        return new JAXBElement<LanguageVarietyInfoType>(_LanguageVarietyInfo_QNAME, LanguageVarietyInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommunicationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "communicationInfo")
    public JAXBElement<CommunicationInfoType> createCommunicationInfo(CommunicationInfoType value) {
        return new JAXBElement<CommunicationInfoType>(_CommunicationInfo_QNAME, CommunicationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimeCoverageInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "timeCoverageInfo")
    public JAXBElement<TimeCoverageInfoType> createTimeCoverageInfo(TimeCoverageInfoType value) {
        return new JAXBElement<TimeCoverageInfoType>(_TimeCoverageInfo_QNAME, TimeCoverageInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProjectListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "projectInfoList")
    public JAXBElement<ProjectListType> createProjectInfoList(ProjectListType value) {
        return new JAXBElement<ProjectListType>(_ProjectInfoList_QNAME, ProjectListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProjectInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "projectInfo")
    public JAXBElement<ProjectInfoType> createProjectInfo(ProjectInfoType value) {
        return new JAXBElement<ProjectInfoType>(_ProjectInfo_QNAME, ProjectInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographicCoverageInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "geographicCoverageInfo")
    public JAXBElement<GeographicCoverageInfoType> createGeographicCoverageInfo(GeographicCoverageInfoType value) {
        return new JAXBElement<GeographicCoverageInfoType>(_GeographicCoverageInfo_QNAME, GeographicCoverageInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "organizationList")
    public JAXBElement<OrganizationListType> createOrganizationList(OrganizationListType value) {
        return new JAXBElement<OrganizationListType>(_OrganizationList_QNAME, OrganizationListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "validationInfo")
    public JAXBElement<ValidationInfoType> createValidationInfo(ValidationInfoType value) {
        return new JAXBElement<ValidationInfoType>(_ValidationInfo_QNAME, ValidationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "mimeType")
    public JAXBElement<String> createMimeType(String value) {
        return new JAXBElement<String>(_MimeType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VariantNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "variants")
    public JAXBElement<VariantNameType> createVariants(VariantNameType value) {
        return new JAXBElement<VariantNameType>(_Variants_QNAME, VariantNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentificationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "identificationInfo")
    public JAXBElement<IdentificationInfoType> createIdentificationInfo(IdentificationInfoType value) {
        return new JAXBElement<IdentificationInfoType>(_IdentificationInfo_QNAME, IdentificationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonSourceSetInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "personSourceSetInfo")
    public JAXBElement<PersonSourceSetInfoType> createPersonSourceSetInfo(PersonSourceSetInfoType value) {
        return new JAXBElement<PersonSourceSetInfoType>(_PersonSourceSetInfo_QNAME, PersonSourceSetInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageScriptNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ilsp.gr/META-XMLSchema", name = "languageScript")
    public JAXBElement<LanguageScriptNameType> createLanguageScript(LanguageScriptNameType value) {
        return new JAXBElement<LanguageScriptNameType>(_LanguageScript_QNAME, LanguageScriptNameType.class, null, value);
    }

}
