//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups information on organizations related to the resource
 * 
 * <p>Java class for organizationInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="organizationInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="organizationName" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;restriction base="&lt;http://www.ilsp.gr/META-XMLSchema>myString">
 *               &lt;/restriction>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="organizationShortName" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;restriction base="&lt;http://www.ilsp.gr/META-XMLSchema>myString">
 *               &lt;/restriction>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="departmentName" type="{http://www.ilsp.gr/META-XMLSchema}myString" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}communicationInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "organizationInfoType", propOrder = {
    "organizationName",
    "organizationShortName",
    "departmentName",
    "communicationInfo"
})
public class OrganizationInfoType {

    @XmlElement(required = true)
    protected List<OrganizationInfoType.OrganizationName> organizationName;
    protected List<OrganizationInfoType.OrganizationShortName> organizationShortName;
    protected List<MyString> departmentName;
    @XmlElement(required = true)
    protected CommunicationInfoType communicationInfo;

    /**
     * Gets the value of the organizationName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organizationName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganizationName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrganizationInfoType.OrganizationName }
     * 
     * 
     */
    public List<OrganizationInfoType.OrganizationName> getOrganizationName() {
        if (organizationName == null) {
            organizationName = new ArrayList<OrganizationInfoType.OrganizationName>();
        }
        return this.organizationName;
    }

    /**
     * Gets the value of the organizationShortName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organizationShortName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganizationShortName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrganizationInfoType.OrganizationShortName }
     * 
     * 
     */
    public List<OrganizationInfoType.OrganizationShortName> getOrganizationShortName() {
        if (organizationShortName == null) {
            organizationShortName = new ArrayList<OrganizationInfoType.OrganizationShortName>();
        }
        return this.organizationShortName;
    }

    /**
     * Gets the value of the departmentName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the departmentName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDepartmentName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MyString }
     * 
     * 
     */
    public List<MyString> getDepartmentName() {
        if (departmentName == null) {
            departmentName = new ArrayList<MyString>();
        }
        return this.departmentName;
    }

    /**
     * Groups information on communication details of a person or an organization
     * 
     * @return
     *     possible object is
     *     {@link CommunicationInfoType }
     *     
     */
    public CommunicationInfoType getCommunicationInfo() {
        return communicationInfo;
    }

    /**
     * Sets the value of the communicationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommunicationInfoType }
     *     
     */
    public void setCommunicationInfo(CommunicationInfoType value) {
        this.communicationInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;restriction base="&lt;http://www.ilsp.gr/META-XMLSchema>myString">
     *     &lt;/restriction>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class OrganizationName
        extends MyString
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;restriction base="&lt;http://www.ilsp.gr/META-XMLSchema>myString">
     *     &lt;/restriction>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class OrganizationShortName
        extends MyString
    {


    }

}
