//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups information on the persons (speakers, video participants, etc.) in the audio andvideoparts of the resource
 * 
 * <p>Java class for personSourceSetInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="personSourceSetInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numberOfPersons" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ageOfPersons" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="child"/>
 *               &lt;enumeration value="teenager"/>
 *               &lt;enumeration value="adult"/>
 *               &lt;enumeration value="elderly"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ageRangeStart" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ageRangeEnd" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="sexOfPersons" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="male"/>
 *               &lt;enumeration value="female"/>
 *               &lt;enumeration value="mixed"/>
 *               &lt;enumeration value="unknown"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="originOfPersons" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="native"/>
 *               &lt;enumeration value="nonNative"/>
 *               &lt;enumeration value="mixed"/>
 *               &lt;enumeration value="unknown"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dialectAccentOfPersons" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="500"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="geographicDistributionOfPersons" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="hearingImpairmentOfPersons" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="yes"/>
 *               &lt;enumeration value="no"/>
 *               &lt;enumeration value="mixed"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="speakingImpairmentOfPersons" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="yes"/>
 *               &lt;enumeration value="no"/>
 *               &lt;enumeration value="mixed"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="numberOfTrainedSpeakers" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="speechInfluences" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="alcohol"/>
 *               &lt;enumeration value="sleepDeprivation"/>
 *               &lt;enumeration value="hyperbaric"/>
 *               &lt;enumeration value="medication"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="participantInfo" type="{http://www.ilsp.gr/META-XMLSchema}participantInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "personSourceSetInfoType", propOrder = {
    "numberOfPersons",
    "ageOfPersons",
    "ageRangeStart",
    "ageRangeEnd",
    "sexOfPersons",
    "originOfPersons",
    "dialectAccentOfPersons",
    "geographicDistributionOfPersons",
    "hearingImpairmentOfPersons",
    "speakingImpairmentOfPersons",
    "numberOfTrainedSpeakers",
    "speechInfluences",
    "participantInfo"
})
public class PersonSourceSetInfoType {

    protected BigInteger numberOfPersons;
    protected List<String> ageOfPersons;
    protected BigInteger ageRangeStart;
    protected BigInteger ageRangeEnd;
    protected String sexOfPersons;
    protected String originOfPersons;
    protected List<String> dialectAccentOfPersons;
    protected String geographicDistributionOfPersons;
    protected String hearingImpairmentOfPersons;
    protected String speakingImpairmentOfPersons;
    protected BigInteger numberOfTrainedSpeakers;
    protected List<String> speechInfluences;
    protected List<ParticipantInfoType> participantInfo;

    /**
     * Gets the value of the numberOfPersons property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfPersons() {
        return numberOfPersons;
    }

    /**
     * Sets the value of the numberOfPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfPersons(BigInteger value) {
        this.numberOfPersons = value;
    }

    /**
     * Gets the value of the ageOfPersons property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ageOfPersons property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgeOfPersons().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAgeOfPersons() {
        if (ageOfPersons == null) {
            ageOfPersons = new ArrayList<String>();
        }
        return this.ageOfPersons;
    }

    /**
     * Gets the value of the ageRangeStart property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAgeRangeStart() {
        return ageRangeStart;
    }

    /**
     * Sets the value of the ageRangeStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAgeRangeStart(BigInteger value) {
        this.ageRangeStart = value;
    }

    /**
     * Gets the value of the ageRangeEnd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAgeRangeEnd() {
        return ageRangeEnd;
    }

    /**
     * Sets the value of the ageRangeEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAgeRangeEnd(BigInteger value) {
        this.ageRangeEnd = value;
    }

    /**
     * Gets the value of the sexOfPersons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSexOfPersons() {
        return sexOfPersons;
    }

    /**
     * Sets the value of the sexOfPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSexOfPersons(String value) {
        this.sexOfPersons = value;
    }

    /**
     * Gets the value of the originOfPersons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginOfPersons() {
        return originOfPersons;
    }

    /**
     * Sets the value of the originOfPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginOfPersons(String value) {
        this.originOfPersons = value;
    }

    /**
     * Gets the value of the dialectAccentOfPersons property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dialectAccentOfPersons property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDialectAccentOfPersons().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDialectAccentOfPersons() {
        if (dialectAccentOfPersons == null) {
            dialectAccentOfPersons = new ArrayList<String>();
        }
        return this.dialectAccentOfPersons;
    }

    /**
     * Gets the value of the geographicDistributionOfPersons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeographicDistributionOfPersons() {
        return geographicDistributionOfPersons;
    }

    /**
     * Sets the value of the geographicDistributionOfPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeographicDistributionOfPersons(String value) {
        this.geographicDistributionOfPersons = value;
    }

    /**
     * Gets the value of the hearingImpairmentOfPersons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHearingImpairmentOfPersons() {
        return hearingImpairmentOfPersons;
    }

    /**
     * Sets the value of the hearingImpairmentOfPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHearingImpairmentOfPersons(String value) {
        this.hearingImpairmentOfPersons = value;
    }

    /**
     * Gets the value of the speakingImpairmentOfPersons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpeakingImpairmentOfPersons() {
        return speakingImpairmentOfPersons;
    }

    /**
     * Sets the value of the speakingImpairmentOfPersons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpeakingImpairmentOfPersons(String value) {
        this.speakingImpairmentOfPersons = value;
    }

    /**
     * Gets the value of the numberOfTrainedSpeakers property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfTrainedSpeakers() {
        return numberOfTrainedSpeakers;
    }

    /**
     * Sets the value of the numberOfTrainedSpeakers property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfTrainedSpeakers(BigInteger value) {
        this.numberOfTrainedSpeakers = value;
    }

    /**
     * Gets the value of the speechInfluences property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the speechInfluences property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpeechInfluences().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSpeechInfluences() {
        if (speechInfluences == null) {
            speechInfluences = new ArrayList<String>();
        }
        return this.speechInfluences;
    }

    /**
     * Gets the value of the participantInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the participantInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParticipantInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParticipantInfoType }
     * 
     * 
     */
    public List<ParticipantInfoType> getParticipantInfo() {
        if (participantInfo == null) {
            participantInfo = new ArrayList<ParticipantInfoType>();
        }
        return this.participantInfo;
    }

}
