//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups together information on the recording of the audio or video part of a resource
 * 
 * <p>Java class for recordingInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="recordingInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="recordingDeviceType" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="hardDisk"/>
 *               &lt;enumeration value="dv"/>
 *               &lt;enumeration value="tapeVHS"/>
 *               &lt;enumeration value="flash"/>
 *               &lt;enumeration value="DAT"/>
 *               &lt;enumeration value="soundBlasterCard"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="recordingDeviceTypeDetails" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="500"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="recordingPlatformSoftware" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="recordingEnvironment" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="office"/>
 *               &lt;enumeration value="inCar"/>
 *               &lt;enumeration value="studio"/>
 *               &lt;enumeration value="conferenceRoom"/>
 *               &lt;enumeration value="lectureRoom"/>
 *               &lt;enumeration value="industrial"/>
 *               &lt;enumeration value="transport"/>
 *               &lt;enumeration value="openPublicPlace"/>
 *               &lt;enumeration value="closedPublicPlace"/>
 *               &lt;enumeration value="anechoicChamber"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="sourceChannel" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="internet"/>
 *               &lt;enumeration value="radio"/>
 *               &lt;enumeration value="tv"/>
 *               &lt;enumeration value="telephone"/>
 *               &lt;enumeration value="laryngograph"/>
 *               &lt;enumeration value="airflow"/>
 *               &lt;enumeration value="EMA"/>
 *               &lt;enumeration value="webCam"/>
 *               &lt;enumeration value="camcorder"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="sourceChannelType" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="ISDN"/>
 *               &lt;enumeration value="GSM"/>
 *               &lt;enumeration value="3G"/>
 *               &lt;enumeration value="CDMA"/>
 *               &lt;enumeration value="DVB-T"/>
 *               &lt;enumeration value="DVB-S"/>
 *               &lt;enumeration value="DVB-C"/>
 *               &lt;enumeration value="VOIP"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="sourceChannelName" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="sourceChannelDetails" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="recorder" type="{http://www.ilsp.gr/META-XMLSchema}actorInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recordingInfoType", propOrder = {
    "recordingDeviceType",
    "recordingDeviceTypeDetails",
    "recordingPlatformSoftware",
    "recordingEnvironment",
    "sourceChannel",
    "sourceChannelType",
    "sourceChannelName",
    "sourceChannelDetails",
    "recorder"
})
public class RecordingInfoType {

    protected List<String> recordingDeviceType;
    protected String recordingDeviceTypeDetails;
    protected List<String> recordingPlatformSoftware;
    protected List<String> recordingEnvironment;
    protected List<String> sourceChannel;
    protected List<String> sourceChannelType;
    protected List<String> sourceChannelName;
    protected String sourceChannelDetails;
    protected List<ActorInfoType> recorder;

    /**
     * Gets the value of the recordingDeviceType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recordingDeviceType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecordingDeviceType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRecordingDeviceType() {
        if (recordingDeviceType == null) {
            recordingDeviceType = new ArrayList<String>();
        }
        return this.recordingDeviceType;
    }

    /**
     * Gets the value of the recordingDeviceTypeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordingDeviceTypeDetails() {
        return recordingDeviceTypeDetails;
    }

    /**
     * Sets the value of the recordingDeviceTypeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordingDeviceTypeDetails(String value) {
        this.recordingDeviceTypeDetails = value;
    }

    /**
     * Gets the value of the recordingPlatformSoftware property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recordingPlatformSoftware property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecordingPlatformSoftware().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRecordingPlatformSoftware() {
        if (recordingPlatformSoftware == null) {
            recordingPlatformSoftware = new ArrayList<String>();
        }
        return this.recordingPlatformSoftware;
    }

    /**
     * Gets the value of the recordingEnvironment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recordingEnvironment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecordingEnvironment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRecordingEnvironment() {
        if (recordingEnvironment == null) {
            recordingEnvironment = new ArrayList<String>();
        }
        return this.recordingEnvironment;
    }

    /**
     * Gets the value of the sourceChannel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceChannel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceChannel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSourceChannel() {
        if (sourceChannel == null) {
            sourceChannel = new ArrayList<String>();
        }
        return this.sourceChannel;
    }

    /**
     * Gets the value of the sourceChannelType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceChannelType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceChannelType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSourceChannelType() {
        if (sourceChannelType == null) {
            sourceChannelType = new ArrayList<String>();
        }
        return this.sourceChannelType;
    }

    /**
     * Gets the value of the sourceChannelName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourceChannelName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourceChannelName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSourceChannelName() {
        if (sourceChannelName == null) {
            sourceChannelName = new ArrayList<String>();
        }
        return this.sourceChannelName;
    }

    /**
     * Gets the value of the sourceChannelDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceChannelDetails() {
        return sourceChannelDetails;
    }

    /**
     * Sets the value of the sourceChannelDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceChannelDetails(String value) {
        this.sourceChannelDetails = value;
    }

    /**
     * Gets the value of the recorder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recorder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecorder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActorInfoType }
     * 
     * 
     */
    public List<ActorInfoType> getRecorder() {
        if (recorder == null) {
            recorder = new ArrayList<ActorInfoType>();
        }
        return this.recorder;
    }

}
