//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for regionNameType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="regionNameType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="100"/>
 *     &lt;enumeration value="Private use"/>
 *     &lt;enumeration value="Ascension Island"/>
 *     &lt;enumeration value="Andorra"/>
 *     &lt;enumeration value="United Arab Emirates"/>
 *     &lt;enumeration value="Afghanistan"/>
 *     &lt;enumeration value="Antigua and Barbuda"/>
 *     &lt;enumeration value="Anguilla"/>
 *     &lt;enumeration value="Albania"/>
 *     &lt;enumeration value="Armenia"/>
 *     &lt;enumeration value="Angola"/>
 *     &lt;enumeration value="Antarctica"/>
 *     &lt;enumeration value="Argentina"/>
 *     &lt;enumeration value="American Samoa"/>
 *     &lt;enumeration value="Austria"/>
 *     &lt;enumeration value="Australia"/>
 *     &lt;enumeration value="Aruba"/>
 *     &lt;enumeration value="Åland Islands"/>
 *     &lt;enumeration value="Azerbaijan"/>
 *     &lt;enumeration value="Bosnia and Herzegovina"/>
 *     &lt;enumeration value="Barbados"/>
 *     &lt;enumeration value="Bangladesh"/>
 *     &lt;enumeration value="Belgium"/>
 *     &lt;enumeration value="Burkina Faso"/>
 *     &lt;enumeration value="Bulgaria"/>
 *     &lt;enumeration value="Bahrain"/>
 *     &lt;enumeration value="Burundi"/>
 *     &lt;enumeration value="Benin"/>
 *     &lt;enumeration value="Saint Barthélemy"/>
 *     &lt;enumeration value="Bermuda"/>
 *     &lt;enumeration value="Brunei Darussalam"/>
 *     &lt;enumeration value="Bolivia"/>
 *     &lt;enumeration value="Bonaire, Sint Eustatius and Saba"/>
 *     &lt;enumeration value="Brazil"/>
 *     &lt;enumeration value="Bahamas"/>
 *     &lt;enumeration value="Bhutan"/>
 *     &lt;enumeration value="Bouvet Island"/>
 *     &lt;enumeration value="Botswana"/>
 *     &lt;enumeration value="Belarus"/>
 *     &lt;enumeration value="Belize"/>
 *     &lt;enumeration value="Canada"/>
 *     &lt;enumeration value="Cocos (Keeling) Islands"/>
 *     &lt;enumeration value="The Democratic Republic of the Congo"/>
 *     &lt;enumeration value="Central African Republic"/>
 *     &lt;enumeration value="Congo"/>
 *     &lt;enumeration value="Switzerland"/>
 *     &lt;enumeration value="Côte d'Ivoire"/>
 *     &lt;enumeration value="Cook Islands"/>
 *     &lt;enumeration value="Chile"/>
 *     &lt;enumeration value="Cameroon"/>
 *     &lt;enumeration value="China"/>
 *     &lt;enumeration value="Colombia"/>
 *     &lt;enumeration value="Clipperton Island"/>
 *     &lt;enumeration value="Costa Rica"/>
 *     &lt;enumeration value="Cuba"/>
 *     &lt;enumeration value="Cabo Verde; Cape Verde"/>
 *     &lt;enumeration value="Curaçao"/>
 *     &lt;enumeration value="Christmas Island"/>
 *     &lt;enumeration value="Cyprus"/>
 *     &lt;enumeration value="Czech Republic"/>
 *     &lt;enumeration value="Germany"/>
 *     &lt;enumeration value="Diego Garcia"/>
 *     &lt;enumeration value="Djibouti"/>
 *     &lt;enumeration value="Denmark"/>
 *     &lt;enumeration value="Dominica"/>
 *     &lt;enumeration value="Dominican Republic"/>
 *     &lt;enumeration value="Algeria"/>
 *     &lt;enumeration value="Ceuta, Melilla"/>
 *     &lt;enumeration value="Ecuador"/>
 *     &lt;enumeration value="Estonia"/>
 *     &lt;enumeration value="Egypt"/>
 *     &lt;enumeration value="Western Sahara"/>
 *     &lt;enumeration value="Eritrea"/>
 *     &lt;enumeration value="Spain"/>
 *     &lt;enumeration value="Ethiopia"/>
 *     &lt;enumeration value="European Union"/>
 *     &lt;enumeration value="Finland"/>
 *     &lt;enumeration value="Fiji"/>
 *     &lt;enumeration value="Falkland Islands (Malvinas)"/>
 *     &lt;enumeration value="Federated States of Micronesia"/>
 *     &lt;enumeration value="Faroe Islands"/>
 *     &lt;enumeration value="France"/>
 *     &lt;enumeration value="Gabon"/>
 *     &lt;enumeration value="United Kingdom"/>
 *     &lt;enumeration value="Grenada"/>
 *     &lt;enumeration value="Georgia"/>
 *     &lt;enumeration value="French Guiana"/>
 *     &lt;enumeration value="Guernsey"/>
 *     &lt;enumeration value="Ghana"/>
 *     &lt;enumeration value="Gibraltar"/>
 *     &lt;enumeration value="Greenland"/>
 *     &lt;enumeration value="Gambia"/>
 *     &lt;enumeration value="Guinea"/>
 *     &lt;enumeration value="Guadeloupe"/>
 *     &lt;enumeration value="Equatorial Guinea"/>
 *     &lt;enumeration value="Greece"/>
 *     &lt;enumeration value="South Georgia and the South Sandwich Islands"/>
 *     &lt;enumeration value="Guatemala"/>
 *     &lt;enumeration value="Guam"/>
 *     &lt;enumeration value="Guinea-Bissau"/>
 *     &lt;enumeration value="Guyana"/>
 *     &lt;enumeration value="Hong Kong"/>
 *     &lt;enumeration value="Heard Island and McDonald Islands"/>
 *     &lt;enumeration value="Honduras"/>
 *     &lt;enumeration value="Croatia"/>
 *     &lt;enumeration value="Haiti"/>
 *     &lt;enumeration value="Hungary"/>
 *     &lt;enumeration value="Canary Islands"/>
 *     &lt;enumeration value="Indonesia"/>
 *     &lt;enumeration value="Ireland"/>
 *     &lt;enumeration value="Israel"/>
 *     &lt;enumeration value="Isle of Man"/>
 *     &lt;enumeration value="India"/>
 *     &lt;enumeration value="British Indian Ocean Territory"/>
 *     &lt;enumeration value="Iraq"/>
 *     &lt;enumeration value="Islamic Republic of Iran"/>
 *     &lt;enumeration value="Iceland"/>
 *     &lt;enumeration value="Italy"/>
 *     &lt;enumeration value="Jersey"/>
 *     &lt;enumeration value="Jamaica"/>
 *     &lt;enumeration value="Jordan"/>
 *     &lt;enumeration value="Japan"/>
 *     &lt;enumeration value="Kenya"/>
 *     &lt;enumeration value="Kyrgyzstan"/>
 *     &lt;enumeration value="Cambodia"/>
 *     &lt;enumeration value="Kiribati"/>
 *     &lt;enumeration value="Comoros"/>
 *     &lt;enumeration value="Saint Kitts and Nevis"/>
 *     &lt;enumeration value="Democratic People's Republic of Korea"/>
 *     &lt;enumeration value="Republic of Korea"/>
 *     &lt;enumeration value="Kuwait"/>
 *     &lt;enumeration value="Cayman Islands"/>
 *     &lt;enumeration value="Kazakhstan"/>
 *     &lt;enumeration value="Lao People's Democratic Republic"/>
 *     &lt;enumeration value="Lebanon"/>
 *     &lt;enumeration value="Saint Lucia"/>
 *     &lt;enumeration value="Liechtenstein"/>
 *     &lt;enumeration value="Sri Lanka"/>
 *     &lt;enumeration value="Liberia"/>
 *     &lt;enumeration value="Lesotho"/>
 *     &lt;enumeration value="Lithuania"/>
 *     &lt;enumeration value="Luxembourg"/>
 *     &lt;enumeration value="Latvia"/>
 *     &lt;enumeration value="Libya"/>
 *     &lt;enumeration value="Morocco"/>
 *     &lt;enumeration value="Monaco"/>
 *     &lt;enumeration value="Moldova"/>
 *     &lt;enumeration value="Montenegro"/>
 *     &lt;enumeration value="Saint Martin (French part)"/>
 *     &lt;enumeration value="Madagascar"/>
 *     &lt;enumeration value="Marshall Islands"/>
 *     &lt;enumeration value="The Former Yugoslav Republic of Macedonia"/>
 *     &lt;enumeration value="Mali"/>
 *     &lt;enumeration value="Myanmar"/>
 *     &lt;enumeration value="Mongolia"/>
 *     &lt;enumeration value="Macao"/>
 *     &lt;enumeration value="Northern Mariana Islands"/>
 *     &lt;enumeration value="Martinique"/>
 *     &lt;enumeration value="Mauritania"/>
 *     &lt;enumeration value="Montserrat"/>
 *     &lt;enumeration value="Malta"/>
 *     &lt;enumeration value="Mauritius"/>
 *     &lt;enumeration value="Maldives"/>
 *     &lt;enumeration value="Malawi"/>
 *     &lt;enumeration value="Mexico"/>
 *     &lt;enumeration value="Malaysia"/>
 *     &lt;enumeration value="Mozambique"/>
 *     &lt;enumeration value="Namibia"/>
 *     &lt;enumeration value="New Caledonia"/>
 *     &lt;enumeration value="Niger"/>
 *     &lt;enumeration value="Norfolk Island"/>
 *     &lt;enumeration value="Nigeria"/>
 *     &lt;enumeration value="Nicaragua"/>
 *     &lt;enumeration value="Netherlands"/>
 *     &lt;enumeration value="Norway"/>
 *     &lt;enumeration value="Nepal"/>
 *     &lt;enumeration value="Nauru"/>
 *     &lt;enumeration value="Niue"/>
 *     &lt;enumeration value="New Zealand"/>
 *     &lt;enumeration value="Oman"/>
 *     &lt;enumeration value="Panama"/>
 *     &lt;enumeration value="Peru"/>
 *     &lt;enumeration value="French Polynesia"/>
 *     &lt;enumeration value="Papua New Guinea"/>
 *     &lt;enumeration value="Philippines"/>
 *     &lt;enumeration value="Pakistan"/>
 *     &lt;enumeration value="Poland"/>
 *     &lt;enumeration value="Saint Pierre and Miquelon"/>
 *     &lt;enumeration value="Pitcairn"/>
 *     &lt;enumeration value="Puerto Rico"/>
 *     &lt;enumeration value="State of Palestine"/>
 *     &lt;enumeration value="Portugal"/>
 *     &lt;enumeration value="Palau"/>
 *     &lt;enumeration value="Paraguay"/>
 *     &lt;enumeration value="Qatar"/>
 *     &lt;enumeration value="Private use"/>
 *     &lt;enumeration value="Réunion"/>
 *     &lt;enumeration value="Romania"/>
 *     &lt;enumeration value="Serbia"/>
 *     &lt;enumeration value="Russian Federation"/>
 *     &lt;enumeration value="Rwanda"/>
 *     &lt;enumeration value="Saudi Arabia"/>
 *     &lt;enumeration value="Solomon Islands"/>
 *     &lt;enumeration value="Seychelles"/>
 *     &lt;enumeration value="Sudan"/>
 *     &lt;enumeration value="Sweden"/>
 *     &lt;enumeration value="Singapore"/>
 *     &lt;enumeration value="Saint Helena, Ascension and Tristan da Cunha"/>
 *     &lt;enumeration value="Slovenia"/>
 *     &lt;enumeration value="Svalbard and Jan Mayen"/>
 *     &lt;enumeration value="Slovakia"/>
 *     &lt;enumeration value="Sierra Leone"/>
 *     &lt;enumeration value="San Marino"/>
 *     &lt;enumeration value="Senegal"/>
 *     &lt;enumeration value="Somalia"/>
 *     &lt;enumeration value="Suriname"/>
 *     &lt;enumeration value="South Sudan"/>
 *     &lt;enumeration value="Sao Tome and Principe"/>
 *     &lt;enumeration value="El Salvador"/>
 *     &lt;enumeration value="Sint Maarten (Dutch part)"/>
 *     &lt;enumeration value="Syrian Arab Republic"/>
 *     &lt;enumeration value="Swaziland"/>
 *     &lt;enumeration value="Tristan da Cunha"/>
 *     &lt;enumeration value="Turks and Caicos Islands"/>
 *     &lt;enumeration value="Chad"/>
 *     &lt;enumeration value="French Southern Territories"/>
 *     &lt;enumeration value="Togo"/>
 *     &lt;enumeration value="Thailand"/>
 *     &lt;enumeration value="Tajikistan"/>
 *     &lt;enumeration value="Tokelau"/>
 *     &lt;enumeration value="Timor-Leste"/>
 *     &lt;enumeration value="Turkmenistan"/>
 *     &lt;enumeration value="Tunisia"/>
 *     &lt;enumeration value="Tonga"/>
 *     &lt;enumeration value="Turkey"/>
 *     &lt;enumeration value="Trinidad and Tobago"/>
 *     &lt;enumeration value="Tuvalu"/>
 *     &lt;enumeration value="Taiwan, Province of China"/>
 *     &lt;enumeration value="United Republic of Tanzania"/>
 *     &lt;enumeration value="Ukraine"/>
 *     &lt;enumeration value="Uganda"/>
 *     &lt;enumeration value="United States Minor Outlying Islands"/>
 *     &lt;enumeration value="United States"/>
 *     &lt;enumeration value="Uruguay"/>
 *     &lt;enumeration value="Uzbekistan"/>
 *     &lt;enumeration value="Holy See (Vatican City State)"/>
 *     &lt;enumeration value="Saint Vincent and the Grenadines"/>
 *     &lt;enumeration value="Venezuela"/>
 *     &lt;enumeration value="British Virgin Islands"/>
 *     &lt;enumeration value="U.S. Virgin Islands"/>
 *     &lt;enumeration value="Viet Nam"/>
 *     &lt;enumeration value="Vanuatu"/>
 *     &lt;enumeration value="Wallis and Futuna"/>
 *     &lt;enumeration value="Samoa"/>
 *     &lt;enumeration value="Private use"/>
 *     &lt;enumeration value="Yemen"/>
 *     &lt;enumeration value="Mayotte"/>
 *     &lt;enumeration value="South Africa"/>
 *     &lt;enumeration value="Zambia"/>
 *     &lt;enumeration value="Zimbabwe"/>
 *     &lt;enumeration value="Private use"/>
 *     &lt;enumeration value="World"/>
 *     &lt;enumeration value="Africa"/>
 *     &lt;enumeration value="North America"/>
 *     &lt;enumeration value="South America"/>
 *     &lt;enumeration value="Oceania"/>
 *     &lt;enumeration value="Western Africa"/>
 *     &lt;enumeration value="Central America"/>
 *     &lt;enumeration value="Eastern Africa"/>
 *     &lt;enumeration value="Northern Africa"/>
 *     &lt;enumeration value="Middle Africa"/>
 *     &lt;enumeration value="Southern Africa"/>
 *     &lt;enumeration value="Americas"/>
 *     &lt;enumeration value="Northern America"/>
 *     &lt;enumeration value="Caribbean"/>
 *     &lt;enumeration value="Eastern Asia"/>
 *     &lt;enumeration value="Southern Asia"/>
 *     &lt;enumeration value="South-Eastern Asia"/>
 *     &lt;enumeration value="Southern Europe"/>
 *     &lt;enumeration value="Australia and New Zealand"/>
 *     &lt;enumeration value="Melanesia"/>
 *     &lt;enumeration value="Micronesia"/>
 *     &lt;enumeration value="Polynesia"/>
 *     &lt;enumeration value="Asia"/>
 *     &lt;enumeration value="Central Asia"/>
 *     &lt;enumeration value="Western Asia"/>
 *     &lt;enumeration value="Europe"/>
 *     &lt;enumeration value="Eastern Europe"/>
 *     &lt;enumeration value="Northern Europe"/>
 *     &lt;enumeration value="Western Europe"/>
 *     &lt;enumeration value="Latin America and the Caribbean"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "regionNameType")
@XmlEnum
public enum RegionNameType {

    @XmlEnumValue("Private use")
    PRIVATE_USE("Private use"),
    @XmlEnumValue("Ascension Island")
    ASCENSION_ISLAND("Ascension Island"),
    @XmlEnumValue("Andorra")
    ANDORRA("Andorra"),
    @XmlEnumValue("United Arab Emirates")
    UNITED_ARAB_EMIRATES("United Arab Emirates"),
    @XmlEnumValue("Afghanistan")
    AFGHANISTAN("Afghanistan"),
    @XmlEnumValue("Antigua and Barbuda")
    ANTIGUA_AND_BARBUDA("Antigua and Barbuda"),
    @XmlEnumValue("Anguilla")
    ANGUILLA("Anguilla"),
    @XmlEnumValue("Albania")
    ALBANIA("Albania"),
    @XmlEnumValue("Armenia")
    ARMENIA("Armenia"),
    @XmlEnumValue("Angola")
    ANGOLA("Angola"),
    @XmlEnumValue("Antarctica")
    ANTARCTICA("Antarctica"),
    @XmlEnumValue("Argentina")
    ARGENTINA("Argentina"),
    @XmlEnumValue("American Samoa")
    AMERICAN_SAMOA("American Samoa"),
    @XmlEnumValue("Austria")
    AUSTRIA("Austria"),
    @XmlEnumValue("Australia")
    AUSTRALIA("Australia"),
    @XmlEnumValue("Aruba")
    ARUBA("Aruba"),
    @XmlEnumValue("\u00c5land Islands")
    ÅLAND_ISLANDS("\u00c5land Islands"),
    @XmlEnumValue("Azerbaijan")
    AZERBAIJAN("Azerbaijan"),
    @XmlEnumValue("Bosnia and Herzegovina")
    BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina"),
    @XmlEnumValue("Barbados")
    BARBADOS("Barbados"),
    @XmlEnumValue("Bangladesh")
    BANGLADESH("Bangladesh"),
    @XmlEnumValue("Belgium")
    BELGIUM("Belgium"),
    @XmlEnumValue("Burkina Faso")
    BURKINA_FASO("Burkina Faso"),
    @XmlEnumValue("Bulgaria")
    BULGARIA("Bulgaria"),
    @XmlEnumValue("Bahrain")
    BAHRAIN("Bahrain"),
    @XmlEnumValue("Burundi")
    BURUNDI("Burundi"),
    @XmlEnumValue("Benin")
    BENIN("Benin"),
    @XmlEnumValue("Saint Barth\u00e9lemy")
    SAINT_BARTHÉLEMY("Saint Barth\u00e9lemy"),
    @XmlEnumValue("Bermuda")
    BERMUDA("Bermuda"),
    @XmlEnumValue("Brunei Darussalam")
    BRUNEI_DARUSSALAM("Brunei Darussalam"),
    @XmlEnumValue("Bolivia")
    BOLIVIA("Bolivia"),
    @XmlEnumValue("Bonaire, Sint Eustatius and Saba")
    BONAIRE_SINT_EUSTATIUS_AND_SABA("Bonaire, Sint Eustatius and Saba"),
    @XmlEnumValue("Brazil")
    BRAZIL("Brazil"),
    @XmlEnumValue("Bahamas")
    BAHAMAS("Bahamas"),
    @XmlEnumValue("Bhutan")
    BHUTAN("Bhutan"),
    @XmlEnumValue("Bouvet Island")
    BOUVET_ISLAND("Bouvet Island"),
    @XmlEnumValue("Botswana")
    BOTSWANA("Botswana"),
    @XmlEnumValue("Belarus")
    BELARUS("Belarus"),
    @XmlEnumValue("Belize")
    BELIZE("Belize"),
    @XmlEnumValue("Canada")
    CANADA("Canada"),
    @XmlEnumValue("Cocos (Keeling) Islands")
    COCOS_KEELING_ISLANDS("Cocos (Keeling) Islands"),
    @XmlEnumValue("The Democratic Republic of the Congo")
    THE_DEMOCRATIC_REPUBLIC_OF_THE_CONGO("The Democratic Republic of the Congo"),
    @XmlEnumValue("Central African Republic")
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic"),
    @XmlEnumValue("Congo")
    CONGO("Congo"),
    @XmlEnumValue("Switzerland")
    SWITZERLAND("Switzerland"),
    @XmlEnumValue("C\u00f4te d'Ivoire")
    CÔTE_D_IVOIRE("C\u00f4te d'Ivoire"),
    @XmlEnumValue("Cook Islands")
    COOK_ISLANDS("Cook Islands"),
    @XmlEnumValue("Chile")
    CHILE("Chile"),
    @XmlEnumValue("Cameroon")
    CAMEROON("Cameroon"),
    @XmlEnumValue("China")
    CHINA("China"),
    @XmlEnumValue("Colombia")
    COLOMBIA("Colombia"),
    @XmlEnumValue("Clipperton Island")
    CLIPPERTON_ISLAND("Clipperton Island"),
    @XmlEnumValue("Costa Rica")
    COSTA_RICA("Costa Rica"),
    @XmlEnumValue("Cuba")
    CUBA("Cuba"),
    @XmlEnumValue("Cabo Verde; Cape Verde")
    CABO_VERDE_CAPE_VERDE("Cabo Verde; Cape Verde"),
    @XmlEnumValue("Cura\u00e7ao")
    CURAÇAO("Cura\u00e7ao"),
    @XmlEnumValue("Christmas Island")
    CHRISTMAS_ISLAND("Christmas Island"),
    @XmlEnumValue("Cyprus")
    CYPRUS("Cyprus"),
    @XmlEnumValue("Czech Republic")
    CZECH_REPUBLIC("Czech Republic"),
    @XmlEnumValue("Germany")
    GERMANY("Germany"),
    @XmlEnumValue("Diego Garcia")
    DIEGO_GARCIA("Diego Garcia"),
    @XmlEnumValue("Djibouti")
    DJIBOUTI("Djibouti"),
    @XmlEnumValue("Denmark")
    DENMARK("Denmark"),
    @XmlEnumValue("Dominica")
    DOMINICA("Dominica"),
    @XmlEnumValue("Dominican Republic")
    DOMINICAN_REPUBLIC("Dominican Republic"),
    @XmlEnumValue("Algeria")
    ALGERIA("Algeria"),
    @XmlEnumValue("Ceuta, Melilla")
    CEUTA_MELILLA("Ceuta, Melilla"),
    @XmlEnumValue("Ecuador")
    ECUADOR("Ecuador"),
    @XmlEnumValue("Estonia")
    ESTONIA("Estonia"),
    @XmlEnumValue("Egypt")
    EGYPT("Egypt"),
    @XmlEnumValue("Western Sahara")
    WESTERN_SAHARA("Western Sahara"),
    @XmlEnumValue("Eritrea")
    ERITREA("Eritrea"),
    @XmlEnumValue("Spain")
    SPAIN("Spain"),
    @XmlEnumValue("Ethiopia")
    ETHIOPIA("Ethiopia"),
    @XmlEnumValue("European Union")
    EUROPEAN_UNION("European Union"),
    @XmlEnumValue("Finland")
    FINLAND("Finland"),
    @XmlEnumValue("Fiji")
    FIJI("Fiji"),
    @XmlEnumValue("Falkland Islands (Malvinas)")
    FALKLAND_ISLANDS_MALVINAS("Falkland Islands (Malvinas)"),
    @XmlEnumValue("Federated States of Micronesia")
    FEDERATED_STATES_OF_MICRONESIA("Federated States of Micronesia"),
    @XmlEnumValue("Faroe Islands")
    FAROE_ISLANDS("Faroe Islands"),
    @XmlEnumValue("France")
    FRANCE("France"),
    @XmlEnumValue("Gabon")
    GABON("Gabon"),
    @XmlEnumValue("United Kingdom")
    UNITED_KINGDOM("United Kingdom"),
    @XmlEnumValue("Grenada")
    GRENADA("Grenada"),
    @XmlEnumValue("Georgia")
    GEORGIA("Georgia"),
    @XmlEnumValue("French Guiana")
    FRENCH_GUIANA("French Guiana"),
    @XmlEnumValue("Guernsey")
    GUERNSEY("Guernsey"),
    @XmlEnumValue("Ghana")
    GHANA("Ghana"),
    @XmlEnumValue("Gibraltar")
    GIBRALTAR("Gibraltar"),
    @XmlEnumValue("Greenland")
    GREENLAND("Greenland"),
    @XmlEnumValue("Gambia")
    GAMBIA("Gambia"),
    @XmlEnumValue("Guinea")
    GUINEA("Guinea"),
    @XmlEnumValue("Guadeloupe")
    GUADELOUPE("Guadeloupe"),
    @XmlEnumValue("Equatorial Guinea")
    EQUATORIAL_GUINEA("Equatorial Guinea"),
    @XmlEnumValue("Greece")
    GREECE("Greece"),
    @XmlEnumValue("South Georgia and the South Sandwich Islands")
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS("South Georgia and the South Sandwich Islands"),
    @XmlEnumValue("Guatemala")
    GUATEMALA("Guatemala"),
    @XmlEnumValue("Guam")
    GUAM("Guam"),
    @XmlEnumValue("Guinea-Bissau")
    GUINEA_BISSAU("Guinea-Bissau"),
    @XmlEnumValue("Guyana")
    GUYANA("Guyana"),
    @XmlEnumValue("Hong Kong")
    HONG_KONG("Hong Kong"),
    @XmlEnumValue("Heard Island and McDonald Islands")
    HEARD_ISLAND_AND_MC_DONALD_ISLANDS("Heard Island and McDonald Islands"),
    @XmlEnumValue("Honduras")
    HONDURAS("Honduras"),
    @XmlEnumValue("Croatia")
    CROATIA("Croatia"),
    @XmlEnumValue("Haiti")
    HAITI("Haiti"),
    @XmlEnumValue("Hungary")
    HUNGARY("Hungary"),
    @XmlEnumValue("Canary Islands")
    CANARY_ISLANDS("Canary Islands"),
    @XmlEnumValue("Indonesia")
    INDONESIA("Indonesia"),
    @XmlEnumValue("Ireland")
    IRELAND("Ireland"),
    @XmlEnumValue("Israel")
    ISRAEL("Israel"),
    @XmlEnumValue("Isle of Man")
    ISLE_OF_MAN("Isle of Man"),
    @XmlEnumValue("India")
    INDIA("India"),
    @XmlEnumValue("British Indian Ocean Territory")
    BRITISH_INDIAN_OCEAN_TERRITORY("British Indian Ocean Territory"),
    @XmlEnumValue("Iraq")
    IRAQ("Iraq"),
    @XmlEnumValue("Islamic Republic of Iran")
    ISLAMIC_REPUBLIC_OF_IRAN("Islamic Republic of Iran"),
    @XmlEnumValue("Iceland")
    ICELAND("Iceland"),
    @XmlEnumValue("Italy")
    ITALY("Italy"),
    @XmlEnumValue("Jersey")
    JERSEY("Jersey"),
    @XmlEnumValue("Jamaica")
    JAMAICA("Jamaica"),
    @XmlEnumValue("Jordan")
    JORDAN("Jordan"),
    @XmlEnumValue("Japan")
    JAPAN("Japan"),
    @XmlEnumValue("Kenya")
    KENYA("Kenya"),
    @XmlEnumValue("Kyrgyzstan")
    KYRGYZSTAN("Kyrgyzstan"),
    @XmlEnumValue("Cambodia")
    CAMBODIA("Cambodia"),
    @XmlEnumValue("Kiribati")
    KIRIBATI("Kiribati"),
    @XmlEnumValue("Comoros")
    COMOROS("Comoros"),
    @XmlEnumValue("Saint Kitts and Nevis")
    SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis"),
    @XmlEnumValue("Democratic People's Republic of Korea")
    DEMOCRATIC_PEOPLE_S_REPUBLIC_OF_KOREA("Democratic People's Republic of Korea"),
    @XmlEnumValue("Republic of Korea")
    REPUBLIC_OF_KOREA("Republic of Korea"),
    @XmlEnumValue("Kuwait")
    KUWAIT("Kuwait"),
    @XmlEnumValue("Cayman Islands")
    CAYMAN_ISLANDS("Cayman Islands"),
    @XmlEnumValue("Kazakhstan")
    KAZAKHSTAN("Kazakhstan"),
    @XmlEnumValue("Lao People's Democratic Republic")
    LAO_PEOPLE_S_DEMOCRATIC_REPUBLIC("Lao People's Democratic Republic"),
    @XmlEnumValue("Lebanon")
    LEBANON("Lebanon"),
    @XmlEnumValue("Saint Lucia")
    SAINT_LUCIA("Saint Lucia"),
    @XmlEnumValue("Liechtenstein")
    LIECHTENSTEIN("Liechtenstein"),
    @XmlEnumValue("Sri Lanka")
    SRI_LANKA("Sri Lanka"),
    @XmlEnumValue("Liberia")
    LIBERIA("Liberia"),
    @XmlEnumValue("Lesotho")
    LESOTHO("Lesotho"),
    @XmlEnumValue("Lithuania")
    LITHUANIA("Lithuania"),
    @XmlEnumValue("Luxembourg")
    LUXEMBOURG("Luxembourg"),
    @XmlEnumValue("Latvia")
    LATVIA("Latvia"),
    @XmlEnumValue("Libya")
    LIBYA("Libya"),
    @XmlEnumValue("Morocco")
    MOROCCO("Morocco"),
    @XmlEnumValue("Monaco")
    MONACO("Monaco"),
    @XmlEnumValue("Moldova")
    MOLDOVA("Moldova"),
    @XmlEnumValue("Montenegro")
    MONTENEGRO("Montenegro"),
    @XmlEnumValue("Saint Martin (French part)")
    SAINT_MARTIN_FRENCH_PART("Saint Martin (French part)"),
    @XmlEnumValue("Madagascar")
    MADAGASCAR("Madagascar"),
    @XmlEnumValue("Marshall Islands")
    MARSHALL_ISLANDS("Marshall Islands"),
    @XmlEnumValue("The Former Yugoslav Republic of Macedonia")
    THE_FORMER_YUGOSLAV_REPUBLIC_OF_MACEDONIA("The Former Yugoslav Republic of Macedonia"),
    @XmlEnumValue("Mali")
    MALI("Mali"),
    @XmlEnumValue("Myanmar")
    MYANMAR("Myanmar"),
    @XmlEnumValue("Mongolia")
    MONGOLIA("Mongolia"),
    @XmlEnumValue("Macao")
    MACAO("Macao"),
    @XmlEnumValue("Northern Mariana Islands")
    NORTHERN_MARIANA_ISLANDS("Northern Mariana Islands"),
    @XmlEnumValue("Martinique")
    MARTINIQUE("Martinique"),
    @XmlEnumValue("Mauritania")
    MAURITANIA("Mauritania"),
    @XmlEnumValue("Montserrat")
    MONTSERRAT("Montserrat"),
    @XmlEnumValue("Malta")
    MALTA("Malta"),
    @XmlEnumValue("Mauritius")
    MAURITIUS("Mauritius"),
    @XmlEnumValue("Maldives")
    MALDIVES("Maldives"),
    @XmlEnumValue("Malawi")
    MALAWI("Malawi"),
    @XmlEnumValue("Mexico")
    MEXICO("Mexico"),
    @XmlEnumValue("Malaysia")
    MALAYSIA("Malaysia"),
    @XmlEnumValue("Mozambique")
    MOZAMBIQUE("Mozambique"),
    @XmlEnumValue("Namibia")
    NAMIBIA("Namibia"),
    @XmlEnumValue("New Caledonia")
    NEW_CALEDONIA("New Caledonia"),
    @XmlEnumValue("Niger")
    NIGER("Niger"),
    @XmlEnumValue("Norfolk Island")
    NORFOLK_ISLAND("Norfolk Island"),
    @XmlEnumValue("Nigeria")
    NIGERIA("Nigeria"),
    @XmlEnumValue("Nicaragua")
    NICARAGUA("Nicaragua"),
    @XmlEnumValue("Netherlands")
    NETHERLANDS("Netherlands"),
    @XmlEnumValue("Norway")
    NORWAY("Norway"),
    @XmlEnumValue("Nepal")
    NEPAL("Nepal"),
    @XmlEnumValue("Nauru")
    NAURU("Nauru"),
    @XmlEnumValue("Niue")
    NIUE("Niue"),
    @XmlEnumValue("New Zealand")
    NEW_ZEALAND("New Zealand"),
    @XmlEnumValue("Oman")
    OMAN("Oman"),
    @XmlEnumValue("Panama")
    PANAMA("Panama"),
    @XmlEnumValue("Peru")
    PERU("Peru"),
    @XmlEnumValue("French Polynesia")
    FRENCH_POLYNESIA("French Polynesia"),
    @XmlEnumValue("Papua New Guinea")
    PAPUA_NEW_GUINEA("Papua New Guinea"),
    @XmlEnumValue("Philippines")
    PHILIPPINES("Philippines"),
    @XmlEnumValue("Pakistan")
    PAKISTAN("Pakistan"),
    @XmlEnumValue("Poland")
    POLAND("Poland"),
    @XmlEnumValue("Saint Pierre and Miquelon")
    SAINT_PIERRE_AND_MIQUELON("Saint Pierre and Miquelon"),
    @XmlEnumValue("Pitcairn")
    PITCAIRN("Pitcairn"),
    @XmlEnumValue("Puerto Rico")
    PUERTO_RICO("Puerto Rico"),
    @XmlEnumValue("State of Palestine")
    STATE_OF_PALESTINE("State of Palestine"),
    @XmlEnumValue("Portugal")
    PORTUGAL("Portugal"),
    @XmlEnumValue("Palau")
    PALAU("Palau"),
    @XmlEnumValue("Paraguay")
    PARAGUAY("Paraguay"),
    @XmlEnumValue("Qatar")
    QATAR("Qatar"),
    @XmlEnumValue("R\u00e9union")
    RÉUNION("R\u00e9union"),
    @XmlEnumValue("Romania")
    ROMANIA("Romania"),
    @XmlEnumValue("Serbia")
    SERBIA("Serbia"),
    @XmlEnumValue("Russian Federation")
    RUSSIAN_FEDERATION("Russian Federation"),
    @XmlEnumValue("Rwanda")
    RWANDA("Rwanda"),
    @XmlEnumValue("Saudi Arabia")
    SAUDI_ARABIA("Saudi Arabia"),
    @XmlEnumValue("Solomon Islands")
    SOLOMON_ISLANDS("Solomon Islands"),
    @XmlEnumValue("Seychelles")
    SEYCHELLES("Seychelles"),
    @XmlEnumValue("Sudan")
    SUDAN("Sudan"),
    @XmlEnumValue("Sweden")
    SWEDEN("Sweden"),
    @XmlEnumValue("Singapore")
    SINGAPORE("Singapore"),
    @XmlEnumValue("Saint Helena, Ascension and Tristan da Cunha")
    SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA("Saint Helena, Ascension and Tristan da Cunha"),
    @XmlEnumValue("Slovenia")
    SLOVENIA("Slovenia"),
    @XmlEnumValue("Svalbard and Jan Mayen")
    SVALBARD_AND_JAN_MAYEN("Svalbard and Jan Mayen"),
    @XmlEnumValue("Slovakia")
    SLOVAKIA("Slovakia"),
    @XmlEnumValue("Sierra Leone")
    SIERRA_LEONE("Sierra Leone"),
    @XmlEnumValue("San Marino")
    SAN_MARINO("San Marino"),
    @XmlEnumValue("Senegal")
    SENEGAL("Senegal"),
    @XmlEnumValue("Somalia")
    SOMALIA("Somalia"),
    @XmlEnumValue("Suriname")
    SURINAME("Suriname"),
    @XmlEnumValue("South Sudan")
    SOUTH_SUDAN("South Sudan"),
    @XmlEnumValue("Sao Tome and Principe")
    SAO_TOME_AND_PRINCIPE("Sao Tome and Principe"),
    @XmlEnumValue("El Salvador")
    EL_SALVADOR("El Salvador"),
    @XmlEnumValue("Sint Maarten (Dutch part)")
    SINT_MAARTEN_DUTCH_PART("Sint Maarten (Dutch part)"),
    @XmlEnumValue("Syrian Arab Republic")
    SYRIAN_ARAB_REPUBLIC("Syrian Arab Republic"),
    @XmlEnumValue("Swaziland")
    SWAZILAND("Swaziland"),
    @XmlEnumValue("Tristan da Cunha")
    TRISTAN_DA_CUNHA("Tristan da Cunha"),
    @XmlEnumValue("Turks and Caicos Islands")
    TURKS_AND_CAICOS_ISLANDS("Turks and Caicos Islands"),
    @XmlEnumValue("Chad")
    CHAD("Chad"),
    @XmlEnumValue("French Southern Territories")
    FRENCH_SOUTHERN_TERRITORIES("French Southern Territories"),
    @XmlEnumValue("Togo")
    TOGO("Togo"),
    @XmlEnumValue("Thailand")
    THAILAND("Thailand"),
    @XmlEnumValue("Tajikistan")
    TAJIKISTAN("Tajikistan"),
    @XmlEnumValue("Tokelau")
    TOKELAU("Tokelau"),
    @XmlEnumValue("Timor-Leste")
    TIMOR_LESTE("Timor-Leste"),
    @XmlEnumValue("Turkmenistan")
    TURKMENISTAN("Turkmenistan"),
    @XmlEnumValue("Tunisia")
    TUNISIA("Tunisia"),
    @XmlEnumValue("Tonga")
    TONGA("Tonga"),
    @XmlEnumValue("Turkey")
    TURKEY("Turkey"),
    @XmlEnumValue("Trinidad and Tobago")
    TRINIDAD_AND_TOBAGO("Trinidad and Tobago"),
    @XmlEnumValue("Tuvalu")
    TUVALU("Tuvalu"),
    @XmlEnumValue("Taiwan, Province of China")
    TAIWAN_PROVINCE_OF_CHINA("Taiwan, Province of China"),
    @XmlEnumValue("United Republic of Tanzania")
    UNITED_REPUBLIC_OF_TANZANIA("United Republic of Tanzania"),
    @XmlEnumValue("Ukraine")
    UKRAINE("Ukraine"),
    @XmlEnumValue("Uganda")
    UGANDA("Uganda"),
    @XmlEnumValue("United States Minor Outlying Islands")
    UNITED_STATES_MINOR_OUTLYING_ISLANDS("United States Minor Outlying Islands"),
    @XmlEnumValue("United States")
    UNITED_STATES("United States"),
    @XmlEnumValue("Uruguay")
    URUGUAY("Uruguay"),
    @XmlEnumValue("Uzbekistan")
    UZBEKISTAN("Uzbekistan"),
    @XmlEnumValue("Holy See (Vatican City State)")
    HOLY_SEE_VATICAN_CITY_STATE("Holy See (Vatican City State)"),
    @XmlEnumValue("Saint Vincent and the Grenadines")
    SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent and the Grenadines"),
    @XmlEnumValue("Venezuela")
    VENEZUELA("Venezuela"),
    @XmlEnumValue("British Virgin Islands")
    BRITISH_VIRGIN_ISLANDS("British Virgin Islands"),
    @XmlEnumValue("U.S. Virgin Islands")
    U_S_VIRGIN_ISLANDS("U.S. Virgin Islands"),
    @XmlEnumValue("Viet Nam")
    VIET_NAM("Viet Nam"),
    @XmlEnumValue("Vanuatu")
    VANUATU("Vanuatu"),
    @XmlEnumValue("Wallis and Futuna")
    WALLIS_AND_FUTUNA("Wallis and Futuna"),
    @XmlEnumValue("Samoa")
    SAMOA("Samoa"),
    @XmlEnumValue("Yemen")
    YEMEN("Yemen"),
    @XmlEnumValue("Mayotte")
    MAYOTTE("Mayotte"),
    @XmlEnumValue("South Africa")
    SOUTH_AFRICA("South Africa"),
    @XmlEnumValue("Zambia")
    ZAMBIA("Zambia"),
    @XmlEnumValue("Zimbabwe")
    ZIMBABWE("Zimbabwe"),
    @XmlEnumValue("World")
    WORLD("World"),
    @XmlEnumValue("Africa")
    AFRICA("Africa"),
    @XmlEnumValue("North America")
    NORTH_AMERICA("North America"),
    @XmlEnumValue("South America")
    SOUTH_AMERICA("South America"),
    @XmlEnumValue("Oceania")
    OCEANIA("Oceania"),
    @XmlEnumValue("Western Africa")
    WESTERN_AFRICA("Western Africa"),
    @XmlEnumValue("Central America")
    CENTRAL_AMERICA("Central America"),
    @XmlEnumValue("Eastern Africa")
    EASTERN_AFRICA("Eastern Africa"),
    @XmlEnumValue("Northern Africa")
    NORTHERN_AFRICA("Northern Africa"),
    @XmlEnumValue("Middle Africa")
    MIDDLE_AFRICA("Middle Africa"),
    @XmlEnumValue("Southern Africa")
    SOUTHERN_AFRICA("Southern Africa"),
    @XmlEnumValue("Americas")
    AMERICAS("Americas"),
    @XmlEnumValue("Northern America")
    NORTHERN_AMERICA("Northern America"),
    @XmlEnumValue("Caribbean")
    CARIBBEAN("Caribbean"),
    @XmlEnumValue("Eastern Asia")
    EASTERN_ASIA("Eastern Asia"),
    @XmlEnumValue("Southern Asia")
    SOUTHERN_ASIA("Southern Asia"),
    @XmlEnumValue("South-Eastern Asia")
    SOUTH_EASTERN_ASIA("South-Eastern Asia"),
    @XmlEnumValue("Southern Europe")
    SOUTHERN_EUROPE("Southern Europe"),
    @XmlEnumValue("Australia and New Zealand")
    AUSTRALIA_AND_NEW_ZEALAND("Australia and New Zealand"),
    @XmlEnumValue("Melanesia")
    MELANESIA("Melanesia"),
    @XmlEnumValue("Micronesia")
    MICRONESIA("Micronesia"),
    @XmlEnumValue("Polynesia")
    POLYNESIA("Polynesia"),
    @XmlEnumValue("Asia")
    ASIA("Asia"),
    @XmlEnumValue("Central Asia")
    CENTRAL_ASIA("Central Asia"),
    @XmlEnumValue("Western Asia")
    WESTERN_ASIA("Western Asia"),
    @XmlEnumValue("Europe")
    EUROPE("Europe"),
    @XmlEnumValue("Eastern Europe")
    EASTERN_EUROPE("Eastern Europe"),
    @XmlEnumValue("Northern Europe")
    NORTHERN_EUROPE("Northern Europe"),
    @XmlEnumValue("Western Europe")
    WESTERN_EUROPE("Western Europe"),
    @XmlEnumValue("Latin America and the Caribbean")
    LATIN_AMERICA_AND_THE_CARIBBEAN("Latin America and the Caribbean");
    private final String value;

    RegionNameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RegionNameType fromValue(String v) {
        for (RegionNameType c: RegionNameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
