//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups together information on the image resolution
 * 
 * <p>Java class for resolutionInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resolutionInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sizeWidth" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="sizeHeight" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="resolutionStandard" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *               &lt;enumeration value="VGA"/>
 *               &lt;enumeration value="HD.720"/>
 *               &lt;enumeration value="HD.1080"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resolutionInfoType", propOrder = {
    "sizeWidth",
    "sizeHeight",
    "resolutionStandard"
})
public class ResolutionInfoType {

    protected Integer sizeWidth;
    protected Integer sizeHeight;
    protected String resolutionStandard;

    /**
     * Gets the value of the sizeWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSizeWidth() {
        return sizeWidth;
    }

    /**
     * Sets the value of the sizeWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSizeWidth(Integer value) {
        this.sizeWidth = value;
    }

    /**
     * Gets the value of the sizeHeight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSizeHeight() {
        return sizeHeight;
    }

    /**
     * Sets the value of the sizeHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSizeHeight(Integer value) {
        this.sizeHeight = value;
    }

    /**
     * Gets the value of the resolutionStandard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResolutionStandard() {
        return resolutionStandard;
    }

    /**
     * Sets the value of the resolutionStandard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResolutionStandard(String value) {
        this.resolutionStandard = value;
    }

}
