//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 07:29:31 PM EET 
//


package gr.ilsp.metashare;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups together all information required for the description of language resources
 * 
 * <p>Java class for resourceInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resourceInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}identificationInfo"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}distributionInfo"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}resourceCreationInfo" minOccurs="0"/>
 *         &lt;element name="contactPerson" type="{http://www.ilsp.gr/META-XMLSchema}personInfoType" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}metadataInfo"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}resourceDocumentationInfo" minOccurs="0"/>
 *         &lt;element name="resourceComponentType">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}corpusInfo"/>
 *                   &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}languageDescriptionInfo"/>
 *                   &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}lexicalConceptualResourceInfo"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="resourceInfo")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resourceInfoType", propOrder = {
    "identificationInfo",
    "distributionInfo",
    "resourceCreationInfo",
    "contactPerson",
    "metadataInfo",
    "resourceDocumentationInfo",
    "resourceComponentType"
})
public class ResourceInfoType {

    @XmlElement(required = true)
    protected IdentificationInfoType identificationInfo;
    @XmlElement(required = true)
    protected DistributionInfo distributionInfo;
    protected ResourceCreationInfoType resourceCreationInfo;
    @XmlElement(required = true)
    protected List<PersonInfoType> contactPerson;
    @XmlElement(required = true)
    protected MetadataInfoType metadataInfo;
    protected ResourceDocumentationInfoType resourceDocumentationInfo;
    @XmlElement(required = true)
    protected ResourceInfoType.ResourceComponentType resourceComponentType;

    /**
     * Groups together information needed to identify the resource
     * 
     * @return
     *     possible object is
     *     {@link IdentificationInfoType }
     *     
     */
    public IdentificationInfoType getIdentificationInfo() {
        return identificationInfo;
    }

    /**
     * Sets the value of the identificationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificationInfoType }
     *     
     */
    public void setIdentificationInfo(IdentificationInfoType value) {
        this.identificationInfo = value;
    }

    /**
     * Groups information on the distribution of the resource
     * 
     * @return
     *     possible object is
     *     {@link DistributionInfo }
     *     
     */
    public DistributionInfo getDistributionInfo() {
        return distributionInfo;
    }

    /**
     * Sets the value of the distributionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistributionInfo }
     *     
     */
    public void setDistributionInfo(DistributionInfo value) {
        this.distributionInfo = value;
    }

    /**
     * Groups information on the creation procedure of a resource
     * 
     * @return
     *     possible object is
     *     {@link ResourceCreationInfoType }
     *     
     */
    public ResourceCreationInfoType getResourceCreationInfo() {
        return resourceCreationInfo;
    }

    /**
     * Sets the value of the resourceCreationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceCreationInfoType }
     *     
     */
    public void setResourceCreationInfo(ResourceCreationInfoType value) {
        this.resourceCreationInfo = value;
    }

    /**
     * Gets the value of the contactPerson property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactPerson property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactPerson().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonInfoType }
     * 
     * 
     */
    public List<PersonInfoType> getContactPerson() {
        if (contactPerson == null) {
            contactPerson = new ArrayList<PersonInfoType>();
        }
        return this.contactPerson;
    }

    /**
     * Groups information on the metadata record itself
     * 
     * @return
     *     possible object is
     *     {@link MetadataInfoType }
     *     
     */
    public MetadataInfoType getMetadataInfo() {
        return metadataInfo;
    }

    /**
     * Sets the value of the metadataInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetadataInfoType }
     *     
     */
    public void setMetadataInfo(MetadataInfoType value) {
        this.metadataInfo = value;
    }

    /**
     * Groups together information on any document describing the resource
     * 
     * @return
     *     possible object is
     *     {@link ResourceDocumentationInfoType }
     *     
     */
    public ResourceDocumentationInfoType getResourceDocumentationInfo() {
        return resourceDocumentationInfo;
    }

    /**
     * Sets the value of the resourceDocumentationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceDocumentationInfoType }
     *     
     */
    public void setResourceDocumentationInfo(ResourceDocumentationInfoType value) {
        this.resourceDocumentationInfo = value;
    }

    /**
     * Gets the value of the resourceComponentType property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceInfoType.ResourceComponentType }
     *     
     */
    public ResourceInfoType.ResourceComponentType getResourceComponentType() {
        return resourceComponentType;
    }

    /**
     * Sets the value of the resourceComponentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceInfoType.ResourceComponentType }
     *     
     */
    public void setResourceComponentType(ResourceInfoType.ResourceComponentType value) {
        this.resourceComponentType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}corpusInfo"/>
     *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}languageDescriptionInfo"/>
     *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}lexicalConceptualResourceInfo"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "corpusInfo",
        "languageDescriptionInfo",
        "lexicalConceptualResourceInfo"
    })
    public static class ResourceComponentType {

        protected CorpusInfoType corpusInfo;
        protected LanguageDescriptionInfoType languageDescriptionInfo;
        protected LexicalConceptualResourceInfoType lexicalConceptualResourceInfo;

        /**
         * Gets the value of the corpusInfo property.
         * 
         * @return
         *     possible object is
         *     {@link CorpusInfoType }
         *     
         */
        public CorpusInfoType getCorpusInfo() {
            return corpusInfo;
        }

        /**
         * Sets the value of the corpusInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link CorpusInfoType }
         *     
         */
        public void setCorpusInfo(CorpusInfoType value) {
            this.corpusInfo = value;
        }

        /**
         * Gets the value of the languageDescriptionInfo property.
         * 
         * @return
         *     possible object is
         *     {@link LanguageDescriptionInfoType }
         *     
         */
        public LanguageDescriptionInfoType getLanguageDescriptionInfo() {
            return languageDescriptionInfo;
        }

        /**
         * Sets the value of the languageDescriptionInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link LanguageDescriptionInfoType }
         *     
         */
        public void setLanguageDescriptionInfo(LanguageDescriptionInfoType value) {
            this.languageDescriptionInfo = value;
        }

        /**
         * Gets the value of the lexicalConceptualResourceInfo property.
         * 
         * @return
         *     possible object is
         *     {@link LexicalConceptualResourceInfoType }
         *     
         */
        public LexicalConceptualResourceInfoType getLexicalConceptualResourceInfo() {
            return lexicalConceptualResourceInfo;
        }

        /**
         * Sets the value of the lexicalConceptualResourceInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link LexicalConceptualResourceInfoType }
         *     
         */
        public void setLexicalConceptualResourceInfo(LexicalConceptualResourceInfoType value) {
            this.lexicalConceptualResourceInfo = value;
        }

    }

}
