//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Groups information on the creation procedure of a resource
 * 
 * <p>Java class for resourceCreationInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resourceCreationInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resourceCreator" type="{http://www.ilsp.gr/META-XMLSchema}actorInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="fundingProject" type="{http://www.ilsp.gr/META-XMLSchema}projectInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="creationStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="creationEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resourceCreationInfoType", propOrder = {
    "resourceCreator",
    "fundingProject",
    "creationStartDate",
    "creationEndDate"
})
public class ResourceCreationInfoType {

    protected List<ActorInfoType> resourceCreator;
    protected List<ProjectInfoType> fundingProject;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar creationStartDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar creationEndDate;

    /**
     * Gets the value of the resourceCreator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceCreator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceCreator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActorInfoType }
     * 
     * 
     */
    public List<ActorInfoType> getResourceCreator() {
        if (resourceCreator == null) {
            resourceCreator = new ArrayList<ActorInfoType>();
        }
        return this.resourceCreator;
    }

    /**
     * Gets the value of the fundingProject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fundingProject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFundingProject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProjectInfoType }
     * 
     * 
     */
    public List<ProjectInfoType> getFundingProject() {
        if (fundingProject == null) {
            fundingProject = new ArrayList<ProjectInfoType>();
        }
        return this.fundingProject;
    }

    /**
     * Gets the value of the creationStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationStartDate() {
        return creationStartDate;
    }

    /**
     * Sets the value of the creationStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationStartDate(XMLGregorianCalendar value) {
        this.creationStartDate = value;
    }

    /**
     * Gets the value of the creationEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationEndDate() {
        return creationEndDate;
    }

    /**
     * Sets the value of the creationEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationEndDate(XMLGregorianCalendar value) {
        this.creationEndDate = value;
    }

}
