//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups together information on the setting of the audio and/or video part of a resource
 * 
 * <p>Java class for settingInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="settingInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="naturality" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="natural"/>
 *               &lt;enumeration value="planned"/>
 *               &lt;enumeration value="semiPlanned"/>
 *               &lt;enumeration value="readSpeech"/>
 *               &lt;enumeration value="spontaneous"/>
 *               &lt;enumeration value="elicited"/>
 *               &lt;enumeration value="assisted"/>
 *               &lt;enumeration value="prompted"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="conversationalType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="monologue"/>
 *               &lt;enumeration value="dialogue"/>
 *               &lt;enumeration value="multilogue"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="scenarioType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="frogStory"/>
 *               &lt;enumeration value="mapTask"/>
 *               &lt;enumeration value="onlineEducationalGame"/>
 *               &lt;enumeration value="pearStory"/>
 *               &lt;enumeration value="rolePlay"/>
 *               &lt;enumeration value="wordGame"/>
 *               &lt;enumeration value="wizardOfOz"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="audience" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="no"/>
 *               &lt;enumeration value="few"/>
 *               &lt;enumeration value="some"/>
 *               &lt;enumeration value="largePublic"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="interactivity" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;enumeration value="interactive"/>
 *               &lt;enumeration value="nonInteractive"/>
 *               &lt;enumeration value="semiInteractive"/>
 *               &lt;enumeration value="overlapping"/>
 *               &lt;enumeration value="other"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="interaction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "settingInfoType", propOrder = {
    "naturality",
    "conversationalType",
    "scenarioType",
    "audience",
    "interactivity",
    "interaction"
})
public class SettingInfoType {

    protected String naturality;
    protected String conversationalType;
    protected String scenarioType;
    protected String audience;
    protected String interactivity;
    protected String interaction;

    /**
     * Gets the value of the naturality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaturality() {
        return naturality;
    }

    /**
     * Sets the value of the naturality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaturality(String value) {
        this.naturality = value;
    }

    /**
     * Gets the value of the conversationalType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConversationalType() {
        return conversationalType;
    }

    /**
     * Sets the value of the conversationalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConversationalType(String value) {
        this.conversationalType = value;
    }

    /**
     * Gets the value of the scenarioType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScenarioType() {
        return scenarioType;
    }

    /**
     * Sets the value of the scenarioType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScenarioType(String value) {
        this.scenarioType = value;
    }

    /**
     * Gets the value of the audience property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAudience() {
        return audience;
    }

    /**
     * Sets the value of the audience property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAudience(String value) {
        this.audience = value;
    }

    /**
     * Gets the value of the interactivity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInteractivity() {
        return interactivity;
    }

    /**
     * Sets the value of the interactivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInteractivity(String value) {
        this.interactivity = value;
    }

    /**
     * Gets the value of the interaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInteraction() {
        return interaction;
    }

    /**
     * Sets the value of the interaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInteraction(String value) {
        this.interaction = value;
    }

}
