//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups together information on text type/genre of the resource
 * 
 * <p>Java class for textClassificationInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="textClassificationInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}textGenre" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}textType" minOccurs="0"/>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}conformanceToClassificationScheme" minOccurs="0"/>
 *         &lt;element name="sizePerTextClassification" type="{http://www.ilsp.gr/META-XMLSchema}sizeInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "textClassificationInfoType", propOrder = {
    "textGenre",
    "textType",
    "conformanceToClassificationScheme",
    "sizePerTextClassification"
})
public class TextClassificationInfoType {

    protected String textGenre;
    protected String textType;
    protected String conformanceToClassificationScheme;
    protected SizeInfoType sizePerTextClassification;

    /**
     * Gets the value of the textGenre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextGenre() {
        return textGenre;
    }

    /**
     * Sets the value of the textGenre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextGenre(String value) {
        this.textGenre = value;
    }

    /**
     * Gets the value of the textType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextType() {
        return textType;
    }

    /**
     * Sets the value of the textType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextType(String value) {
        this.textType = value;
    }

    /**
     * Specifies the external classification schemes
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConformanceToClassificationScheme() {
        return conformanceToClassificationScheme;
    }

    /**
     * Sets the value of the conformanceToClassificationScheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConformanceToClassificationScheme(String value) {
        this.conformanceToClassificationScheme = value;
    }

    /**
     * Gets the value of the sizePerTextClassification property.
     * 
     * @return
     *     possible object is
     *     {@link SizeInfoType }
     *     
     */
    public SizeInfoType getSizePerTextClassification() {
        return sizePerTextClassification;
    }

    /**
     * Sets the value of the sizePerTextClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link SizeInfoType }
     *     
     */
    public void setSizePerTextClassification(SizeInfoType value) {
        this.sizePerTextClassification = value;
    }

}
