//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Groups information on the text format(s) of a resource
 * 
 * <p>Java class for textFormatInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="textFormatInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ilsp.gr/META-XMLSchema}mimeType"/>
 *         &lt;element name="sizePerTextFormat" type="{http://www.ilsp.gr/META-XMLSchema}sizeInfoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "textFormatInfoType", propOrder = {
    "mimeType",
    "sizePerTextFormat"
})
public class TextFormatInfoType {

    @XmlElement(required = true)
    protected String mimeType;
    protected SizeInfoType sizePerTextFormat;

    /**
     * Gets the value of the mimeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMimeType() {
        return mimeType;
    }

    /**
     * Sets the value of the mimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMimeType(String value) {
        this.mimeType = value;
    }

    /**
     * Gets the value of the sizePerTextFormat property.
     * 
     * @return
     *     possible object is
     *     {@link SizeInfoType }
     *     
     */
    public SizeInfoType getSizePerTextFormat() {
        return sizePerTextFormat;
    }

    /**
     * Sets the value of the sizePerTextFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link SizeInfoType }
     *     
     */
    public void setSizePerTextFormat(SizeInfoType value) {
        this.sizePerTextFormat = value;
    }

}
