//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.15 at 01:12:36 PM EET 
//


package gr.ilsp.metashare;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for variantNameType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="variantNameType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Late Middle French (to 1606)"/>
 *     &lt;enumeration value="Early Modern French"/>
 *     &lt;enumeration value="Traditional German orthography"/>
 *     &lt;enumeration value="'Academic' ('governmental') variant of Belarusian as codified in 1959"/>
 *     &lt;enumeration value="Standardized Resian orthography"/>
 *     &lt;enumeration value="German orthography of 1996"/>
 *     &lt;enumeration value="Aluku dialect; Boni dialect"/>
 *     &lt;enumeration value="Eastern Armenian"/>
 *     &lt;enumeration value="Western Armenian"/>
 *     &lt;enumeration value="Unified Turkic Latin Alphabet (Historical)"/>
 *     &lt;enumeration value="The Balanka dialect of Anii"/>
 *     &lt;enumeration value="The Barlavento dialect group of Kabuverdianu"/>
 *     &lt;enumeration value="Buddhist Hybrid Sanskrit"/>
 *     &lt;enumeration value="Biscayan dialect of Basque"/>
 *     &lt;enumeration value="The San Giorgio dialect of Resian; The Bila dialect of Resian"/>
 *     &lt;enumeration value="Slovene in Bohorič alphabet"/>
 *     &lt;enumeration value="Boontling"/>
 *     &lt;enumeration value="Slovene in Dajnko alphabet"/>
 *     &lt;enumeration value="Serbian with Ekavian pronunciation"/>
 *     &lt;enumeration value="Early Modern English (1500-1700)"/>
 *     &lt;enumeration value="Hepburn romanization"/>
 *     &lt;enumeration value="Norwegian in Høgnorsk (High Norwegian) orthography"/>
 *     &lt;enumeration value="Serbian with Ijekavian pronunciation"/>
 *     &lt;enumeration value="Epic Sanskrit"/>
 *     &lt;enumeration value="Jauer dialect of Romansh"/>
 *     &lt;enumeration value="Jyutping Cantonese Romanization"/>
 *     &lt;enumeration value="Common Cornish orthography of Revived Cornish"/>
 *     &lt;enumeration value="Standard Cornish orthography of Revived Cornish; Kernowek Standard"/>
 *     &lt;enumeration value="Classical Sanskrit"/>
 *     &lt;enumeration value="The Lipovaz dialect of Resian; The Lipovec dialect of Resian"/>
 *     &lt;enumeration value="Post-1917 Russian orthography"/>
 *     &lt;enumeration value="Slovene in Metelko alphabet"/>
 *     &lt;enumeration value="Monotonic Greek"/>
 *     &lt;enumeration value="Ndyuka dialect; Aukan dialect"/>
 *     &lt;enumeration value="Natisone dialect; Nadiza dialect"/>
 *     &lt;enumeration value="The Gniva dialect of Resian; The Njiva dialect of Resian"/>
 *     &lt;enumeration value="Volapük nulik; Volapük perevidöl; Volapük nulädik; de Jong's Volapük; New Volapük; Revised Volapük; Modern Volapük"/>
 *     &lt;enumeration value="The Oseacco dialect of Resian; The Osojane dialect of Resian"/>
 *     &lt;enumeration value="Pamaka dialect"/>
 *     &lt;enumeration value="Petrine orthography"/>
 *     &lt;enumeration value="Pinyin romanization"/>
 *     &lt;enumeration value="Polytonic Greek"/>
 *     &lt;enumeration value="Puter idiom of Romansh"/>
 *     &lt;enumeration value="Volapük rigik; Schleyer's Volapük; Original Volapük; Classic Volapük"/>
 *     &lt;enumeration value="Resian; Resianic; Rezijan"/>
 *     &lt;enumeration value="Rumantsch Grischun"/>
 *     &lt;enumeration value="Scottish Standard English"/>
 *     &lt;enumeration value="Scouse"/>
 *     &lt;enumeration value="The Stolvizza dialect of Resian; The Solbica dialect of Resian"/>
 *     &lt;enumeration value="The Sotavento dialect group of Kabuverdianu"/>
 *     &lt;enumeration value="Surmiran idiom of Romansh"/>
 *     &lt;enumeration value="Sursilvan idiom of Romansh"/>
 *     &lt;enumeration value="Sutsilvan idiom of Romansh"/>
 *     &lt;enumeration value="Belarusian in Taraskievica orthography"/>
 *     &lt;enumeration value="Unified Cornish orthography of Revived Cornish"/>
 *     &lt;enumeration value="Unified Cornish Revised orthography of Revived Cornish"/>
 *     &lt;enumeration value="Ulster dialect of Scots"/>
 *     &lt;enumeration value="Unifon phonetic alphabet"/>
 *     &lt;enumeration value="Vedic Sanskrit"/>
 *     &lt;enumeration value="Valencian"/>
 *     &lt;enumeration value="Vallader idiom of Romansh"/>
 *     &lt;enumeration value="Wade-Giles romanization"/>
 *     &lt;enumeration value="ALA-LC Romanization, 1997 edition"/>
 *     &lt;enumeration value="International Phonetic Alphabet"/>
 *     &lt;enumeration value="Uralic Phonetic Alphabet"/>
 *     &lt;enumeration value="X-SAMPA transcription"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "variantNameType")
@XmlEnum
public enum VariantNameType {

    @XmlEnumValue("Late Middle French (to 1606)")
    LATE_MIDDLE_FRENCH_TO_1606("Late Middle French (to 1606)"),
    @XmlEnumValue("Early Modern French")
    EARLY_MODERN_FRENCH("Early Modern French"),
    @XmlEnumValue("Traditional German orthography")
    TRADITIONAL_GERMAN_ORTHOGRAPHY("Traditional German orthography"),
    @XmlEnumValue("'Academic' ('governmental') variant of Belarusian as codified in 1959")
    ACADEMIC_GOVERNMENTAL_VARIANT_OF_BELARUSIAN_AS_CODIFIED_IN_1959("'Academic' ('governmental') variant of Belarusian as codified in 1959"),
    @XmlEnumValue("Standardized Resian orthography")
    STANDARDIZED_RESIAN_ORTHOGRAPHY("Standardized Resian orthography"),
    @XmlEnumValue("German orthography of 1996")
    GERMAN_ORTHOGRAPHY_OF_1996("German orthography of 1996"),
    @XmlEnumValue("Aluku dialect; Boni dialect")
    ALUKU_DIALECT_BONI_DIALECT("Aluku dialect; Boni dialect"),
    @XmlEnumValue("Eastern Armenian")
    EASTERN_ARMENIAN("Eastern Armenian"),
    @XmlEnumValue("Western Armenian")
    WESTERN_ARMENIAN("Western Armenian"),
    @XmlEnumValue("Unified Turkic Latin Alphabet (Historical)")
    UNIFIED_TURKIC_LATIN_ALPHABET_HISTORICAL("Unified Turkic Latin Alphabet (Historical)"),
    @XmlEnumValue("The Balanka dialect of Anii")
    THE_BALANKA_DIALECT_OF_ANII("The Balanka dialect of Anii"),
    @XmlEnumValue("The Barlavento dialect group of Kabuverdianu")
    THE_BARLAVENTO_DIALECT_GROUP_OF_KABUVERDIANU("The Barlavento dialect group of Kabuverdianu"),
    @XmlEnumValue("Buddhist Hybrid Sanskrit")
    BUDDHIST_HYBRID_SANSKRIT("Buddhist Hybrid Sanskrit"),
    @XmlEnumValue("Biscayan dialect of Basque")
    BISCAYAN_DIALECT_OF_BASQUE("Biscayan dialect of Basque"),
    @XmlEnumValue("The San Giorgio dialect of Resian; The Bila dialect of Resian")
    THE_SAN_GIORGIO_DIALECT_OF_RESIAN_THE_BILA_DIALECT_OF_RESIAN("The San Giorgio dialect of Resian; The Bila dialect of Resian"),
    @XmlEnumValue("Slovene in Bohori\u010d alphabet")
    SLOVENE_IN_BOHORIČ_ALPHABET("Slovene in Bohori\u010d alphabet"),
    @XmlEnumValue("Boontling")
    BOONTLING("Boontling"),
    @XmlEnumValue("Slovene in Dajnko alphabet")
    SLOVENE_IN_DAJNKO_ALPHABET("Slovene in Dajnko alphabet"),
    @XmlEnumValue("Serbian with Ekavian pronunciation")
    SERBIAN_WITH_EKAVIAN_PRONUNCIATION("Serbian with Ekavian pronunciation"),
    @XmlEnumValue("Early Modern English (1500-1700)")
    EARLY_MODERN_ENGLISH_1500_1700("Early Modern English (1500-1700)"),
    @XmlEnumValue("Hepburn romanization")
    HEPBURN_ROMANIZATION("Hepburn romanization"),
    @XmlEnumValue("Norwegian in H\u00f8gnorsk (High Norwegian) orthography")
    NORWEGIAN_IN_HØGNORSK_HIGH_NORWEGIAN_ORTHOGRAPHY("Norwegian in H\u00f8gnorsk (High Norwegian) orthography"),
    @XmlEnumValue("Serbian with Ijekavian pronunciation")
    SERBIAN_WITH_IJEKAVIAN_PRONUNCIATION("Serbian with Ijekavian pronunciation"),
    @XmlEnumValue("Epic Sanskrit")
    EPIC_SANSKRIT("Epic Sanskrit"),
    @XmlEnumValue("Jauer dialect of Romansh")
    JAUER_DIALECT_OF_ROMANSH("Jauer dialect of Romansh"),
    @XmlEnumValue("Jyutping Cantonese Romanization")
    JYUTPING_CANTONESE_ROMANIZATION("Jyutping Cantonese Romanization"),
    @XmlEnumValue("Common Cornish orthography of Revived Cornish")
    COMMON_CORNISH_ORTHOGRAPHY_OF_REVIVED_CORNISH("Common Cornish orthography of Revived Cornish"),
    @XmlEnumValue("Standard Cornish orthography of Revived Cornish; Kernowek Standard")
    STANDARD_CORNISH_ORTHOGRAPHY_OF_REVIVED_CORNISH_KERNOWEK_STANDARD("Standard Cornish orthography of Revived Cornish; Kernowek Standard"),
    @XmlEnumValue("Classical Sanskrit")
    CLASSICAL_SANSKRIT("Classical Sanskrit"),
    @XmlEnumValue("The Lipovaz dialect of Resian; The Lipovec dialect of Resian")
    THE_LIPOVAZ_DIALECT_OF_RESIAN_THE_LIPOVEC_DIALECT_OF_RESIAN("The Lipovaz dialect of Resian; The Lipovec dialect of Resian"),
    @XmlEnumValue("Post-1917 Russian orthography")
    POST_1917_RUSSIAN_ORTHOGRAPHY("Post-1917 Russian orthography"),
    @XmlEnumValue("Slovene in Metelko alphabet")
    SLOVENE_IN_METELKO_ALPHABET("Slovene in Metelko alphabet"),
    @XmlEnumValue("Monotonic Greek")
    MONOTONIC_GREEK("Monotonic Greek"),
    @XmlEnumValue("Ndyuka dialect; Aukan dialect")
    NDYUKA_DIALECT_AUKAN_DIALECT("Ndyuka dialect; Aukan dialect"),
    @XmlEnumValue("Natisone dialect; Nadiza dialect")
    NATISONE_DIALECT_NADIZA_DIALECT("Natisone dialect; Nadiza dialect"),
    @XmlEnumValue("The Gniva dialect of Resian; The Njiva dialect of Resian")
    THE_GNIVA_DIALECT_OF_RESIAN_THE_NJIVA_DIALECT_OF_RESIAN("The Gniva dialect of Resian; The Njiva dialect of Resian"),
    @XmlEnumValue("Volap\u00fck nulik; Volap\u00fck perevid\u00f6l; Volap\u00fck nul\u00e4dik; de Jong's Volap\u00fck; New Volap\u00fck; Revised Volap\u00fck; Modern Volap\u00fck")
    VOLAPÜK_NULIK_VOLAPÜK_PEREVIDÖL_VOLAPÜK_NULÄDIK_DE_JONG_S_VOLAPÜK_NEW_VOLAPÜK_REVISED_VOLAPÜK_MODERN_VOLAPÜK("Volap\u00fck nulik; Volap\u00fck perevid\u00f6l; Volap\u00fck nul\u00e4dik; de Jong's Volap\u00fck; New Volap\u00fck; Revised Volap\u00fck; Modern Volap\u00fck"),
    @XmlEnumValue("The Oseacco dialect of Resian; The Osojane dialect of Resian")
    THE_OSEACCO_DIALECT_OF_RESIAN_THE_OSOJANE_DIALECT_OF_RESIAN("The Oseacco dialect of Resian; The Osojane dialect of Resian"),
    @XmlEnumValue("Pamaka dialect")
    PAMAKA_DIALECT("Pamaka dialect"),
    @XmlEnumValue("Petrine orthography")
    PETRINE_ORTHOGRAPHY("Petrine orthography"),
    @XmlEnumValue("Pinyin romanization")
    PINYIN_ROMANIZATION("Pinyin romanization"),
    @XmlEnumValue("Polytonic Greek")
    POLYTONIC_GREEK("Polytonic Greek"),
    @XmlEnumValue("Puter idiom of Romansh")
    PUTER_IDIOM_OF_ROMANSH("Puter idiom of Romansh"),
    @XmlEnumValue("Volap\u00fck rigik; Schleyer's Volap\u00fck; Original Volap\u00fck; Classic Volap\u00fck")
    VOLAPÜK_RIGIK_SCHLEYER_S_VOLAPÜK_ORIGINAL_VOLAPÜK_CLASSIC_VOLAPÜK("Volap\u00fck rigik; Schleyer's Volap\u00fck; Original Volap\u00fck; Classic Volap\u00fck"),
    @XmlEnumValue("Resian; Resianic; Rezijan")
    RESIAN_RESIANIC_REZIJAN("Resian; Resianic; Rezijan"),
    @XmlEnumValue("Rumantsch Grischun")
    RUMANTSCH_GRISCHUN("Rumantsch Grischun"),
    @XmlEnumValue("Scottish Standard English")
    SCOTTISH_STANDARD_ENGLISH("Scottish Standard English"),
    @XmlEnumValue("Scouse")
    SCOUSE("Scouse"),
    @XmlEnumValue("The Stolvizza dialect of Resian; The Solbica dialect of Resian")
    THE_STOLVIZZA_DIALECT_OF_RESIAN_THE_SOLBICA_DIALECT_OF_RESIAN("The Stolvizza dialect of Resian; The Solbica dialect of Resian"),
    @XmlEnumValue("The Sotavento dialect group of Kabuverdianu")
    THE_SOTAVENTO_DIALECT_GROUP_OF_KABUVERDIANU("The Sotavento dialect group of Kabuverdianu"),
    @XmlEnumValue("Surmiran idiom of Romansh")
    SURMIRAN_IDIOM_OF_ROMANSH("Surmiran idiom of Romansh"),
    @XmlEnumValue("Sursilvan idiom of Romansh")
    SURSILVAN_IDIOM_OF_ROMANSH("Sursilvan idiom of Romansh"),
    @XmlEnumValue("Sutsilvan idiom of Romansh")
    SUTSILVAN_IDIOM_OF_ROMANSH("Sutsilvan idiom of Romansh"),
    @XmlEnumValue("Belarusian in Taraskievica orthography")
    BELARUSIAN_IN_TARASKIEVICA_ORTHOGRAPHY("Belarusian in Taraskievica orthography"),
    @XmlEnumValue("Unified Cornish orthography of Revived Cornish")
    UNIFIED_CORNISH_ORTHOGRAPHY_OF_REVIVED_CORNISH("Unified Cornish orthography of Revived Cornish"),
    @XmlEnumValue("Unified Cornish Revised orthography of Revived Cornish")
    UNIFIED_CORNISH_REVISED_ORTHOGRAPHY_OF_REVIVED_CORNISH("Unified Cornish Revised orthography of Revived Cornish"),
    @XmlEnumValue("Ulster dialect of Scots")
    ULSTER_DIALECT_OF_SCOTS("Ulster dialect of Scots"),
    @XmlEnumValue("Unifon phonetic alphabet")
    UNIFON_PHONETIC_ALPHABET("Unifon phonetic alphabet"),
    @XmlEnumValue("Vedic Sanskrit")
    VEDIC_SANSKRIT("Vedic Sanskrit"),
    @XmlEnumValue("Valencian")
    VALENCIAN("Valencian"),
    @XmlEnumValue("Vallader idiom of Romansh")
    VALLADER_IDIOM_OF_ROMANSH("Vallader idiom of Romansh"),
    @XmlEnumValue("Wade-Giles romanization")
    WADE_GILES_ROMANIZATION("Wade-Giles romanization"),
    @XmlEnumValue("ALA-LC Romanization, 1997 edition")
    ALA_LC_ROMANIZATION_1997_EDITION("ALA-LC Romanization, 1997 edition"),
    @XmlEnumValue("International Phonetic Alphabet")
    INTERNATIONAL_PHONETIC_ALPHABET("International Phonetic Alphabet"),
    @XmlEnumValue("Uralic Phonetic Alphabet")
    URALIC_PHONETIC_ALPHABET("Uralic Phonetic Alphabet"),
    @XmlEnumValue("X-SAMPA transcription")
    X_SAMPA_TRANSCRIPTION("X-SAMPA transcription");
    private final String value;

    VariantNameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VariantNameType fromValue(String v) {
        for (VariantNameType c: VariantNameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
